LANG_NAME = "德语"
LANG_CODE = "de-DE"

TEMPLATES = {
    "常规文案": [
        "Der Wetterbericht sagt für heute Nachmittag Regen im Großraum Berlin voraus.",
        "Hinweis: Das System wird morgen zwischen 2:00 und 6:00 Uhr wegen Wartungsarbeiten nicht verfügbar sein.",
        "Die U-Bahn-Linie U6 ist wegen einer Signalstörung im Abschnitt Friedrichstraße–Stadtmitte unterbrochen.",
        "Das neue Mittagsmenü umfasst Vorspeise, Hauptgericht, Dessert und ein Getränk.",
        "Die Hausverwaltung informiert über die geplante Installation einer neuen Gegensprechanlage.",
        "Liebe Eltern, der Elternsprechtag findet nächsten Mittwoch um 14:30 Uhr statt.",
        "Der Deutsche Wetterdienst hat eine amtliche Unwetterwarnung für Südbayern herausgegeben.",
        "Die Stadtbibliothek öffnet nach zweiwöchiger Renovierung heute wieder ihre Türen.",
        "Diese Dokumentation begleitet das Leben der Wölfe im Bayerischen Wald.",
        "Der ICE nach München erreicht in Kürze den Hauptbahnhof Frankfurt. Bitte bereiten Sie das Aussteigen vor.",
        "Der Paketbote hat die Lieferung trotz des starken Gewitters pünktlich zugestellt.",
        "Ehrenamtliche Helfer haben am Wochenende bei der Tafel ausgeholfen.",
        "Das Deutsche Museum in München zeigt eine Sonderausstellung zur Geschichte der Luftfahrt.",
        "Während des Oktoberfests strömen Millionen Besucher aus aller Welt nach München.",
        "Die Weihnachtsfeier der Firma findet am 23. Dezember im Restaurant am Marienplatz statt.",
        "Das Bundesministerium für Bildung hat neue Richtlinien zur digitalen Bildung veröffentlicht.",
        "Die alte Bäckerei in der Altstadt verkauft jeden Tag frische Brezn, die schon am Vormittag ausverkauft sind.",
        "Den neuen Personalausweis kann man jetzt auch online über das Bürgerportal beantragen.",
        "Der neue Radweg verbindet den Englischen Garten mit dem Olympiapark.",
        "Während der Adventszeit locken die Weihnachtsmärkte mit Glühwein und gebrannten Mandeln.",
        "Heute ist Heiligabend. Die ganze Familie versammelt sich zum Festessen und Bescherung.",
        "Ihr Paket liegt in der Packstation bereit. Bitte holen Sie es mit Ihrem Abholcode ab.",
        "Die Betriebskantine bietet ab sofort auch vegane und glutenfreie Gerichte an.",
        "Im Wartezimmer läuft leise klassische Musik und sorgt für eine entspannte Atmosphäre.",
        "Die Brandschutzübung findet diesen Freitag um 10:00 Uhr in der Eingangshalle statt.",
        "Der Fliederbusch im Nachbargarten blüht und verströmt seinen Duft durch die ganze Straße.",
        "Heute ist meteorologischer Herbstanfang, aber die Temperaturen sind noch sommerlich warm.",
        "Das neue Café in der Schillerstraße feiert Eröffnung mit dem zweiten Kaffee gratis.",
        "Opa steht jeden Morgen um sechs Uhr auf und geht im Park spazieren.",
        "Die Schule informiert über die geänderten Abholzeiten ab nächster Woche.",
        "Die Lehrerin zeichnete eine Deutschlandkarte an die Tafel und fragte die Schüler nach den Landeshauptstädten.",
    ],
    "长难句": [
        "Obwohl die Bundesregierung wiederholt Maßnahmen zur Stabilisierung des Immobilienmarktes ergriffen hat, zeigen die Wohnungspreise in den Ballungsräumen keinerlei Anzeichen einer Entspannung, was bei den Wohnungssuchenden für wachsende Frustration sorgt.",
        "Wäre die Finanzkrise damals nicht mit solcher Wucht über Deutschland hereingebrochen, hätte die Reform des Bankensektors mit großer Wahrscheinlichkeit einen völlig anderen Verlauf genommen.",
        "Dieses Urteil geht weit über die Entscheidung eines Einzelfalls hinaus und schafft einen wegweisenden Präzedenzfall für die Bestimmung der Reichweite des Rechts auf informationelle Selbstbestimmung im digitalen Zeitalter.",
        "So weit die maschinelle Übersetzung auch fortgeschritten sein mag, die kulturellen Nuancen und den rhythmischen Reiz eines literarischen Werkes originalgetreu in eine andere Sprache zu übertragen, bleibt eine Aufgabe, an der die Technik noch scheitert.",
        "Laut dem Bericht des Bundesrechnungshofs hat die betreffende Behörde die internen Kontrollmechanismen bei der Mittelvergabe de facto ausgehöhlt und in zahlreichen Fällen freihändige Vergaben vorgenommen.",
        "Die wissenschaftliche Systematik, die der Entwicklung der deutschen Orthografie zugrunde liegt, verdient nicht nur aus sprachwissenschaftlicher, sondern auch aus kognitionswissenschaftlicher Sicht Anerkennung.",
        "Den demografischen Wandel allein durch finanzielle Anreize aufhalten zu wollen, verkennt die strukturellen Ursachen, die junge Menschen dazu bewegen, ländliche Regionen zu verlassen.",
        "Die Verteidigung machte geltend, dass die von der Staatsanwaltschaft vorgelegten digitalen Beweismittel unter Verstoß gegen die Strafprozessordnung erlangt worden seien und daher einem Beweisverwertungsverbot unterlägen.",
        "Was die Romane dieses Autors so verstörend macht, ist seine Weigerung, über seine Figuren moralisch zu urteilen, wodurch er den Leser zwingt, selbst ethische Schlüsse zu ziehen.",
        "In den vom Bevölkerungsrückgang bedrohten ländlichen Gebieten werden Zuzüglern großzügige Zuschüsse für Wohnraum, Kinderbetreuung und medizinische Versorgung angeboten, doch die Bleibequote bleibt enttäuschend niedrig.",
        "Die deutsche Nachkriegsgeschichte ohne Berücksichtigung der Teilung und Wiedervereinigung zu analysieren, wäre, als würde man ein Gebäude ohne sein Fundament untersuchen.",
        "Der durch den Klimawandel verursachte Anstieg des Meeresspiegels bedroht die Küstenbevölkerung, und die Frage, ob die Industrienationen ihre Emissionsreduktionsziele einhalten, ist längst zu einer Frage der globalen Gerechtigkeit geworden.",
        "Die bei der Ausgrabung entdeckten mittelalterlichen Handschriften sind nicht bloße Kunstobjekte, sondern historische Zeugnisse, die Aufschluss über die Handelsnetzwerke des mittelalterlichen Europas geben.",
        "Selbst wenn die Verhandlungen zu einem erfolgreichen Abschluss kommen, lässt sich nicht ausschließen, dass Auslegungsunterschiede zwischen den Parteien in der Umsetzungsphase erneut zu Konflikten führen.",
        "Solange die Autonomie der Lehrkräfte im Unterricht nicht gewährleistet ist, wird jede noch so ambitionierte Bildungsreform wirkungslos bleiben.",
        "Was die wissenschaftliche Kontroverse auslöste, war nicht ein methodischer Mangel der Studie, sondern ihr Ergebnis selbst, das die seit Jahrzehnten vorherrschende Lehrmeinung grundlegend infrage stellt.",
        "Der Anwalt des Klägers wandte ein, dass die vom Beklagten vorgelegten elektronischen Beweise Mängel in der Beweiskette aufwiesen und daher als unzulässig zu betrachten seien.",
        "Das Sprichwort sagt, man solle den Menschen das Fischen beibringen statt ihnen Fische zu geben – doch was nützt es, die Angel werfen zu lehren, wenn man sich keine Angel leisten kann?",
        "In einer Welt, in der globale Lieferketten eng miteinander verflochten sind, kann die Unterbrechung eines einzigen Knotenpunkts eine Kettenreaktion auslösen, deren Ausmaß jede Prognose übersteigt.",
        "Hat der Auftraggeber die Abnahme nicht innerhalb der vertraglich vereinbarten Frist durchgeführt, gilt das vom Auftragnehmer gelieferte Werk als stillschweigend abgenommen.",
        "Immer mehr Studien deuten darauf hin, dass eine langfristige Exposition gegenüber niedrig dosierten Umweltschadstoffen die neurologische Entwicklung von Kindern beeinträchtigen kann, wobei die Schäden oft erst in der Pubertät sichtbar werden.",
        "Die eigentliche Stärke dieses Regisseurs liegt darin, Empathie für jede Figur zu wecken, ohne dem Zuschauer vorzugeben, wem er sein Mitgefühl schenken soll.",
        "Obwohl die Blockchain-Technologie theoretisch das Vertrauensproblem bei grenzüberschreitenden Zahlungen lösen kann, bleiben die unterschiedlichen regulatorischen Rahmenbedingungen das größte Hindernis für eine flächendeckende Einführung.",
        "Die bei der Grabung gefundenen Bambusstreifen waren stark beschädigt, doch dank Infrarot-Bildgebung konnten mehrere bis dahin unbekannte antike Texte von außerordentlichem philologischem Wert entziffert werden.",
        "Der Entwurf dieser Brücke muss eine tägliche Verkehrsbelastung von über hunderttausend Fahrzeugen tragen und gleichzeitig die Standsicherheit bei einem Erdbeben der Stärke 7 oder höher gewährleisten.",
        "Seinen Rücktritt als rein persönliche Entscheidung zu deuten, greift zu kurz; vielmehr ist er als stiller Protest gegen die fortgesetzten ideologischen Kompromisse der Geschäftsleitung zu verstehen.",
        "Weil ein wirksamer Mechanismus zur Koordination zwischen den Ministerien fehlt, agieren die einzelnen Behörden bei plötzlichen Gesundheitskrisen isoliert und verpassen den optimalen Zeitpunkt für ein Eingreifen.",
        "Selbst die optimistischsten Wirtschaftsexperten müssen einräumen, dass angesichts der zunehmenden internationalen Handelsspannungen die Wachstumsaussichten exportorientierter Volkswirtschaften sich deutlich eingetrübt haben.",
        "Was auf den ersten Blick wie ein gewöhnlicher Streit in der Eigentümergemeinschaft aussieht, entpuppt sich bei näherer Betrachtung als ein Geflecht aus Veruntreuung der Instandhaltungsrücklage und illegalen Vorabverkäufen durch den Bauträger.",
        "Die Digitalisierung des Bildungswesens erfordert neben der Ausstattung mit Geräten auch die Fortbildung der Lehrkräfte im Bereich digitaler Kompetenzen und ein umfassendes IT-Sicherheitskonzept – drei Aspekte, die nur im Zusammenspiel wirksam sind.",
        "Je stärker eine Gesellschaft bei der Entscheidungsfindung auf künstliche Intelligenz setzt, desto dringlicher wird die Debatte über algorithmische Transparenz und die Rechenschaftspflicht derjenigen, die diese Systeme entwerfen.",
    ],
    "短文本": [
        "Bestätigen", "Abbrechen", "Senden", "Zurück", "Weiter",
        "Entwurf speichern", "Jetzt kaufen", "In den Warenkorb", "Details anzeigen", "Ausverkauft",
        "Wird geladen", "Aktualisieren", "Suchen", "Einstellungen", "Mein Konto",
        "Benachrichtigungen", "Abmelden", "Passwort ändern", "Telefon bestätigen", "Identität prüfen",
        "In Prüfung", "Genehmigt", "Abgelehnt", "Ausstehend", "Abgeschlossen",
        "Keine Daten", "Netzwerkfehler", "Bitte erneut versuchen", "Erfolgreich", "Eingabefehler",
        "Alle auswählen", "Löschen", "Bearbeiten", "Link kopieren", "Teilen",
        "Favoriten", "Gefällt mir", "Melden", "Blockieren", "Folgen",
        "Startseite", "Entdecken", "Warenkorb", "Profil", "Hilfe",
    ],
    "数字日期": [
        "Donnerstag, 14. Mai 2026",
        "Bestellsumme: 1.298,50 €",
        "Telefon: +49 30 1234 5678",
        "Mobil: +49 170 123 4567",
        "Personalausweisnummer: L01X00T47",
        "Sendungsnummer: DE1234567890123",
        "Öffnungszeiten: Mo–Fr 09:00–17:30 Uhr (Sa, So und Feiertage geschlossen)",
        "Besprechung: Montag, 1. Juni 2026, 14:00–16:30 Uhr",
        "Temperatur: min. −3 °C / max. 28 °C",
        "Stammkapital: 5.000.000 € (fünf Millionen Euro)",
        "Kfz-Kennzeichen: B AB 1234",
        "Postleitzahl: 10117",
        "Vertragsnummer: HT-2026-05-0378",
        "Kontonummer: DE89 3704 0044 0532 0130 00 (IBAN)",
        "Rechnungsbetrag: 86.400,00 € (inkl. MwSt.)",
        "Koordinaten: 52°31′12″ N, 13°24′18″ O",
        "Wohnfläche: 128,56 m² (Nutzfläche: 96,32 m²)",
        "Flug LH456, Abflug 08:45, Ankunft 11:20",
        "Passwort: 8–16 Zeichen, Groß-/Kleinbuchstaben und Ziffern erforderlich",
        "Version: v3.2.1-beta (Build 20260514)",
        "Spielstand: 3:2 (Verlängerung)",
        "Zinssatz: 4,35 % p. a. (0,3625 % monatlich)",
        "Höhe: 4.718 Meter über dem Meeresspiegel",
        "Mindesthaltbarkeitsdatum: 15.03.2027",
        "WKN: 710000 (Daimler Truck)",
        "IP-Adresse: 192.168.1.100:8080",
        "Handelsregisternummer: HRB 12345",
        "Umsatz Q3: +12,7 % gegenüber Vorjahr",
        "Packungsgröße: 500 ml × 24 Flaschen/Karton",
        "Lieferradius: 5 km, voraussichtliche Lieferzeit 30–45 Minuten",
    ],
    "特殊字符": [
        "【WICHTIGER HINWEIS】Betriebsferien 2026",
        "»Die Verwandlung« — Franz Kafkas Meisterwerk",
        "Achtung: Essen und Getränke sind im Lesesaal nicht gestattet!!!",
        "Preis: statt 29,80 € → nur 19,80 € (solange der Vorrat reicht)",
        "Bewertung: ★★★★☆ (4,5/5,0)",
        "Route: Berlin → Leipzig → Nürnberg → München",
        "Unterstützte Betriebssysteme: Windows / macOS / Linux (64 Bit)",
        "Formel: E = mc², wobei c ≈ 3×10⁸ m/s",
        "Hinweis: Alle Preise verstehen sich zzgl. MwSt. (±5 % Abweichung)",
        "Kontakt: ☎ +49 30 1234 5678 / ✉ info@beispiel.de / 📍 Kurfürstendamm",
        "Fortschritt: ████████░░ 80 %",
        "♻️ Bitte Wertstoffe in die gelbe Tonne ♻️",
        "⚠️ Gefahr: Hochspannung 380 V — Zutritt verboten! ⚠️",
        '— Goethe, Faust: „Zwei Seelen wohnen, ach! in meiner Brust…"',
        "【BEHOBEN ✓】Serverfehler 500 wurde behoben @alle",
        "Unzulässige Zeichen in Dateinamen: \\ / : * ? \" < > |",
        "Formel: ∑(i=1→n) aᵢ × bᵢ = a·b",
        "Chemie: 2H₂ + O₂ → 2H₂O (exotherme Reaktion)",
        "© 2026 Musterfirma GmbH. Alle Rechte vorbehalten.",
        "CO₂-Ausstoß: ca. 2,3 kg/km²·Jahr⁻¹",
        "Passwortstärke: schwach ☠️ / mittel ⚡ / stark 💪",
        "【Weiterleitung】@Thomas @Julia Schaut euch das an! 🔥🔥🔥",
        "Antwortmöglichkeiten: (a) richtig (b) falsch (c) unklar (d) keine Angabe",
        "1. Platz 🥇: 100.000 € | 2. Platz 🥈: 50.000 € | 3. Platz 🥉: 20.000 €",
        "═══════════════════════════════════════════",
        'Sonderzeichen: ä ö ü Ä Ö Ü ß — „…" «…» ‹…›',
        "#Reise #Essen #Alltag #Vlog",
        "✓ Erledigt  × Offen  ○ In Bearbeitung  △ Warten",
        "Emojis: 😀😂🤔😭🥰🤯👍🎉💯🔥❤️✅❌⚡🌈",
        "Mehrsprachig: Heute gab es zum Mittag phở und es war おいしかった！",
    ],
    "边界场景": [
        "a" * 200,
        " " * 50 + "Von Leerzeichen umgebener Text" + " " * 50,
        "Test\tTabulator\tgetrennt\tText",
        "Zeile 1\nZeile 2\nZeile 3\nZeile 4\nZeile 5",
        "Dies ist ein sehr langer Testtext. " + "Das System muss mit langen Zeichenketten korrekt umgehen können. " * 15,
        "",
        "   ",
        "aäoöuü Mischung von Vokalen mit und ohne Umlaut",
        "DeutschEnglish中文日本語한국어العربية mehrsprachiger Mix",
        "ＡＢＣＤＥ１２３４５ Zeichen in voller Breite",
        "①②③④⑤⑥⑦⑧⑨⑩ eingekreiste Zahlen",
        "㎡ ㎝ ㎞ ㎏ ℃ ℉ Sondereinheiten",
        "Wiederholte Zeichen!!!!!?????.....",
        "OhneLeerstelle" + "abcdefghijklmnopqrstuvwxyz" * 10,
        "Umlaute und Eszett: Ärger, Öffnung, Übung, Straße, Maß",
        "Zusammengesetzte Wörter: Donaudampfschifffahrtsgesellschaftskapitän",
        "Wiederholte Emojis: " + "😀" * 100,
        "Besondere Leerzeichen: normal geschützt dünn breit",
        "\u200ELTR-Marke und \u200FRTL-Marke gemischt",
        "Dichte Zahlen: 12345678901234567890.12345678901234567890",
        "Gemischte Satzzeichen: Test, this is a test.",
        "Gemischte Zeilenumbrüche\r\nWindows\nUnix\rAltes Mac",
        "HTML: <script>alert('XSS')</script><b>fett</b>",
        "SQL-Injection: '; DROP TABLE users; --",
        "Dateipfad: C:\\Users\\Test\\Dokumente\\Bericht.xlsx",
        "URL: https://beispiel.de/suche?stichwort=test&seite=1#ergebnis",
        "Extreme Einrückung:" + "\t" * 20 + "tief eingerückter Text",
        "Aufeinanderfolgende Leerzeilen:\n\n\n\n\nText nach 5 Leerzeilen",
        "Rechtschreibreform: Schifffahrt, Stoppschild, Delfin/Delphin",
        "Scharfes S: Straße vs. STRASSE, Maß vs. MASS",
        "Eszett-Paar: ß und ẞ (großes ß seit 2017)",
    ],
    "专业术语": [
        "Gemäß § 280 Abs. 1 BGB kann der Gläubiger Schadensersatz verlangen, wenn der Schuldner eine Pflicht aus dem Schuldverhältnis verletzt.",
        "Der Patient stellte sich mit retrosternalem Druckgefühl vor; das EKG zeigte ST-Hebungen in den Ableitungen II, III und aVF, vereinbar mit einem akuten inferioren STEMI.",
        "Das System basiert auf einer Microservice-Architektur mit einem API-Gateway für Authentifizierung und Rate Limiting; die Kommunikation zwischen den Diensten erfolgt über gRPC.",
        "Der Geschäfts- oder Firmenwert in der Konzernbilanz zum Stichtag beträgt 128 Mio. € und ist damit um 23,5 % gegenüber dem Vorjahr gestiegen.",
        "Gemäß § 253 ZPO muss die Klageschrift die Bezeichnung der Parteien, den bestimmten Antrag und die Darlegung des Klagegrundes enthalten.",
        "Histopathologischer Befund: invasives duktales Karzinom der linken Brust, Grad II. Immunhistochemie: ER(+), PR(+), HER2 (2+), FISH negativ.",
        "Das Modell erreicht eine Top-1-Genauigkeit von 87,3 % auf dem ImageNet-Validierungsdatensatz bei einer Inferenzlatenz von 2,1 ms pro Bild auf einer A100-GPU.",
        "Die Stammaktien des Emittenten wurden am 8. Mai 2026 zum Handel im regulierten Markt der Frankfurter Wertpapierbörse zugelassen. WKN: XXXXXX.",
        "Der Fonds kann in börsennotierte Aktien, Staatsanleihen, Unternehmensanleihen, Geldmarktinstrumente und Derivate investieren.",
        "Kraniales MRT mit Kontrastmittel: inhomogen kontrastmittelaufnehmende Raumforderung von 3,2 × 2,8 × 2,5 cm im rechten Temporallappen.",
        "Kommt der Schuldner der Zahlungsaufforderung nicht nach, kann das Gericht die Zwangsvollstreckung einleiten und die Pfändung von Vermögenswerten anordnen.",
        "Die Finanzierungsrunde wird von einem führenden Risikokapitalgeber angeführt; die Post-Money-Bewertung beträgt rund 3,5 Mrd. €.",
        "Die Container-Orchestrierung erfolgt über einen Kubernetes-Cluster mit Helm Charts für das Lifecycle-Management und Prometheus + Grafana für die Observability.",
        "Dieses Arzneimittel ist verschreibungspflichtig und bei Patienten mit bekannter Überempfindlichkeit gegen einen der Bestandteile kontraindiziert. Bei Leber- oder Niereninsuffizienz ist eine Dosisanpassung erforderlich.",
        "Der Lizenzgeber räumt dem Lizenznehmer das ausschließliche Vertriebsrecht für das Gebiet der Bundesrepublik Deutschland für die Dauer von drei Jahren ab Vertragsbeginn ein.",
        "Sozialversicherungsbeiträge: Arbeitgeberanteil 19,975 %, Arbeitnehmeranteil 20,225 % (inkl. Renten-, Kranken-, Pflege- und Arbeitslosenversicherung).",
        "Der HbA1c-Wert des Patienten liegt bei 9,2 %, der Nüchternblutzucker bei 14,6 mmol/L – eine intensivierte Insulintherapie wird empfohlen.",
        "Für das Training wurde der AdamW-Optimizer mit einer initialen Lernrate von 3×10⁻⁴, Cosine-Annealing-Schedule, 100 Epochen und einer Batchgröße von 256 verwendet.",
        "Der konsolidierte Konzernumsatz im Geschäftsjahr 2025 belief sich auf 5.872 Mio. € (+18,6 % ggü. Vorjahr), der Konzernjahresüberschuss auf 643 Mio. €.",
        "Das System hat eine RTO von ≤ 4 Stunden und eine RPO von ≤ 1 Stunde und erfüllt damit die Anforderungen des Business-Continuity-Plans (BCP) der Stufe 3.",
        "Klageantrag: 1. Der Beklagte wird verurteilt, die Verletzung der eingetragenen Marke zu unterlassen. 2. Der Beklagte wird verurteilt, an den Kläger Schadensersatz in Höhe von 500.000 € zu zahlen.",
        "Verordnung: Amoxicillin 500 mg Kapseln, 3 × täglich nach den Mahlzeiten, 7 Tage; Ibuprofen 300 mg retard, 2 × täglich bei Schmerzen.",
        "Der SoC wird im TSMC-5-nm-Verfahren gefertigt, integriert 12 Milliarden Transistoren und erreicht eine maximale Taktfrequenz von 3,5 GHz bei einer TDP von 65 W.",
        'Änderung der Bilanzierungsmethode: Der Konzern wendet ab dem 1. Januar 2026 IFRS 15 „Erlöse aus Verträgen mit Kunden" unter vollständiger retrospektiver Anwendung an.',
        "Konfiguration des DB-Connection-Pools: max. Verbindungen 200, min. Idle-Verbindungen 20, Verbindungs-Timeout 30 Sekunden.",
        "Gemäß § 622 BGB beträgt die Kündigungsfrist vier Wochen zum Fünfzehnten oder zum Ende eines Kalendermonats.",
        "Postoperativer Tag 3 nach Aortenklappenersatz: Vitalzeichen stabil, Drainagevolumen rückläufig; Entfernung der Thoraxdrainage für morgen geplant.",
        "Das System hält einen Durchsatz von 100k QPS bei einer p99-Latenz von ≤ 200 ms aufrecht.",
        "Diese Transaktion stellt einen wesentlichen Unternehmenserwerb dar und bedarf der Zustimmung der Hauptversammlung sowie der Freigabe durch das Bundeskartellamt.",
        "Differential-Privacy-Mechanismus: Laplace-Rauschen wird bei der Datenaggregation injiziert, Privacy-Budget ε = 1,0, um eine Re-Identifikation zu verhindern.",
    ],
    "口语俚语": [
        "Echt jetzt?! Das ist ja der Hammer! Das glaub ich nicht!",
        "Hahaha, ich kann nicht mehr! Voll der Brüller!",
        "Was? Und ich bin der Letzte, der's erfährt? Na super...",
        "Los, komm! Wenn wir zu spät kommen, ist alles weg!",
        "Das war sooo lecker! Da müssen wir unbedingt nochmal hin!",
        "Nee, das geht gar nicht. Das ist echt zu viel.",
        "Stimmt. Da hast du vollkommen recht.",
        "Keinen Bock... Heute will ich einfach gar nix machen.",
        "Krass! Das ist ja legendär! Wie geil ist das denn?!",
        "Okay, alles klar, ich kümmere mich drum!",
        "Voll der Neid... Ich will auch in den Urlaub!",
        "Hm, also... das ist so eine Sache... schwer zu sagen...",
        "Boah, wie nervig! Schon wieder Regen!",
        "Wollen wir was essen gehen? Ich hab mega Hunger.",
        "Alter, du bist echt ein Genie! Bester im Test? Stark!",
        "Bist du verrückt? Wer macht denn so was?",
        "Hab's einfach so gemacht. Ist doch nichts Besonderes.",
        "Tut mir leid, dass ich nochmal nerve, aber ich bräuchte nochmal Hilfe...",
        "Bleib locker, ja? Ist doch kein Weltuntergang.",
        "Das reicht so. Mehr braucht's nicht.",
        "Boah, wie krass! Einfach nur wow!",
        "Meinetwegen. Mach, wie du willst.",
        "Lass gut sein, ja? Hör auf damit.",
        "Voll cool! Da will ich auch hin!",
        "Vergiss das bloß nicht, hörst du?! Das ist wichtig!",
        "Geht klar! Mach ich sofort!",
        "Mann, ist das schwer... Mir raucht der Kopf.",
        "AHHH!!! Meine Lieblingsband kommt nach Deutschland!!! Tickets!!!",
        "Ähm... naja... ach, egal...",
        "Hey, kannst du mir mal kurz helfen? Ist echt dringend!",
        "Beeil dich! Nur noch wenige Stück!",
    ],
}
