LANG_NAME = "英语"
LANG_CODE = "en-GB"

TEMPLATES = {
    "常规文案": [
        "The council has announced that roadworks on the high street will continue until the end of the month.",
        "Passengers are advised to check for any service disruptions before travelling this weekend.",
        "A new community centre is set to open in the village, offering classes and activities for all ages.",
        "The supermarket has recalled a batch of ready meals due to incorrect allergen labelling.",
        "Residents are kindly reminded to put their bins out by seven o'clock on collection day.",
        "The charity fun run raised over fifteen thousand pounds for the local children's hospital.",
        "Fog and ice warnings have been issued for much of the south-east overnight.",
        "The headteacher sent a letter to parents regarding changes to the school uniform policy.",
        "A planning application for thirty new homes on the outskirts of town has been submitted to the council.",
        "The library will be closed on bank holidays but will remain open on Saturdays as usual.",
        "A lorry has broken down on the M25, causing significant delays during the morning rush hour.",
        "The GP surgery is now accepting online bookings for flu vaccinations.",
        "Police are appealing for witnesses following a burglary in the Elm Road area last Tuesday evening.",
        "The local cricket club has announced trials for the under-sixteen squad next Saturday.",
        "Water companies have urged customers to report any leaks during the ongoing cold snap.",
        "The museum's new exhibition explores the social history of the textile industry in Lancashire.",
        "A consultation on proposed changes to parking charges in the town centre closes on Friday.",
        "The annual village fête will take place on the first Saturday of July on the recreation ground.",
        "Engineers have been called to repair a burst water main affecting several streets in the area.",
        "The council's recycling rate has improved to fifty-two per cent, up from forty-seven per cent last year.",
        "Rail passengers face disruption this weekend as engineering work takes place between London and Bristol.",
        "A new cycle lane has been completed, linking the station to the business park.",
        "The school governors have approved a proposal to extend the breakfast club hours.",
        "Strong winds have brought down trees and power lines across parts of the West Midlands.",
        "The neighbourhood watch scheme is holding a meeting at the church hall on Wednesday evening.",
        "A popular café on the seafront has been forced to close temporarily after a kitchen fire.",
        "The NHS trust has confirmed that waiting times for outpatient appointments have been reduced.",
        "Motorists are being warned of surface water on many roads following heavy overnight rain.",
        "The farmers' market will return to the square every other Thursday from next month.",
        "A local teenager has been selected to represent Great Britain at the European athletics championships.",
        "The parish council has agreed to fund new playground equipment for the recreation ground.",
    ],
    "长难句": [
        "Notwithstanding the amendments proposed during the third reading of the bill, the opposition caucus maintained that the legislation fundamentally undermined workers' collective bargaining rights.",
        "The arbitration panel ruled that the subcontractor's failure to disclose the material defect constituted a breach of the implied warranty of merchantability, thereby entitling the claimant to consequential damages.",
        "Had the central bank intervened earlier by raising the benchmark interest rate, the inflationary spiral that eroded consumers' purchasing power throughout the second quarter might have been averted.",
        "The committee's interim findings suggest that, whilst the overall mortality rate has declined, health inequalities between socioeconomic groups have widened considerably over the past decade.",
        "It is precisely because the regulatory framework was designed with legacy industries in mind that it fails to accommodate the decentralised nature of blockchain-based financial instruments.",
        "The archaeological excavation, which had been painstakingly conducted over the course of seven field seasons, unearthed a trove of cuneiform tablets that challenged prevailing assumptions about Bronze Age trade networks.",
        "Delegates were reminded that any motion to amend the constitution requires a two-thirds supermajority, and that proxy votes cast after the registration deadline shall be deemed inadmissible.",
        "The CEO's assertion that the restructuring would not result in compulsory redundancies rang hollow when, within a fortnight, over three hundred employees received notice of termination.",
        "Insofar as the plaintiff can demonstrate that the defendant's negligence was the proximate cause of the injury, the burden of proof shifts to the defendant to establish contributory fault.",
        "The phenomenon whereby migratory birds recalibrate their internal compass using the Earth's magnetic field has been the subject of intensive research, yet the precise biomolecular mechanism remains elusive.",
        "Whilst the minister acknowledged that the previous administration's austerity measures had disproportionately affected vulnerable communities, she stopped short of committing additional ring-fenced funding for social care.",
        "The peer-reviewed meta-analysis, which synthesised data from forty-seven randomised controlled trials spanning four continents, concluded that the intervention yielded a statistically significant but clinically modest effect.",
        "One cannot overstate the extent to which colonial-era cartographic practices shaped contemporary border disputes, particularly in regions where ethnic and linguistic boundaries were deliberately disregarded.",
        "Were it not for the whistle-blower's testimony, which the internal audit team initially dismissed as unsubstantiated, the multi-million-pound procurement fraud would have gone undetected for years.",
        "The extent to which algorithmic bias perpetuates systemic discrimination in housing, employment, and criminal justice has become a central concern for regulators on both sides of the Atlantic.",
        "By the time the regulatory body issued its enforcement notice, the company had already relocated its servers to a jurisdiction where data-protection legislation was markedly less stringent.",
        "The philosopher's argument rests on the premise that moral intuitions, however deeply felt, cannot serve as epistemically reliable foundations for normative ethical theory without independent rational justification.",
        "What the report conspicuously omits is any acknowledgement of the structural factors—decades of underinvestment, punitive welfare conditionality, and the erosion of collective bargaining—that gave rise to the crisis in the first place.",
        "The orchestra's interpretation of the symphony, far from adhering slavishly to historically informed performance practice, brought a distinctly contemporary sensibility to the phrasing that divided critics but captivated the audience.",
        "The very premise upon which the economic model rests—namely, that rational agents possess perfect information and act solely to maximise utility—has been so thoroughly discredited by behavioural economics that its continued use borders on intellectual negligence.",
        "By conflating procedural compliance with substantive justice, the regulatory framework inadvertently creates perverse incentives for organisations to prioritise box-ticking exercises over genuine risk mitigation.",
        "It would be intellectually dishonest to evaluate the outcomes of the intervention without acknowledging that the baseline conditions in the treatment group differed materially from those in the control group.",
        "The paradox at the heart of democratic governance is that the institutions designed to protect minority rights from majoritarian tyranny must themselves derive their legitimacy from the very majoritarian processes they seek to constrain.",
        "Notwithstanding the considerable body of jurisprudence developed by the European Court of Human Rights on the right to privacy, member states retain a wide margin of appreciation in balancing this right against competing public interests.",
        "The government's assertion that the new surveillance legislation contains adequate safeguards against abuse rings hollow in light of the intelligence services' documented history of overreach.",
        "Not only did the contractor fail to meet the contractual deadline, but the quality of the deliverables fell so far below the agreed specifications that the client invoked the termination clause without prior notice.",
        "The longitudinal study, which tracked over twelve thousand participants across three decades, found that socioeconomic status at birth remained the single strongest predictor of health outcomes in later life.",
        "The diplomatic cable, which was never intended for public consumption, reveals a degree of scepticism among senior officials about the viability of the peace accord that stands in stark contrast to their public pronouncements.",
        "However laudable the charity's objectives may be, its governance structure—marked by an absence of independent oversight and opaque financial reporting—raises serious questions about accountability.",
        "The notion that economic growth and environmental sustainability are inherently incompatible has been increasingly challenged by proponents of circular economy models.",
    ],
    "短文本": [
        "Submit", "Cancel", "Proceed", "Go back", "Next step",
        "Save draft", "Buy now", "Add to basket", "View details", "Sold out",
        "Loading…", "Refresh", "Search", "Settings", "My account",
        "Notifications", "Sign out", "Change password", "Verify email", "Accept terms",
        "Under review", "Approved", "Rejected", "Pending", "Completed",
        "No results found", "Network error", "Please try again", "Success", "Invalid input",
        "Select all", "Delete", "Edit", "Copy link", "Share",
        "Bookmark", "Like", "Report", "Block user", "Follow",
        "Home", "Explore", "Basket", "Profile", "Help centre",
    ],
    "数字日期": [
        "14 May 2026",
        "Order total: £1,298.50",
        "Telephone: 020 7946 0958",
        "Mobile: 07700 900123",
        "National Insurance number: QQ 12 34 56 C",
        "Royal Mail tracking: RN123456789GB",
        "Opening hours: Mon–Fri 09:00–17:30",
        "Meeting: Monday 1 June 2026, 14:00–16:30 BST",
        "Temperature range: −15 °C to 42 °C",
        "Share capital: £5,000,000.00 (five million pounds sterling)",
        "Vehicle registration: AB12 CDE",
        "Postcode: SW1A 1AA",
        "Contract ref: HT-2026-05-0378",
        "Sort code: 20-00-00 / Account: 12345678",
        "Invoice amount: £86,400.00 (incl. VAT)",
        "Coordinates: 51°30′26″N, 0°7′39″W",
        "Floor area: 128.56 m² (gross internal area)",
        "Flight BA0234, departs 08:45, arrives 11:20 GMT",
        "Password: 8–16 characters, must include uppercase, lowercase, and digits",
        "Version 3.2.1-beta (build 20260514)",
        "Final score: 3–2 (after extra time)",
        "Interest rate: 4.35% p.a. (0.3625% monthly)",
        "Elevation: 4,718 metres above sea level",
        "Best before: 15 March 2027",
        "FTSE ticker: HSBA.L",
        "IP address: 192.168.1.100:8080",
        "Company number: 01234567",
        "Q3 revenue up 12.7% year-on-year",
        "Pack size: 500 ml × 24 bottles per case",
        "Delivery radius: 5 miles, estimated 30–45 minutes",
    ],
    "特殊字符": [
        "【IMPORTANT NOTICE】Regarding the bank holiday schedule for 2026",
        "'Pride and Prejudice' — a masterpiece of English literature",
        "Reminder: No food or drink in the auditorium!!!",
        "Price: was £299 → now £199 (limited-time offer)",
        "Rating: ★★★★☆ (4.5/5.0)",
        "Route: London → Paris → Berlin → Prague → Vienna",
        "Supported OS: Windows / macOS / Linux (64-bit)",
        "Formula: E = mc², where c ≈ 3 × 10⁸ m/s",
        "Note: prices exclude VAT (±5% variance)",
        "Contact: ☎ 020 7946 0958 / ✉ info@example.co.uk / 📍 Westminster",
        "Progress: ████████░░ 80%",
        "♻️ Please place recyclable waste in the blue bin ♻️",
        "⚠️ Warning: 380V — authorised personnel only! ⚠️",
        "— Shakespeare, Hamlet, Act III, Scene I: 'To be, or not to be…'",
        "[RESOLVED ✓] Server 500 error has been fixed @all",
        "Filenames must not contain: \\ / : * ? \" < > |",
        "Maths: ∑(i=1→n) aᵢ × bᵢ = a·b",
        "Chemistry: 2H₂ + O₂ → 2H₂O (exothermic)",
        "© 2026 Example Ltd. All rights reserved.",
        "CO₂ emissions: approx. 2.3 kg/km²·yr⁻¹",
        "Password strength: weak ☠️ / medium ⚡ / strong 💪",
        "[FWD] @John @Sarah — have a look at this! 🔥🔥🔥",
        "Options: (A) True  (B) False  (C) Uncertain  (D) None of the above",
        "1st 🥇 £10,000 | 2nd 🥈 £5,000 | 3rd 🥉 £2,000",
        "═══════════════════════════════════════════",
        "IPA: /ˌɪntəˈnæʃənəl/",
        "Tags: #travel #foodie #lifestyle #vlog",
        "✓ Done  ✗ Not done  ○ In progress  △ Awaiting confirmation",
        "Emoji test: 😀😂🤔😭🥰🤯👍🎉💯🔥❤️✅❌⚡🌈",
        "Mixed script: I had おにぎり for lunch — not bad at all",
    ],
    "边界场景": [
        "a" * 200,
        " " * 50 + "surrounded by spaces" + " " * 50,
        "tab\tseparated\tvalues\there",
        "line one\nline two\nline three\nline four\nline five",
        "This is a very long sentence that keeps going " + "and going " * 30 + "until it finally stops.",
        "",
        "   ",
        "a中b文c混d排e测f试g",
        "English中文混合テスト한국어ทดสอบMultilingual مختلط",
        "ＡＢＣＤＥ１２３４５ fullwidth characters ａｂｃｄｅ",
        "𠀀𠀁𠀂 CJK Extension B rare characters test",
        "zero​width​space​test",
        "()[]{}⟨⟩«»‹› various bracket types",
        "①②③④⑤⑥⑦⑧⑨⑩ circled numbers",
        "㎡ ㎝ ㎞ ㎏ ℃ ℉ special units",
        "Consecutive punctuation!!!!!?????.....",
        "nospaces" + "abcdefghijklmnopqrstuvwxyz" * 10,
        "Colour vs color, favourite vs favorite, organisation vs organization — British vs American spelling",
        "Ligatures: ﬁ ﬂ ﬀ ﬃ ﬄ — ﬁnd ﬂoor oﬀer",
        "Repeated emoji: " + "😀" * 100,
        "Special whitespace: normal non-breaking thin em-space",
        "\u200ELTR mark and \u200FRTL mark mixed",
        "Dense digits: 12345678901234567890.123456789012345678901234567890",
        'Mixing British and American punctuation, this is "acceptable".',
        "Mixed line endings\r\nWindows\nUnix\rOld Mac",
        "HTML tags: <script>alert('XSS')</script><b>bold</b>",
        "SQL injection: '; DROP TABLE users; --",
        "Path test: C:\\Users\\Test\\Documents\\report.xlsx",
        "URL: https://example.com/search?q=test&page=1#results",
        "Extreme indentation:" + "\t" * 20 + "deeply indented text",
        "Multiple blank lines:\n\n\n\n\nText after five blank lines",
    ],
    "专业术语": [
        "Pursuant to Section 75 of the Consumer Credit Act 1974, the credit card provider is jointly and severally liable with the supplier for any breach of contract or misrepresentation.",
        "The patient presented with retrosternal crushing chest pain radiating to the left shoulder; ECG showed ST-segment elevation — provisional diagnosis: acute STEMI.",
        "The platform employs a microservices architecture with an API gateway handling authentication and rate limiting; inter-service communication uses gRPC over mTLS.",
        "As at the reporting date, goodwill recognised on the consolidated balance sheet amounted to £128 million, representing a year-on-year increase of 23.5%.",
        "Under CPR Part 36, a claimant who fails to obtain a judgment more advantageous than a defendant's Part 36 offer will ordinarily be ordered to pay the defendant's costs from the date of expiry of the relevant period.",
        "Histopathology report: left breast — invasive ductal carcinoma, grade II; IHC: ER+, PR+, HER2 2+ (FISH negative).",
        "The model achieves a Top-1 accuracy of 87.3% on the ImageNet validation set with an inference latency of 2.1 ms per image on an A100 GPU.",
        "The issuer's ordinary shares were admitted to trading on the London Stock Exchange Main Market on 8 May 2026 under ticker XYZ.",
        "The fund may invest in transferable securities, money-market instruments, units in collective investment schemes, deposits, and financial derivative instruments.",
        "MRI brain with contrast: right temporal lobe — heterogeneously enhancing mass lesion measuring 3.2 × 2.8 × 2.5 cm; differential includes high-grade glioma.",
        "A winding-up petition was presented against the company under Section 122(1)(f) of the Insolvency Act 1986 on the grounds that it is unable to pay its debts.",
        "The Series B round was led by Sequoia Capital, with participation from Accel and Index Ventures, at a post-money valuation of approximately $350 million.",
        "Container orchestration uses a Kubernetes cluster managed via Helm charts; observability is provided by Prometheus and Grafana across the full request lifecycle.",
        "This product is a prescription-only medicine (POM); it is contraindicated in patients with known hypersensitivity to any of its components. Dose adjustment is required in hepatic or renal impairment.",
        "The Licensor grants the Licensee an exclusive licence to distribute the Products within the United Kingdom for a period of three years from the Effective Date.",
        "Employer NIC rate: 13.8% on earnings above the secondary threshold (£175 per week for 2025/26).",
        "HbA1c: 9.2%; fasting glucose: 14.6 mmol/L — recommend initiation of basal-bolus insulin regimen.",
        "Training used the AdamW optimiser with an initial learning rate of 3 × 10⁻⁴ and cosine annealing over 100 epochs; batch size 256.",
        "Revenue for FY 2025 was £587.2 million, up 18.6% year-on-year; profit attributable to equity holders was £64.3 million.",
        "The system's RTO is ≤ 4 hours and RPO ≤ 1 hour, meeting Tier III business-continuity requirements.",
        "Relief sought: (1) an injunction restraining the defendant from further infringement of the claimant's registered trade mark; (2) damages or, at the claimant's election, an account of profits.",
        "Rx: amoxicillin capsules 500 mg t.d.s. p.o. × 7 days; ibuprofen SR capsules 300 mg b.d. p.o. p.r.n.",
        "The SoC is fabricated on TSMC's 5 nm process, integrating 12 billion transistors; peak clock speed 3.5 GHz, TDP 65 W.",
        "Change in accounting policy: the Group adopted IFRS 15 Revenue from Contracts with Customers from 1 January 2026 using the fully retrospective method.",
        "Connection pool: max connections 200, min idle 20, connection timeout 30 s.",
        "Under Section 139 of the Employment Rights Act 1996, an employee dismissed by reason of redundancy is entitled to a statutory redundancy payment calculated by reference to age, length of service, and weekly pay.",
        "Post-operative day three following aortic valve replacement: haemodynamically stable, chest-drain output decreasing; plan to remove drain tomorrow.",
        "Throughput: the system sustains 100k QPS at p99 latency ≤ 200 ms.",
        "The transaction constitutes a Class 1 transaction under the Listing Rules and requires the approval of shareholders in general meeting.",
        "Differential privacy: Laplacian noise is injected during data aggregation with a privacy budget ε = 1.0 to prevent re-identification of individuals.",
    ],
    "口语俚语": [
        "That's absolutely mental, mate — I can't believe they actually did that.",
        "Gutted. I was so close to getting tickets but they sold out in seconds.",
        "Fancy a cuppa? I'm putting the kettle on.",
        "He proper stitched me up — told everyone about the surprise before the party.",
        "I'm chuffed to bits, honestly. Best news I've had all week.",
        "Can't be arsed to cook tonight. Shall we just get a takeaway?",
        "She's well fit, not gonna lie.",
        "That exam was an absolute doddle — finished it in half the time.",
        "Cheers for sorting that out, you're a legend.",
        "I'm knackered. Been on my feet since six this morning.",
        "Stop taking the mick — I'm being serious here.",
        "He was gobsmacked when he found out he'd got the job.",
        "It's chucking it down out there — I'm not going anywhere.",
        "Don't be daft, of course you can stay for dinner.",
        "Blimey, that was close! Nearly walked into a lamppost.",
        "I'm skint until payday — can you spot me a tenner?",
        "The traffic was murder this morning — took me two hours to get in.",
        "She went absolutely ballistic when she saw the mess in the kitchen.",
        "No worries, I'll crack on with it first thing Monday morning.",
        "Bit of a shambles, that meeting — nobody had a clue what was going on.",
        "He's having a laugh if he thinks I'm paying that much for parking.",
        "Sod's law, innit — the one day I forget my brolly, it buckets down.",
        "Fair enough, I suppose that's one way to look at it.",
        "You're winding me up — there's no way that's true.",
        "I'm buzzing — just booked flights to Tenerife for next month!",
        "Nowt wrong with it, if you ask me.",
        "Dead good, that film — you should definitely watch it.",
        "My flatmate's done a runner without paying his share of the rent.",
        "Bog standard laptop, nothing fancy, but it does the job.",
        "Couldn't give a toss what they think — I'm doing it anyway.",
        "She's absolutely smashing it at work, fair play to her.",
    ],
}
