LANG_NAME = "西班牙语"
LANG_CODE = "es-ES"

TEMPLATES = {
    "常规文案": [
        "El pronóstico del tiempo indica que esta tarde habrá lluvias dispersas en la zona metropolitana de Madrid.",
        "Aviso: el sistema estará fuera de servicio mañana de 2:00 a 6:00 de la madrugada por tareas de mantenimiento.",
        "La línea 3 del metro de Barcelona sufre retrasos por una avería en la señalización.",
        "El nuevo menú del día incluye primer plato, segundo plato, postre y bebida por 12,50 euros.",
        "La comunidad de vecinos ha convocado una junta extraordinaria para tratar la instalación del ascensor.",
        "Estimados padres y madres: la reunión de tutoría será el próximo miércoles a las 14:30 horas.",
        "La Agencia Estatal de Meteorología ha activado la alerta naranja por lluvias torrenciales en la Comunidad Valenciana.",
        "La biblioteca municipal reabre hoy sus puertas tras dos semanas de reformas.",
        "Este documental recorre la vida silvestre del Parque Nacional de Doñana.",
        "El AVE con destino Sevilla efectuará su llegada en breves minutos. Preparen su equipaje, por favor.",
        "El repartidor entregó el pedido puntualmente a pesar de la fuerte tormenta.",
        "Un grupo de voluntarios organizó una recogida de alimentos para el banco de alimentos local.",
        "El Museo del Prado inaugura una exposición temporal dedicada a la obra de Velázquez.",
        "Durante las fiestas de San Fermín, las calles de Pamplona se llenan de visitantes de todo el mundo.",
        "La cena de empresa de Navidad se celebrará el 23 de diciembre en un restaurante del centro.",
        "El Ministerio de Educación ha anunciado cambios en el currículo de educación primaria.",
        "La panadería del barrio vende empanadas artesanales que se agotan cada día antes del mediodía.",
        "Ya se puede renovar el DNI electrónico a través de la sede electrónica del Gobierno.",
        "El nuevo carril bici conecta el parque del Retiro con la estación de Atocha.",
        "Durante la Semana Santa, los principales monumentos de Sevilla requieren reserva previa.",
        "Hoy es Nochebuena. Toda la familia se reúne para cenar y abrir los regalos.",
        "Su paquete ha llegado al punto de recogida. Puede recogerlo con su código de verificación.",
        "El comedor universitario ha incorporado opciones veganas y sin gluten al menú diario.",
        "En la sala de espera suena una suave melodía de guitarra clásica que invita a la calma.",
        "El simulacro de evacuación tendrá lugar este viernes a las 10:00 en el vestíbulo principal.",
        "El naranjo del patio del vecino ha florecido y el aroma llega hasta nuestra ventana.",
        "Hoy es el solsticio de verano, el día más largo del año en el hemisferio norte.",
        "La nueva cafetería de especialidad ofrece la segunda taza a mitad de precio en su inauguración.",
        "El abuelo se levanta cada mañana a las seis para pasear por el parque con su perro.",
        "El colegio informa de que a partir de la semana que viene cambia el horario de recogida.",
        "La profesora dibujó el mapa de España en la pizarra y pidió a los alumnos que señalaran las capitales de provincia.",
    ],
    "长难句": [
        "A pesar de que el Gobierno ha implementado sucesivas medidas para estabilizar el mercado inmobiliario, los precios de la vivienda en las grandes ciudades siguen sin dar señales de moderación, lo que genera una creciente frustración entre los compradores de primera vivienda.",
        "Si en aquel momento la crisis financiera no hubiera estallado con tanta virulencia, es muy probable que la reforma del sistema bancario español habría tomado un rumbo completamente diferente al que conocemos hoy.",
        "Esta sentencia no se limita a resolver un caso particular, sino que sienta un precedente de enorme trascendencia para delimitar el alcance del derecho al olvido digital en el ámbito de la Unión Europea.",
        "Por más que la inteligencia artificial avance en el campo de la traducción automática, trasladar con fidelidad los matices culturales y la musicalidad de una obra literaria sigue siendo un desafío que la tecnología no ha conseguido superar.",
        "Según el informe del Tribunal de Cuentas, el organismo público investigado adjudicó contratos a dedo de manera reiterada, vulnerando los principios de publicidad y libre concurrencia exigidos por la Ley de Contratos del Sector Público.",
        "La riqueza lingüística del español, con sus variantes dialectales repartidas por más de veinte países, constituye un patrimonio cultural cuya diversidad no debe entenderse como fragmentación, sino como fuente inagotable de creatividad.",
        "Pretender resolver el problema de la despoblación rural únicamente con incentivos económicos revela un desconocimiento profundo de las causas estructurales que impulsan a los jóvenes a abandonar los pueblos.",
        "La defensa del acusado alegó que las pruebas electrónicas presentadas por la fiscalía habían sido obtenidas sin la correspondiente autorización judicial, por lo que debían ser declaradas nulas de pleno derecho.",
        "Lo que hace que las novelas de este autor resulten inquietantes para el lector es que se niega a emitir juicios morales sobre sus personajes, obligando al lector a extraer sus propias conclusiones éticas.",
        "En las comarcas rurales amenazadas por la despoblación, las administraciones ofrecen ayudas a la vivienda, bonificaciones fiscales e incluso empleo público para atraer nuevos pobladores, pero la tasa de arraigo sigue siendo decepcionante.",
        "Analizar la historia contemporánea de España sin tener en cuenta el impacto de la Guerra Civil y la dictadura posterior equivaldría a estudiar un edificio ignorando sus cimientos.",
        "El aumento del nivel del mar provocado por el cambio climático amenaza a las poblaciones costeras, y el cumplimiento de los compromisos de reducción de emisiones por parte de los países industrializados se ha convertido en una cuestión de justicia global.",
        "Las piezas de cerámica ibérica halladas en la excavación no son meros objetos decorativos, sino testimonios materiales que arrojan luz sobre las redes comerciales del Mediterráneo occidental en la Antigüedad.",
        "Aun en el supuesto de que las negociaciones lleguen a buen puerto, las diferencias de interpretación entre las partes podrían reavivar el conflicto en la fase de ejecución, lo que hace imprescindible un protocolo de seguimiento riguroso.",
        "Mientras no se garantice la autonomía del profesorado en el aula, cualquier reforma educativa, por ambiciosa que sea en su diseño, estará condenada a quedarse en papel mojado.",
        "Lo que provocó el revuelo académico no fue un fallo metodológico del estudio, sino la conclusión misma, que contradice frontalmente la teoría dominante en el campo durante las últimas tres décadas.",
        "El abogado de la parte demandante sostuvo que las evidencias digitales aportadas por el demandado adolecían de vicios en su cadena de custodia que las invalidaban como prueba.",
        "Dice el refrán que más vale maña que fuerza, pero cuando ni siquiera se dispone de las herramientas básicas, de poco sirve la habilidad para emplearlas.",
        "En un mundo en el que las cadenas de suministro globales están entrelazadas de forma cada vez más compleja, la interrupción de un solo eslabón puede desencadenar efectos en cascada cuya magnitud supera cualquier previsión.",
        "Si la parte compradora no completa la inspección dentro del plazo estipulado en el contrato, se entenderá que acepta tácitamente la conformidad del producto entregado con los estándares de calidad pactados.",
        "Cada vez son más las evidencias científicas que apuntan a que la exposición prolongada a contaminantes ambientales en dosis bajas puede causar daños neurológicos en los niños que no se manifiestan hasta la adolescencia.",
        "El verdadero talento de este director radica en su capacidad para suscitar la empatía del espectador hacia cada personaje sin necesidad de señalar explícitamente a quién debe compadecerse.",
        "Aunque la tecnología blockchain puede, en teoría, resolver el problema de la confianza en los pagos transfronterizos, la disparidad entre los marcos regulatorios nacionales sigue siendo el principal obstáculo para su adopción a gran escala.",
        "Los pergaminos descubiertos en la excavación presentaban un deterioro severo, pero gracias a la reflectografía infrarroja se logró descifrar varios textos medievales inéditos de extraordinario valor filológico.",
        "El diseño de este puente debe soportar una carga de más de cien mil vehículos diarios y, al mismo tiempo, garantizar la integridad estructural ante un terremoto de magnitud 7 o superior.",
        "Sería un error interpretar su dimisión como una decisión meramente personal; en realidad, constituye una protesta silenciosa contra las sucesivas concesiones ideológicas de la junta directiva.",
        "La ausencia de un mecanismo eficaz de coordinación interministerial provoca que, ante una emergencia sanitaria, cada organismo actúe de forma aislada y se pierda el momento óptimo de intervención.",
        "Hasta los analistas más optimistas reconocen que, en un contexto de escalada de tensiones comerciales internacionales, las perspectivas de crecimiento de las economías orientadas a la exportación se han ensombrecido considerablemente.",
        "Lo que a primera vista parece un simple conflicto vecinal por los gastos de comunidad esconde, tras una investigación más profunda, un entramado de irregularidades que incluye la apropiación indebida del fondo de reserva.",
        "Impulsar la transformación digital de la enseñanza exige abordar de forma simultánea la dotación tecnológica, la formación del profesorado y la ciberseguridad, como un todo inseparable.",
        "Cuanto más depende una sociedad de la inteligencia artificial para la toma de decisiones, más urgente se vuelve el debate sobre la transparencia algorítmica y la rendición de cuentas de quienes diseñan esos sistemas.",
    ],
    "短文本": [
        "Confirmar", "Cancelar", "Enviar", "Volver", "Siguiente",
        "Guardar borrador", "Comprar ahora", "Añadir al carrito", "Ver detalles", "Agotado",
        "Cargando", "Actualizar", "Buscar", "Ajustes", "Mi cuenta",
        "Notificaciones", "Cerrar sesión", "Cambiar contraseña", "Verificar teléfono", "Verificar identidad",
        "En revisión", "Aprobado", "Rechazado", "Pendiente", "Completado",
        "Sin datos", "Error de red", "Inténtelo de nuevo", "Correcto", "Error de entrada",
        "Seleccionar todo", "Eliminar", "Editar", "Copiar enlace", "Compartir",
        "Favoritos", "Me gusta", "Denunciar", "Bloquear", "Seguir",
        "Inicio", "Explorar", "Carrito", "Perfil", "Ayuda",
    ],
    "数字日期": [
        "Jueves, 14 de mayo de 2026",
        "Importe del pedido: 1.298,50 €",
        "Teléfono: +34 91 123 45 67",
        "Móvil: +34 612 345 678",
        "DNI: 12345678-Z",
        "N.º de seguimiento: ES1234567890123",
        "Horario: lunes a viernes, 09:00–17:30 (sábados, domingos y festivos cerrado)",
        "Reunión: lunes 1 de junio de 2026, 14:00–16:30",
        "Temperatura: mínima −3 °C / máxima 28 °C",
        "Capital social: 5.000.000 € (cinco millones de euros)",
        "Matrícula: 1234 BCD",
        "Código postal: 28001",
        "N.º de contrato: HT-2026-05-0378",
        "Cuenta bancaria: ES91 2100 0418 4502 0005 1332",
        "Importe factura: 86.400,00 € (IVA incluido)",
        "Coordenadas: 40°25′01″ N, 3°42′13″ O",
        "Superficie: 128,56 m² (superficie útil: 96,32 m²)",
        "Vuelo IB6123, salida 08:45, llegada 11:20",
        "Contraseña: 8-16 caracteres, con mayúsculas, minúsculas y números",
        "Versión: v3.2.1-beta (compilación 20260514)",
        "Resultado: 3-2 (prórroga)",
        "Tipo de interés: 4,35 % anual (0,3625 % mensual)",
        "Altitud: 4.718 metros sobre el nivel del mar",
        "Fecha de caducidad: 15/03/2027",
        "Código ISIN: ES0178430E18 (Telefónica)",
        "Dirección IP: 192.168.1.100:8080",
        "CIF: B-12345678",
        "Ventas del 3.er trimestre: +12,7 % interanual",
        "Formato: 500 ml × 24 unidades/caja",
        "Radio de entrega: 5 km; tiempo estimado: 30-45 minutos",
    ],
    "特殊字符": [
        "【AVISO IMPORTANTE】Calendario de festivos 2026",
        "«Don Quijote de la Mancha» — obra cumbre de la literatura española",
        "¡Atención! Prohibido el paso de alimentos y bebidas.",
        "Precio: de 29,80 € → a 19,80 € (oferta limitada)",
        "Valoración: ★★★★☆ (4,5/5,0)",
        "Ruta: Madrid → Córdoba → Sevilla → Granada",
        "SO compatibles: Windows / macOS / Linux (64 bits)",
        "Fórmula: E = mc², donde c ≈ 3×10⁸ m/s",
        "Nota: precios sin IVA (±5 % de variación)",
        "Contacto: ☎ +34 91 123 4567 / ✉ info@ejemplo.es / 📍 Gran Vía, Madrid",
        "Progreso: ████████░░ 80 %",
        "♻️ Deposite los envases en el contenedor amarillo ♻️",
        "⚠️ Peligro: alta tensión 380 V — Prohibido el acceso ⚠️",
        "— Cervantes, Don Quijote: «En un lugar de la Mancha, de cuyo nombre no quiero acordarme…»",
        "【RESUELTO ✓】Error 500 del servidor corregido @todos",
        "Caracteres no permitidos en nombres de archivo: \\ / : * ? \" < > |",
        "Fórmula: ∑(i=1→n) aᵢ × bᵢ = a·b",
        "Química: 2H₂ + O₂ → 2H₂O (reacción exotérmica)",
        "© 2026 Empresa Ejemplo, S.L. Todos los derechos reservados.",
        "Emisión de CO₂: aprox. 2,3 kg/km²·año⁻¹",
        "Seguridad de contraseña: débil ☠️ / media ⚡ / fuerte 💪",
        "【Reenviar】@Carlos @María ¡echad un vistazo a esto! 🔥🔥🔥",
        "Opciones: (a) Verdadero (b) Falso (c) No se sabe (d) Ninguna de las anteriores",
        "1.º 🥇: 100.000 € | 2.º 🥈: 50.000 € | 3.º 🥉: 20.000 €",
        "═══════════════════════════════════════════",
        "Signos propios: ¿…? ¡…! « » — ñ Ñ á é í ó ú ü",
        "#viajes #gastronomía #vidacotidiana #vlog",
        "✓ Hecho  × Pendiente  ○ En curso  △ En espera",
        "Emojis: 😀😂🤔😭🥰🤯👍🎉💯🔥❤️✅❌⚡🌈",
        "Multilingüe: Hoy almorcé phở y estaba おいしかった！",
    ],
    "边界场景": [
        "a" * 200,
        " " * 50 + "texto rodeado de espacios" + " " * 50,
        "prueba\ttabulador\tseparado\ttexto",
        "línea 1\nlínea 2\nlínea 3\nlínea 4\nlínea 5",
        "Esta es una cadena de texto muy larga para probar. " + "El sistema debe manejar correctamente cadenas extensas. " * 15,
        "",
        "   ",
        "aáeébíoóuú mezcla de vocales con y sin tilde",
        "EspañolEnglish中文日本語한국어العربية mezcla multilingüe",
        "ＡＢＣＤＥ１２３４５ caracteres de ancho completo",
        "①②③④⑤⑥⑦⑧⑨⑩ números en círculo",
        "㎡ ㎝ ㎞ ㎏ ℃ ℉ unidades especiales",
        "¡¡¡¡¡¿¿¿¿¿ signos invertidos repetidos",
        "espacioinseparable" + "abcdefghijklmnopqrstuvwxyz" * 10,
        "Tildes: si/sí, el/él, mas/más, tu/tú, se/sé, de/dé",
        "ñ Ñ ü Ü — caracteres exclusivos del español",
        "Emoji repetido: " + "😀" * 100,
        "Espacios especiales: normal no-break fino ancho",
        "\u200EMarca LTR y \u200Fmarca RTL mezcladas",
        "Números densos: 12345678901234567890.12345678901234567890",
        "Puntuación mixta: Prueba, this is a test.",
        "Saltos de línea mixtos\r\nWindows\nUnix\rMac antiguo",
        "HTML: <script>alert('XSS')</script><b>negrita</b>",
        "SQL injection: '; DROP TABLE users; --",
        "Ruta: C:\\Users\\Prueba\\Documentos\\informe.xlsx",
        "URL: https://ejemplo.com/búsqueda?término=prueba&página=1#resultados",
        "Sangría extrema:" + "\t" * 20 + "texto con sangría profunda",
        "Líneas vacías consecutivas:\n\n\n\n\nTexto tras 5 líneas vacías",
        "Diéresis y eñes: pingüino, vergüenza, Ñoño, piñata, cañón",
        "Abreviaturas: Sr., Sra., Ud., Uds., pág., n.º, 1.er, 2.º",
        "Signos de apertura y cierre: ¿Qué? ¡Hola! «cita» (paréntesis) [corchetes]",
    ],
    "专业术语": [
        "De conformidad con el artículo 1101 del Código Civil, quedan sujetos a la indemnización de daños y perjuicios los que incurrieren en dolo, negligencia o morosidad en el cumplimiento de sus obligaciones.",
        "El paciente acude a urgencias con dolor torácico opresivo irradiado al brazo izquierdo; el ECG muestra elevación del ST en derivaciones inferiores, compatible con IAMCEST.",
        "El sistema emplea una arquitectura de microservicios con un API Gateway para autenticación y limitación de tráfico; la comunicación entre servicios se realiza mediante gRPC.",
        "El fondo de comercio en el balance consolidado al cierre del ejercicio asciende a 128 millones de euros, lo que supone un incremento del 23,5 % respecto al mismo periodo del año anterior.",
        "Conforme a la Ley de Enjuiciamiento Civil, el demandado dispondrá de veinte días hábiles para contestar a la demanda a partir de la notificación de la misma.",
        "Informe anatomopatológico: carcinoma ductal infiltrante de mama izquierda, grado II. Inmunohistoquímica: RE(+), RP(+), HER2 (2+), FISH negativo.",
        "El modelo alcanza una precisión Top-1 del 87,3 % en el conjunto de validación de ImageNet, con una latencia de inferencia de 2,1 ms por imagen en GPU A100.",
        "Las acciones ordinarias del emisor fueron admitidas a cotización en el mercado continuo de la Bolsa de Madrid el 8 de mayo de 2026. Código ISIN: ESXXXXXXXXXX.",
        "El fondo podrá invertir en renta variable cotizada, deuda pública, bonos corporativos, instrumentos del mercado monetario y derivados financieros.",
        "RM cerebral con contraste: lesión ocupante de espacio de 3,2 × 2,8 × 2,5 cm en lóbulo temporal derecho con realce heterogéneo; diagnóstico diferencial con glioma de alto grado.",
        "En caso de que el deudor no cumpla el requerimiento de pago, el tribunal podrá decretar el embargo de bienes suficientes para cubrir la cantidad adeudada.",
        "La ronda de financiación ha sido liderada por un fondo de capital riesgo de primer nivel, con una valoración post-money de aproximadamente 3.500 millones de euros.",
        "La orquestación de contenedores se basa en un clúster de Kubernetes, con gestión del ciclo de vida mediante Helm Charts y observabilidad a través de Prometheus + Grafana.",
        "Este medicamento es de prescripción médica obligatoria y está contraindicado en pacientes con hipersensibilidad conocida a alguno de sus componentes. En pacientes con insuficiencia hepática o renal se requiere ajuste de dosis.",
        "La parte concedente otorga a la parte concesionaria el derecho exclusivo de distribución en el territorio del Reino de España por un periodo de tres años desde la entrada en vigor del contrato.",
        "Cotización a la Seguridad Social: tipo general 28,30 % (empresa 23,60 %, trabajador 4,70 %) sobre la base de cotización, con un tope máximo de 4.720,50 €/mes.",
        "La hemoglobina glicosilada (HbA1c) del paciente es del 9,2 % y la glucemia basal de 14,6 mmol/L, por lo que se recomienda iniciar terapia insulínica intensiva.",
        "El entrenamiento utilizó el optimizador AdamW con tasa de aprendizaje inicial de 3×10⁻⁴, programación de tipo cosine annealing, 100 épocas y tamaño de lote de 256.",
        "Los ingresos consolidados del ejercicio 2025 alcanzaron los 5.872 millones de euros (+18,6 % interanual); el beneficio neto atribuido fue de 643 millones de euros.",
        "El RTO del sistema es de 4 horas y el RPO de 1 hora, cumpliendo los requisitos del Plan de Continuidad de Negocio (BCP) de nivel 3.",
        "Suplico al Juzgado: 1.º Que condene al demandado a cesar en los actos de infracción de la marca registrada. 2.º Que condene al demandado a indemnizar con 500.000 euros.",
        "Prescripción: amoxicilina cápsulas 500 mg, 1 cada 8 horas, 7 días; ibuprofeno 300 mg retard, 1 cada 12 horas si dolor.",
        "El SoC se fabrica en proceso TSMC de 5 nm, integra 12.000 millones de transistores, frecuencia máxima de 3,5 GHz y TDP de 65 W.",
        "Cambio de política contable: la sociedad aplica desde el 1 de enero de 2026 la NIIF 15 «Ingresos procedentes de contratos con clientes», con efecto retroactivo completo.",
        "Configuración del pool de conexiones: máximo 200 conexiones, mínimo de conexiones en reposo 20, tiempo de espera de conexión 30 s.",
        "De acuerdo con el artículo 53 del Estatuto de los Trabajadores, el despido por causas objetivas requiere un preaviso de 15 días o, en su defecto, el abono de los salarios correspondientes.",
        "Postoperatorio día 3 tras sustitución valvular aórtica: constantes estables, débito del drenaje torácico en descenso; se prevé retirada del drenaje mañana.",
        "El sistema mantiene un throughput de 100k QPS con una latencia en el percentil 99 inferior a 200 ms.",
        "Esta operación constituye una adquisición significativa de activos sujeta a la aprobación de la Junta General de Accionistas y a la supervisión de la CNMV.",
        "Mecanismo de privacidad diferencial: se inyecta ruido de Laplace durante la agregación de datos, con un presupuesto de privacidad ε = 1,0 para prevenir la reidentificación.",
    ],
    "口语俚语": [
        "¡Madre mía! ¿Esto es en serio? No me lo puedo creer, tío.",
        "Jajajaja me estoy partiendo de risa, qué bueno.",
        "¿En serio? ¿Y yo soy el último en enterarme? Mola...",
        "¡Venga, vamos! ¡Que si llegamos tarde nos quedamos sin sitio!",
        "Estaba buenísimo, ¡madre mía! Tenemos que volver.",
        "Bah, eso no está bien, ¿no? Se han pasado un poco.",
        "Totalmente. Llevas toda la razón del mundo.",
        "Qué pereza... Hoy no tengo ganas de hacer nada de nada.",
        "¡Esto es una pasada! ¡Brutal, de verdad!",
        "Vale vale, ¡yo me encargo!",
        "Qué envidia me das... Yo también quiero irme de vacaciones.",
        "Pues... no sé, es complicado... Es un poco raro.",
        "Qué asco, ¡otra vez lloviendo!",
        "¿Vamos a comer algo? Me muero de hambre.",
        "¡Tío, eres un crack! ¿El primero del examen? ¡Fenómeno!",
        "¿Pero tú estás loco? ¿Quién hace eso?",
        "Lo hice así, sin más. Tampoco es para tanto.",
        "Perdona que te moleste, pero necesito pedirte otro favor...",
        "Relájate, ¿vale? No es el fin del mundo.",
        "Con esto basta. No hace falta más.",
        "¡Flipa! ¡Qué pasada! ¡Esto es increíble!",
        "Bueno, como quieras, me da igual.",
        "Anda ya, déjalo estar, ¿quieres?",
        "¡Cómo mola! ¡Quiero ir yo también!",
        "¡No te olvides, ¿eh?! ¡Es importante!",
        "Hecho, ¡me pongo con ello ahora mismo!",
        "Buf, qué difícil... Me va a explotar la cabeza.",
        "¡¡¡Aaah!!! ¡Mi grupo favorito viene a España!!! ¡Entradas ya!",
        "Pues... bueno... nada... da igual...",
        "Oye, ¿me echas una mano? Es urgente, porfa.",
        "¡Date prisa, que se acaba! ¡Últimas unidades!",
    ],
}
