LANG_NAME = "菲律宾语"
LANG_CODE = "fil-PH"

TEMPLATES = {
    "常规文案": [
        "Ayon sa PAGASA, inaasahang uulan sa Metro Manila ngayong hapon at gabi.",
        "Paunawa: Ang sistema ay pansamantalang hindi magagamit bukas mula 2:00 hanggang 6:00 ng umaga dahil sa maintenance.",
        "Ang MRT Line 3 ay nakakaranas ng pagkaantala dahil sa signal failure.",
        "Kasama sa bagong lunch set ang main course, salad, soup, at drinks sa espesyal na presyo.",
        "Inaabot ng homeowners association ang lahat ng residente tungkol sa bagong security system.",
        "Mga magulang: Ang parents' meeting ay sa susunod na Miyerkules, alas-2:30 ng hapon.",
        "Naglabas ang PAGASA ng Signal No. 2 para sa Visayas dahil sa bagyong papalapit.",
        "Bukas na muli ang library simula ngayon matapos ang dalawang linggong renovasyon.",
        "Ang dokumentaryong ito ay tungkol sa buhay-dagat sa Tubbataha Reef Natural Park.",
        "Malapit nang dumating ang tren sa Taft Avenue station. Maghanda na po ang mga bababa.",
        "Naihatid ng delivery rider ang order sa tamang oras kahit malakas ang ulan.",
        "Nagsagawa ang mga volunteer ng coastal cleanup sa Manila Bay noong weekend.",
        "May espesyal na exhibit ang National Museum tungkol sa ginto ng sinaunang Pilipinas.",
        "Tuwing Pista ng Itim na Nazareno, daan-daang libong deboto ang nagtitipon sa Quiapo.",
        "Ang Christmas party ng opisina ay sa December 23 sa isang restaurant sa BGC.",
        "Naglabas ang DepEd ng bagong guidelines para sa K-12 curriculum.",
        "Ang panaderya sa kanto ay nagbebenta ng mainit na pandesal na nauubos bago mag-alas-siyete ng umaga.",
        "Maaari nang kumuha ng PSA birth certificate online sa pamamagitan ng PSASerbilis.",
        "Ang bagong bike lane ay nag-uugnay sa Rizal Park at Intramuros.",
        "Sa panahon ng Holy Week, kailangan ng advance booking sa mga tourist spots.",
        "Noche Buena ngayon! Magtitipon-tipon ang buong pamilya para sa handa.",
        "Dumating na ang iyong package sa locker. I-claim mo gamit ang verification code.",
        "May bagong halal at vegetarian options na ang cafeteria ng school.",
        "Tumutugtog ang malumanay na musika sa waiting area — nakakarelax ang ambiance.",
        "Ang fire drill ay gagawin sa Biyernes, alas-10 ng umaga sa ground floor lobby.",
        "Namumulaklak na ang sampaguita sa bakuran ng kapitbahay — mabango ang buong kalye.",
        "Tag-init na ngayon pero parang summer pa rin ang init kahit October na.",
        "May buy-one-take-one promo ang bagong milk tea shop sa tapat — mahaba ang pila.",
        "Si Lolo ay gumigising ng maaga araw-araw para maglakad-lakad sa parke.",
        "Abiso: Magbabago ang oras ng dismissal ng mga estudyante simula sa susunod na linggo.",
        "Iginuhit ng guro ang mapa ng Pilipinas sa blackboard at pinahanap sa mga bata ang mga probinsya.",
    ],
    "长难句": [
        "Kahit na paulit-ulit nang naglalabas ang gobyerno ng mga hakbang para panatilihin ang katatagan ng presyo ng bilihin, patuloy pa rin ang pagtaas ng mga bilihin sa pamilihan, na lubhang nakakaapekto sa kabuhayan ng mga ordinaryong mamamayan.",
        "Kung hindi naganap ang krisis pinansyal noong panahong iyon, malamang na iba ang naging takbo ng reporma sa sistema ng pagbabangko sa Pilipinas.",
        "Ang desisyon ng korte ay hindi lamang para sa isang partikular na kaso kundi nagtatatag ng mahalagang precedente sa pagtatakda ng saklaw ng karapatan sa privacy ng personal na datos sa digital na panahon.",
        "Gaano man kasulong ang artificial intelligence sa larangan ng pagsasalin, ang tapat na pagsasalin ng mga kultural na nuance at estetikong halaga ng isang literaryong akda ay nananatiling malaking hamon.",
        "Ayon sa ulat ng Commission on Audit, ang ahensya ay nagbigay ng mga kontrata nang walang maayos na bidding process, na labag sa Government Procurement Reform Act.",
        "Ang Filipino bilang wikang pambansa ay nagsisilbing tulay sa mahigit 180 wika at diyalektong sinasalita sa buong kapuluan, at ang pagkakaiba-iba nito ay kayamanan, hindi hadlang.",
        "Ang pagtatangkang lutasin ang problema ng kahirapan sa kanayunan sa pamamagitan lamang ng financial incentives ay nagpapakita ng kakulangan sa pag-unawa sa mga ugat na sanhi ng migrasyon tungo sa kalunsuran.",
        "Iginiit ng abogado ng akusado na ang mga digital na ebidensya na inilahad ng prosecution ay nakuha nang hindi sumusunod sa tamang proseso ng batas, kaya't hindi ito dapat tanggapin bilang katibayan.",
        "Ang dahilan kung bakit nakaka-unsettle ang mga nobela ng manunulat na ito ay ang kanyang pagtangging magbigay ng moral na hatol sa kanyang mga karakter, na pumipigil sa mambabasa na umasa sa isang simpleng moral na konklusyon.",
        "Sa mga probinsyang nanganganib na mawalan ng populasyon, nagbibigay ang gobyerno ng subsidyo sa pabahay, edukasyon, at kalusugan para maakit ang mga bagong settler, ngunit mababa pa rin ang retention rate.",
        "Ang pag-aaral ng kasaysayan ng Pilipinas nang hindi isinasaalang-alang ang epekto ng kolonyalismo ay tulad ng pag-aaral ng isang punongkahoy habang binabalewala ang mga ugat nito.",
        "Ang pagtaas ng sea level dulot ng climate change ay nagbabanta sa mga komunidad sa baybayin, at ang tanong kung tutuparin ba ng mga industriyalisadong bansa ang kanilang pangako sa pagbawas ng emissions ay naging usaping pang-global na katarungan.",
        "Ang mga artifact na natuklasan sa site ay hindi lamang mga kagandahang sining kundi mga historikal na ebidensya na nagbibigay-liwanag sa mga sinaunang network ng kalakalan sa Southeast Asia.",
        "Kahit maabot ang kasunduan sa negosasyon, hindi maaaring ipagwalang-bahala ang posibilidad na magkaroon ng hindi pagkakaunawaan sa yugto ng implementasyon dahil sa magkaibang interpretasyon ng mga partido.",
        "Hangga't hindi binibigyan ng sapat na autonomiya ang mga guro sa loob ng silid-aralan, anumang reporma sa edukasyon, gaano man kaganda ang disenyo nito, ay mananatiling walang epekto.",
        "Ang dahilan ng kontrobersya sa academic community ay hindi ang methodology kundi ang mismong konklusyon, na direktang sumasalungat sa nananaig na teorya sa larangan.",
        "Iginiit ng abogado ng plaintiff na ang electronic evidence na inilahad ng defendant ay may depekto sa chain of custody, kaya't walang legal na bisa.",
        "May kasabihan na mas mabuting ituro ang pangingisda kaysa magbigay ng isda, ngunit ano ang silbi ng pagtuturo ng pangingisda kung wala namang pambili ng lambat?",
        "Sa mundong ang global supply chain ay magkakaugnay nang masikip, ang pagkagambala sa isang mahalagang link ay maaaring magdulot ng chain reaction na lampas sa anumang hula.",
        "Kung hindi makumpleto ng buyer ang inspeksyon sa loob ng takdang panahon sa kontrata, ituturing na tinanggap niya nang tahimik na ang produkto ay nakatutugon sa mga napagkasunduang quality standards.",
        "Lumalaki ang ebidensyang nagpapakita na ang matagalang pagkakalantad sa mababang dosis ng environmental pollutants ay maaaring makapinsala sa neurological development ng mga bata, at ang mga epekto ay lumilitaw lamang sa adolescence.",
        "Ang tunay na galing ng direktor na ito ay nasa kakayahan niyang pukawin ang empatiya ng manonood para sa bawat karakter nang hindi sinasabi kung sino ang dapat kaawaan.",
        "Kahit ang blockchain technology ay maaaring solusyunan ang isyu ng tiwala sa cross-border payments sa teorya, ang pagkakaiba ng regulatory framework sa iba't ibang bansa ang nananatiling pangunahing hadlang sa mass adoption.",
        "Malubha ang deteriorasyon ng mga natuklasang manuskrito sa excavation, ngunit sa pamamagitan ng infrared imaging, natuklasan ang ilang sinaunang teksto na hindi pa natutuklasan dati.",
        "Ang disenyo ng tulay na ito ay dapat kayanin ang higit 100,000 na sasakyan bawat araw habang tinitiyak ang structural safety sa lindol na magnitude 7 o higit pa.",
        "Mas tama ang tingnan ang kanyang pagbibitiw bilang tahimik na protesta laban sa paulit-ulit na kompromiso ng pamunuan sa core values, kaysa personal na desisyon lamang.",
        "Ang kawalan ng epektibong mekanismo ng koordinasyon sa pagitan ng mga ahensya ng gobyerno ay nagreresulta sa magkakahiwalay na tugon sa emergency situations, na nauuwi sa pagkawala ng tamang timing ng aksyon.",
        "Kahit ang pinaka-optimistikong economist ay kinikilala na sa gitna ng tumitinding trade tensions, lubhang bumaba ang growth prospects ng mga export-oriented na ekonomiya.",
        "Ang mukhang simpleng away sa homeowners association ay naglalaman pala ng kumplikadong irregularities kabilang ang illegal pre-selling at misuse ng association funds.",
        "Ang digital transformation sa edukasyon ay nangangailangan ng sabay-sabay na pagtupad sa tatlong aspeto: teknolohikal na imprastraktura, digital literacy ng mga guro, at information security.",
        "Habang lumalaki ang pag-asa ng lipunan sa artificial intelligence sa paggawa ng desisyon, lalong tumitindi ang pangangailangan para sa talakayan tungkol sa algorithmic transparency at accountability.",
    ],
    "短文本": [
        "Kumpirmahin", "Kanselahin", "Ipadala", "Bumalik", "Susunod",
        "I-save ang draft", "Bilhin ngayon", "Idagdag sa cart", "Tingnan ang detalye", "Sold out",
        "Naglo-load", "I-refresh", "Maghanap", "Mga setting", "Aking account",
        "Mga notification", "Mag-log out", "Palitan ang password", "I-verify ang phone", "I-verify ang identity",
        "Sinusuri", "Na-approve", "Tinanggihan", "Pending", "Kumpleto",
        "Walang data", "Network error", "Subukan muli", "Tagumpay", "Input error",
        "Piliin lahat", "Tanggalin", "I-edit", "Kopyahin ang link", "I-share",
        "Mga paborito", "Like", "I-report", "I-block", "I-follow",
        "Home", "Explore", "Cart", "Profile", "Tulong",
    ],
    "数字日期": [
        "Huwebes, Mayo 14, 2026",
        "Kabuuang halaga: ₱72,850.00",
        "Telepono: (02) 8123-4567",
        "Mobile: +63 917 123 4567",
        "PhilSys ID: 1234-5678-9012-3456",
        "Tracking number: PH1234567890123",
        "Oras ng trabaho: Lunes–Biyernes, 08:00–17:00",
        "Meeting: Lunes, Hunyo 1, 2026, 14:00–16:30",
        "Temperatura: 24°C – 38°C",
        "Capital: ₱5,000,000.00 (limang milyong piso)",
        "Plate number: ABC 1234",
        "ZIP code: 1000",
        "Contract no.: HT-2026-05-0378",
        "Bank account: 1234-5678-90 — BDO Unibank",
        "Invoice amount: ₱86,400.00 (VAT inclusive)",
        "Coordinates: 14°35′00″ N, 120°58′00″ E",
        "Area: 128.56 sq.m. (floor area)",
        "Flight PR123, departure 08:45, arrival 11:20",
        "Password: 8–16 characters, with uppercase, lowercase, and numbers",
        "Version: v3.2.1-beta (build 20260514)",
        "Score: 3-2 (overtime)",
        "Interest rate: 4.35% per annum (0.3625% monthly)",
        "Elevation: 4,718 meters above sea level",
        "Expiry date: March 15, 2027",
        "Stock code: SM (SM Investments Corporation)",
        "IP address: 192.168.1.100:8080",
        "TIN: 123-456-789-000",
        "Q3 revenue: +12.7% year-on-year",
        "Packaging: 500 ml × 24 bottles/case",
        "Delivery radius: 5 km, estimated time 30–45 minutes",
    ],
    "特殊字符": [
        "【MAHALAGANG PAUNAWA】Schedule ng holiday para sa 2026",
        "«Noli Me Tangere» — ang obra maestra ni Jose Rizal",
        "Babala: Bawal ang pagpasok ng pagkain at inumin sa library!!!",
        "Presyo: ₱298 → ₱198 (limited time offer)",
        "Rating: ★★★★☆ (4.5/5.0)",
        "Ruta: Manila → Clark → Baguio → Vigan → Laoag",
        "Supported OS: Windows / macOS / Linux (64-bit)",
        "Formula: E = mc², kung saan c ≈ 3×10⁸ m/s",
        "Note: Prices are VAT-exclusive (±5% variation)",
        "Contact: ☎ (02) 8123-4567 / ✉ info@example.ph / 📍 Makati City",
        "Progress: ████████░░ 80%",
        "♻️ Pakilagay ang recyclable waste sa tamang basurahan ♻️",
        "⚠️ Panganib: High voltage 380V — Bawal pumasok! ⚠️",
        "— Jose Rizal, Noli Me Tangere: «Huwag mo akong salingin»",
        "【NAAYOS NA ✓】Server error 500 fixed na @lahat",
        "Bawal na characters sa filename: \\ / : * ? \" < > |",
        "Math: ∑(i=1→n) aᵢ × bᵢ = a·b",
        "Chemistry: 2H₂ + O₂ → 2H₂O (exothermic reaction)",
        "© 2026 Sample Company Inc. All rights reserved.",
        "CO₂ emission: approx. 2.3 kg/km²·year⁻¹",
        "Password strength: mahina ☠️ / katamtaman ⚡ / malakas 💪",
        "【Forward】@Juan @Maria Tingnan niyo ito! 🔥🔥🔥",
        "Choices: (a) Tama (b) Mali (c) Hindi sigurado (d) Wala sa mga nabanggit",
        "1st 🥇: ₱100,000 | 2nd 🥈: ₱50,000 | 3rd 🥉: ₱20,000",
        "═══════════════════════════════════════════",
        "Filipino characters: Ñ ñ Ng ng — mga espesyal na letra",
        "#byahe #kainan #arawAraw #vlog",
        "✓ Tapos  × Hindi pa  ○ Ginagawa  △ Naghihintay",
        "Emojis: 😀😂🤔😭🥰🤯👍🎉💯🔥❤️✅❌⚡🌈",
        "Multilingual: Kumain ako ng phở kanina, おいしかった！",
    ],
    "边界场景": [
        "a" * 200,
        " " * 50 + "text na napapaligiran ng spaces" + " " * 50,
        "test\ttab\tseparated\ttext",
        "linya 1\nlinya 2\nlinya 3\nlinya 4\nlinya 5",
        "Ito ay napakahaba na test string. " + "Kailangan ng system na mahandle ang mahahabang string nang tama. " * 15,
        "",
        "   ",
        "aAbBcCdDeE English-Filipino mixed text test",
        "FilipinoEnglish中文日本語한국어العربية multilingual mix",
        "ＡＢＣＤＥ１２３４５ fullwidth characters",
        "①②③④⑤⑥⑦⑧⑨⑩ circled numbers",
        "㎡ ㎝ ㎞ ㎏ ℃ ℉ special units",
        "Repeated punctuation!!!!!?????.....",
        "walangSpaces" + "abcdefghijklmnopqrstuvwxyz" * 10,
        "Ñ ñ Ng ng — espesyal na letra sa Filipino",
        "Taglish: Ang ganda naman ng weather today, 'di ba?",
        "Repeated emoji: " + "😀" * 100,
        "Special spaces: normal non-breaking thin wide",
        "\u200ELTR mark at \u200FRTL mark na magkahalo",
        "Dense numbers: 12345678901234567890.12345678901234567890",
        "Mixed punctuation: Subukan, this is a test.",
        "Mixed line breaks\r\nWindows\nUnix\rOld Mac",
        "HTML: <script>alert('XSS')</script><b>bold</b>",
        "SQL injection: '; DROP TABLE users; --",
        "File path: C:\\Users\\Test\\Documents\\report.xlsx",
        "URL: https://example.com/hanap?keyword=test&page=1#results",
        "Extreme indent:" + "\t" * 20 + "deeply indented text",
        "Consecutive blank lines:\n\n\n\n\nText after 5 blank lines",
        "Baybayin script: ᜊᜌ᜔ᜊᜌᜒᜈ᜔ — ancient Filipino writing",
        "Slang abbreviations: 'di, 'yung, 'wag, 'to, 'yan, 'no",
        "Code-switching: Nag-meeting kami about the new project timeline kahapon.",
    ],
    "专业术语": [
        "Alinsunod sa Artikulo 1170 ng Civil Code, ang mga may utang na hindi tumutupad ng kanilang obligasyon ay mananagot sa mga pinsala.",
        "Ang pasyente ay na-admit dahil sa chest pain na nag-radiate sa kaliwang braso; ang ECG ay nagpakita ng ST elevation — impression: acute STEMI.",
        "Ang sistema ay gumagamit ng microservices architecture na may API Gateway para sa authentication at rate limiting; ang communication sa pagitan ng services ay ginagawa sa pamamagitan ng gRPC.",
        "Ang goodwill sa consolidated balance sheet sa katapusan ng reporting period ay ₱12.8 bilyon, tumaas ng 23.5% kumpara sa parehong panahon noong nakaraang taon.",
        "Alinsunod sa Rules of Court, ang defendant ay may 15 araw para mag-file ng answer matapos matanggap ang summons at kopya ng complaint.",
        "Histopathology report: invasive ductal carcinoma ng kaliwang breast, grade II. Immunohistochemistry: ER(+), PR(+), HER2 (2+), FISH negative.",
        "Ang modelo ay nakamit ang Top-1 accuracy na 87.3% sa ImageNet validation set, na may inference latency na 2.1 ms per image sa A100 GPU.",
        "Ang common shares ng issuer ay na-list sa Philippine Stock Exchange noong Mayo 8, 2026. Ticker symbol: XXXX.",
        "Ang pondo ay maaaring mag-invest sa listed equities, government securities, corporate bonds, money market instruments, at derivatives.",
        "Brain MRI with contrast: 3.2×2.8×2.5 cm heterogeneously enhancing mass sa right temporal lobe.",
        "Kung hindi sumunod ang may utang sa writ of execution, maaaring mag-utos ang korte ng garnishment o attachment ng kanyang mga ari-arian.",
        "Ang Series B funding round ay pinangunahan ng isang nangungunang venture capital fund, na may post-money valuation na humigit-kumulang $350 milyon.",
        "Ang container orchestration ay ginagawa sa pamamagitan ng Kubernetes cluster, na may Helm Charts para sa application lifecycle management at Prometheus + Grafana para sa observability.",
        "Ang gamot na ito ay prescription drug at contraindicated sa mga pasyenteng may hypersensitivity sa kahit anong component nito. Kailangan ng dose adjustment sa mga may liver o kidney impairment.",
        "Ibinibigay ng Party A sa Party B ang exclusive distribution rights sa buong Pilipinas sa loob ng tatlong taon mula sa effectivity ng kontrata.",
        "SSS contribution: employer 9.5%, employee 4.5% ng monthly salary credit, na may maximum coverage na ₱30,000.",
        "Ang HbA1c ng pasyente ay 9.2%, fasting blood sugar ay 14.6 mmol/L — recommended ang pagsisimula ng intensive insulin therapy.",
        "Ginamit ang AdamW optimizer na may initial learning rate na 3×10⁻⁴, cosine annealing schedule, 100 epochs, at batch size na 256.",
        "Ang consolidated revenue para sa fiscal year 2025 ay ₱587.2 bilyon (+18.6% YoY); net income attributable to parent company ay ₱64.3 bilyon.",
        "Ang RTO ng sistema ay 4 na oras at RPO ay 1 oras, na nakakatugon sa BCP Level 3 requirements.",
        "Relief sought: 1. Order the defendant to cease trademark infringement. 2. Order the defendant to pay ₱50 million in damages.",
        "Prescription: Amoxicillin 500 mg capsule, 3× daily after meals for 7 days; Ibuprofen 300 mg extended-release, 2× daily for pain.",
        "Ang SoC ay manufactured sa TSMC 5nm process, may 12 bilyong transistors, max clock 3.5 GHz, TDP 65W.",
        "Change in accounting policy: Inumpisahan ng kompanya ang paggamit ng PFRS 15 simula Enero 1, 2026, na may full retrospective application.",
        "DB connection pool config: max connections 200, min idle 20, connection timeout 30 seconds.",
        "Alinsunod sa Labor Code, ang employer na mag-terminate ng empleado nang walang just o authorized cause ay liable sa illegal dismissal at reinstatement with full backwages.",
        "Post-op day 3 matapos ang aortic valve replacement: vital signs stable, drain output decreasing; planned chest drain removal bukas.",
        "Ang sistema ay nagma-maintain ng 100k QPS throughput na may p99 latency ≤ 200 ms.",
        "Ang transaksyon na ito ay isang material related-party transaction na nangangailangan ng approval ng board at majority ng minority shareholders.",
        "Differential privacy mechanism: Laplacian noise injection during data aggregation, privacy budget ε = 1.0.",
    ],
    "口语俚语": [
        "Talaga?! Grabe naman! Hindi ako makapaniwala!",
        "Hahahaha! Ang funny! Di ko kaya!",
        "Ha? Ako na lang pala ang hindi nakakaalam? Naman oh...",
        "Tara na! Bilis! Pag late tayo wala nang pwesto!",
        "Sobrang sarap nung food! Balik tayo dun ulit!",
        "Nako, hindi na yata tama yun. Medyo OA na.",
        "Oo nga. Tama ka dyan.",
        "Tamad na tamad ako ngayon... Ayoko na gumawa ng kahit ano.",
        "Ang galing!!! Epic talaga!!! Legendary!!!",
        "Sige sige, ako na bahala!",
        "Nakakainggit naman... Gusto ko rin mag-travel!",
        "Parang... hindi ko alam eh... medyo confusing...",
        "Hay naku, umuulan na naman!",
        "Kain tayo? Gutom na gutom na ako eh.",
        "Grabe ka! Number one?! Genius ka ba?!",
        "Loko-loko ka ba? Sino ang gagawa nun?!",
        "Ginawa ko lang. Walang special.",
        "Sorry ha, may gusto na naman akong i-ask...",
        "Chill ka lang. Hindi naman yun big deal.",
        "Tama na yan. Hindi na kailangan ng dagdag.",
        "Wow, ang ganda! Sobrang nice!",
        "Ewan, bahala ka. Walang pakialam.",
        "Tama na, please. Nakakapagod na.",
        "Gusto ko rin pumunta! Sama ako!",
        "Huwag mong kakalimutan ha! Promise yan!",
        "G na! Gawin ko na!",
        "Ang hirap naman nito... Sumasakit ulo ko.",
        "OMG!!! Pupunta ang fave ko sa Pilipinas!!! Bilhin na ang tickets!!!",
        "Uhm... sige... okay... fine...",
        "Kuya/Ate, tulungan mo naman ako please! Urgent eh!",
        "Dali! Mauubos na! Limited stocks lang!",
    ],
}
