LANG_NAME = "法语"
LANG_CODE = "fr-FR"

TEMPLATES = {
    "常规文案": [
        "Les prévisions météo annoncent de la pluie sur l'Île-de-France pour cet après-midi.",
        "Veuillez noter que le système sera temporairement indisponible demain de 2 h à 6 h pour maintenance.",
        "La ligne 4 du métro est perturbée en raison d'un incident technique entre Montparnasse et Barbès.",
        "Le nouveau menu du déjeuner comprend un plat principal, une salade, un dessert et une boisson.",
        "Le syndic de copropriété informe les résidents de l'installation de nouvelles caméras de surveillance.",
        "Chers parents, la réunion parents-professeurs aura lieu mercredi prochain à 14 h 30.",
        "Météo-France a placé douze départements en vigilance orange pour orages violents.",
        "La bibliothèque universitaire reprend ses horaires d'ouverture habituels dès aujourd'hui.",
        "Ce documentaire retrace la transhumance des bergers dans les Pyrénées ariégeoises.",
        "Le TGV Paris-Lyon circulera avec un retard d'environ trente minutes en raison de travaux sur la voie.",
        "Le livreur a assuré la livraison dans les temps malgré la pluie battante.",
        "Des bénévoles de la Croix-Rouge ont distribué des repas chauds aux sans-abri ce week-end.",
        "Le musée du Louvre présente une exposition exceptionnelle consacrée à l'art impressionniste.",
        "À l'approche des fêtes de fin d'année, les gares parisiennes connaissent une affluence record.",
        "Le dîner d'entreprise de fin d'année se tiendra le 20 décembre au restaurant Le Meurice.",
        "Le ministère de l'Éducation nationale a publié une circulaire sur la réforme du baccalauréat.",
        "La boulangerie du quartier a reçu le prix de la meilleure baguette de Paris cette année.",
        "Les citoyens peuvent désormais renouveler leur carte d'identité en ligne via le site de l'ANTS.",
        "La nouvelle piste cyclable relie la gare au parc des Buttes-Chaumont.",
        "Pendant le pont du 14 Juillet, la plupart des musées nationaux seront ouverts gratuitement.",
        "Ce soir, c'est la Fête de la musique : des concerts gratuits un peu partout dans la ville.",
        "Votre colis est arrivé au point relais. Veuillez le retirer sous cinq jours ouvrés.",
        "La cantine scolaire propose désormais un menu végétarien chaque jour de la semaine.",
        "Dans la salle d'attente, une musique d'ambiance douce accompagne les patients.",
        "Un exercice d'évacuation incendie est prévu vendredi à 10 h dans le hall principal.",
        "Le voisin a planté un lilas dans son jardin ; le parfum embaume tout le quartier.",
        "On est déjà en automne, mais les températures restent anormalement élevées pour la saison.",
        "La nouvelle crêperie bretonne fait un malheur : il faut faire la queue pour y entrer.",
        "Grand-père se lève chaque matin à six heures pour aller marcher le long du canal.",
        "L'école maternelle informe les familles d'un changement d'horaires à compter de lundi prochain.",
        "La maîtresse a dessiné une carte de France au tableau et demandé aux élèves de situer les régions.",
    ],
    "长难句": [
        "Bien que le rapport de la Cour des comptes ait mis en lumière des irrégularités flagrantes dans la gestion des fonds publics, aucune poursuite judiciaire n'a été engagée à ce jour.",
        "Si le gouvernement n'avait pas décrété l'état d'urgence sanitaire au printemps dernier, le système hospitalier aurait probablement été submergé en l'espace de quelques semaines.",
        "Force est de constater que la réforme du code du travail, loin de simplifier les relations entre employeurs et salariés, a engendré une complexité administrative supplémentaire que personne n'avait anticipée.",
        "Le terroir bourguignon, dont la renommée dépasse largement les frontières de l'Hexagone, repose sur un savoir-faire viticole transmis de génération en génération depuis l'époque monastique.",
        "L'accusé a fait valoir devant la cour d'assises que les aveux obtenus lors de sa garde à vue l'avaient été sous la contrainte, ce qui, selon la jurisprudence de la CEDH, les rendrait irrecevables.",
        "À mesure que l'intelligence artificielle s'immisce dans les processus décisionnels des entreprises, la question de la responsabilité juridique en cas d'erreur algorithmique se pose avec une acuité croissante.",
        "Il n'est pas exagéré de dire que la politique d'aménagement du territoire menée depuis les années soixante-dix a contribué à creuser le fossé entre les métropoles dynamiques et les zones rurales en déclin.",
        "Le conservateur du musée a insisté pour que les œuvres restaurées soient exposées dans des conditions hygrométriques rigoureusement contrôlées, sous peine de compromettre irréversiblement l'intégrité des pigments.",
        "Quand bien même l'on parviendrait à réduire les émissions de gaz à effet de serre de moitié d'ici 2035, les climatologues estiment que certains effets du réchauffement seraient déjà irréversibles.",
        "Ce n'est qu'après avoir épuisé toutes les voies de recours internes que le requérant pourra saisir la Cour européenne des droits de l'homme, conformément au principe de subsidiarité.",
        "Les fouilles archéologiques menées sur le site de l'ancienne abbaye ont révélé un scriptorium carolingien dont l'existence n'était jusqu'alors attestée que par une unique mention dans un cartulaire du XIe siècle.",
        "Autant la première partie du discours présidentiel a été saluée pour sa lucidité sur l'état des finances publiques, autant la seconde a été critiquée pour son manque de propositions concrètes.",
        "Le paradoxe veut que ce soient précisément les mécanismes de protection sociale, conçus pour amortir les chocs économiques, qui se retrouvent les premiers menacés en période d'austérité budgétaire.",
        "Toute clause contractuelle qui aurait pour effet de priver le consommateur de son droit de rétractation dans le délai légal de quatorze jours sera réputée non écrite et inopposable.",
        "Il serait intellectuellement malhonnête d'évaluer les résultats de l'intervention sans reconnaître que les conditions de départ dans le groupe traité différaient sensiblement de celles du groupe témoin.",
        "La notion selon laquelle croissance économique et durabilité environnementale seraient intrinsèquement incompatibles est de plus en plus remise en question par les partisans de l'économie circulaire.",
        "C'est précisément parce que le cadre réglementaire a été conçu pour des industries traditionnelles qu'il peine à s'adapter à la nature décentralisée des instruments financiers basés sur la blockchain.",
        "Le manuscrit, qui avait dormi pendant plus d'un siècle dans les archives de l'université, s'est révélé contenir une correspondance inédite entre deux des figures les plus influentes des Lumières.",
        "En confondant conformité procédurale et justice substantielle, le cadre réglementaire crée involontairement des incitations perverses pour les organisations à privilégier le formalisme au détriment de la véritable atténuation des risques.",
        "Le philosophe soutient que nos obligations morales envers les générations futures ne peuvent être fondées sur la réciprocité, puisque ceux qui n'existent pas encore ne peuvent ni nous aider ni nous demander des comptes.",
        "Nonobstant l'abondante jurisprudence de la CEDH en matière de droit à la vie privée, les États membres conservent une large marge d'appréciation pour concilier ce droit avec les impératifs d'intérêt public.",
        "L'orchestre, loin de se conformer servilement aux pratiques d'interprétation historiquement informées, a apporté à cette symphonie une sensibilité résolument contemporaine qui a divisé les critiques mais captivé le public.",
        "Le rapport de l'auditeur a révélé non seulement que le processus de passation de marchés n'avait pas respecté la réglementation applicable, mais que la direction avait activement cherché à dissimuler les irrégularités.",
        "Ce que les critiques ne parviennent pas à saisir, c'est que la structure narrative délibérément fragmentée du roman reflète la désintégration identitaire du protagoniste — un choix formel thématiquement indispensable.",
        "Le prémisse même sur lequel repose le modèle économique — à savoir que les agents rationnels disposent d'une information parfaite et agissent uniquement pour maximiser leur utilité — a été si profondément discrédité par l'économie comportementale que son usage continu confine à la négligence intellectuelle.",
        "Au moment où l'enquête a achevé ses auditions, il était devenu manifeste que les défaillances institutionnelles n'étaient pas le fruit d'une incompétence individuelle mais d'une culture de déférence profondément enracinée.",
        "Dans la mesure où les obligations conventionnelles sont concernées, les États signataires se sont engagés à garantir qu'aucune personne relevant de leur juridiction ne sera soumise au refoulement.",
        "Le paradoxe au cœur de la gouvernance démocratique est que les institutions conçues pour protéger les droits des minorités doivent elles-mêmes tirer leur légitimité des processus majoritaires qu'elles cherchent à encadrer.",
        "Encore faudrait-il que les pouvoirs publics prennent la mesure de l'ampleur du phénomène avant de proposer des solutions qui, en l'état, apparaissent largement insuffisantes au regard des enjeux.",
        "La crise du logement en Île-de-France résulte d'un enchevêtrement de facteurs structurels — spéculation foncière, insuffisance de l'offre, normes urbanistiques contraignantes — que des mesures ponctuelles ne sauraient résoudre.",
    ],
    "短文本": [
        "Valider", "Annuler", "Envoyer", "Retour", "Suivant",
        "Enregistrer le brouillon", "Acheter", "Ajouter au panier", "Voir les détails", "Épuisé",
        "Chargement…", "Actualiser", "Rechercher", "Paramètres", "Mon compte",
        "Notifications", "Se déconnecter", "Modifier le mot de passe", "Vérifier le téléphone", "Vérification d'identité",
        "En cours d'examen", "Approuvé", "Rejeté", "En attente", "Terminé",
        "Aucun résultat", "Erreur réseau", "Veuillez réessayer", "Succès", "Saisie invalide",
        "Tout sélectionner", "Supprimer", "Modifier", "Copier le lien", "Partager",
        "Favoris", "J'aime", "Signaler", "Bloquer", "Suivre",
        "Accueil", "Explorer", "Panier", "Profil", "Aide",
    ],
    "数字日期": [
        "14 mai 2026",
        "Montant de la commande : 1 298,50 €",
        "Téléphone : 01 23 45 67 89",
        "Portable : 06 12 34 56 78",
        "Numéro de sécurité sociale : 1 90 03 75 123 456 78",
        "Numéro de suivi : LA123456789FR",
        "Horaires d'ouverture : lun.–ven. 9 h 00–17 h 30",
        "Réunion : lundi 1er juin 2026, de 14 h 00 à 16 h 30",
        "Température : de −3 °C à 28 °C",
        "Capital social : 5 000 000 € (cinq millions d'euros)",
        "Immatriculation : AA-123-BB",
        "Code postal : 75008",
        "Référence contrat : HT-2026-05-0378",
        "IBAN : FR76 3000 4000 0500 0012 3456 789",
        "Montant de la facture : 86 400,00 € TTC",
        "Coordonnées : 48°51′24″ N, 2°21′03″ E",
        "Surface : 128,56 m² (surface habitable)",
        "Vol AF1234, départ 08 h 45, arrivée 11 h 20",
        "Mot de passe : 8 à 16 caractères, majuscules, minuscules et chiffres obligatoires",
        "Version 3.2.1-bêta (build 20260514)",
        "Score : 3–2 (après prolongation)",
        "Taux d'intérêt : 4,35 % par an",
        "Altitude : 4 718 mètres",
        "À consommer avant le 15/03/2027",
        "Code ISIN : FR0000120271",
        "Adresse IP : 192.168.1.100:8080",
        "SIREN : 123 456 789",
        "Chiffre d'affaires T3 : +12,7 % en glissement annuel",
        "Conditionnement : 500 ml × 24 bouteilles",
        "Zone de livraison : rayon de 5 km, délai estimé 30–45 min",
    ],
    "特殊字符": [
        "【AVIS IMPORTANT】Calendrier des jours fériés 2026",
        "« Les Misérables » — chef-d'œuvre de la littérature française",
        "Rappel : interdiction de manger ou de boire dans la salle !!!",
        "Prix : de 299 € → à 199 € (offre limitée)",
        "Note : ★★★★☆ (4,5/5,0)",
        "Itinéraire : Paris → Lyon → Marseille → Nice → Monaco",
        "OS pris en charge : Windows / macOS / Linux (64 bits)",
        "Formule : E = mc², où c ≈ 3 × 10⁸ m/s",
        "N.B. : prix hors taxes (± 5 % de variation)",
        "Contact : ☎ 01 23 45 67 89 / ✉ info@exemple.fr / 📍 Paris 8e",
        "Progression : ████████░░ 80 %",
        "♻️ Merci de trier vos déchets recyclables ♻️",
        "⚠️ Attention : haute tension 380 V — accès interdit ! ⚠️",
        "— Victor Hugo, « Les Contemplations » : « Demain, dès l'aube… »",
        "【RÉSOLU ✓】Erreur serveur 500 corrigée @tous",
        "Caractères interdits dans les noms de fichier : \\ / : * ? \" < > |",
        "Maths : ∑(i=1→n) aᵢ × bᵢ = a·b",
        "Chimie : 2H₂ + O₂ → 2H₂O (réaction exothermique)",
        "© 2026 Société Exemple SAS. Tous droits réservés.",
        "Émissions de CO₂ : environ 2,3 kg/km²·an⁻¹",
        "Force du mot de passe : faible ☠️ / moyen ⚡ / fort 💪",
        "【Transféré】@Jean @Marie regardez ça ! 🔥🔥🔥",
        "Choix : (A) Vrai  (B) Faux  (C) Incertain  (D) Aucune réponse",
        "1er 🥇 : 10 000 € | 2e 🥈 : 5 000 € | 3e 🥉 : 2 000 €",
        "═══════════════════════════════════════════",
        "Ligatures : œuf, cœur, bœuf — æsthétique (rare)",
        "#voyage #gastronomie #lifestyle #vlog",
        "✓ Fait  × Non fait  ○ En cours  △ En attente",
        "Émojis : 😀😂🤔😭🥰🤯👍🎉💯🔥❤️✅❌⚡🌈",
        "Multilingue : J'ai mangé des おにぎり, 맛있었어요 !",
    ],
    "边界场景": [
        "a" * 200,
        " " * 50 + "texte entouré d'espaces" + " " * 50,
        "test\ttabulation\tséparée",
        "première ligne\ndeuxième ligne\ntroisième ligne\nquatrième\ncinquième",
        "Ceci est un texte extrêmement long " + "destiné à tester la gestion des chaînes longues " * 15 + "fin.",
        "",
        "   ",
        "aàbéçdêeë mélange accent-ASCII",
        "FrançaisEnglish中文한국어日本語العربية multilingue",
        "Ligatures : œ æ ﬁ ﬂ ﬀ ﬃ ﬄ",
        "ÀÂÆÇÉÈÊËÏÎÔŒÙÛÜŸ majuscules accentuées",
        "àâæçéèêëïîôœùûüÿ minuscules accentuées",
        "ＡＢＣＤＥ１２３４５ caractères pleine chasse",
        "①②③④⑤⑥⑦⑧⑨⑩ chiffres cerclés",
        "㎡ ㎝ ㎞ ㎏ ℃ ℉ unités spéciales",
        "Ponctuation multiple !!!!!?????.....",
        "sansespaceanglais" + "abcdefghijklmnopqrstuvwxyz" * 10,
        'Guillemets : « français » vs "anglais" vs „allemand"',
        "Tirets : trait d'union - tiret cadratin — tiret demi-cadratin –",
        "Émojis répétés : " + "😀" * 100,
        "Espaces spéciaux : normal insécable fine",
        "\u200EMarque LTR et \u200Fmarque RTL mélangées",
        "Chiffres denses : 12345678901234567890,12345678901234567890",
        "Mélange ponctuation : test, this is a test.",
        "Retours à la ligne\r\nWindows\nUnix\rancien Mac",
        "HTML : <script>alert('XSS')</script><b>gras</b>",
        "Injection SQL : '; DROP TABLE users; --",
        "Chemin : C:\\Utilisateurs\\Test\\Documents\\rapport.xlsx",
        "URL : https://exemple.fr/recherche?q=test&page=1#résultats",
        "Indentation extrême :" + "\t" * 20 + "texte très indenté",
        "Lignes vides multiples :\n\n\n\n\nTexte après 5 lignes vides",
    ],
    "专业术语": [
        "Conformément à l'article 1231-1 du Code civil, le débiteur est condamné, s'il y a lieu, au paiement de dommages et intérêts soit à raison de l'inexécution de l'obligation, soit à raison du retard dans l'exécution.",
        "Le patient se présente avec une douleur thoracique rétrosternale irradiant vers l'épaule gauche ; l'ECG montre un sus-décalage du segment ST — diagnostic provisoire : SCA ST+.",
        "La plateforme repose sur une architecture en microservices avec une passerelle API assurant l'authentification et la limitation de débit ; la communication inter-services utilise gRPC sur mTLS.",
        "À la date de clôture, le goodwill inscrit au bilan consolidé s'élève à 128 millions d'euros, en hausse de 23,5 % par rapport à l'exercice précédent.",
        "En application de l'article 56 du Code de procédure civile, l'assignation doit contenir, à peine de nullité, les mentions prescrites par les textes.",
        "Compte rendu anatomopathologique : sein gauche — carcinome canalaire infiltrant, grade II ; IHC : RE+, RP+, HER2 2+ (FISH négatif).",
        "Le modèle atteint une précision Top-1 de 87,3 % sur le jeu de validation ImageNet, avec une latence d'inférence de 2,1 ms par image sur GPU A100.",
        "Les actions de l'émetteur ont été admises aux négociations sur Euronext Paris le 8 mai 2026, sous le code mnémonique XYZ.",
        "Le fonds peut investir en valeurs mobilières, instruments du marché monétaire, parts d'OPCVM, dépôts et instruments financiers dérivés.",
        "IRM cérébrale avec injection de gadolinium : lésion tumorale de 3,2 × 2,8 × 2,5 cm dans le lobe temporal droit, rehaussement hétérogène.",
        "Le juge de l'exécution a ordonné la saisie-attribution des comptes bancaires du débiteur défaillant.",
        "Le tour de table de série B a été mené par un fonds d'investissement de premier plan, pour une valorisation post-money d'environ 350 millions d'euros.",
        "L'orchestration des conteneurs s'appuie sur un cluster Kubernetes géré via Helm Charts ; l'observabilité est assurée par Prometheus et Grafana.",
        "Ce médicament est soumis à prescription médicale obligatoire ; il est contre-indiqué chez les patients présentant une hypersensibilité connue à l'un de ses composants.",
        "Le concédant accorde au concessionnaire un droit exclusif de distribution des produits sur le territoire français pour une durée de trois ans à compter de la date d'effet du contrat.",
        "Les cotisations patronales d'assurance maladie s'élèvent à 13 % sur les rémunérations inférieures à 2,5 SMIC et à 7 % au-delà.",
        "HbA1c : 9,2 % ; glycémie à jeun : 14,6 mmol/L — instauration d'une insulinothérapie intensive recommandée.",
        "L'entraînement utilise l'optimiseur AdamW avec un taux d'apprentissage initial de 3 × 10⁻⁴ et un programme de recuit cosinus sur 100 époques ; taille de lot : 256.",
        "Le chiffre d'affaires consolidé pour l'exercice 2025 s'établit à 587,2 M€, en progression de 18,6 % ; le résultat net part du groupe s'élève à 64,3 M€.",
        "Le RTO du système est fixé à 4 heures et le RPO à 1 heure, conformément aux exigences du PCA de niveau III.",
        "Demandes : 1) qu'il soit fait interdiction au défendeur de poursuivre les actes de contrefaçon ; 2) que le défendeur soit condamné à verser 5 M€ de dommages et intérêts.",
        "Ordonnance : amoxicilline gélules 500 mg, 1 gélule 3 fois par jour pendant 7 jours ; ibuprofène LP 300 mg, 1 comprimé 2 fois par jour si douleur.",
        "Le SoC est gravé en technologie TSMC 5 nm, intégrant 12 milliards de transistors ; fréquence maximale : 3,5 GHz ; TDP : 65 W.",
        "Changement de méthode comptable : le Groupe applique la norme IFRS 15 depuis le 1er janvier 2026 selon la méthode rétrospective complète.",
        "Pool de connexions : nombre max. 200, nombre min. inactif 20, délai de connexion 30 s.",
        "En vertu de l'article L. 1234-1 du Code du travail, le salarié licencié a droit à un préavis dont la durée dépend de son ancienneté.",
        "J3 post-remplacement valvulaire aortique : constantes hémodynamiques stables, débit du drain thoracique en diminution ; retrait prévu demain.",
        "Le système maintient un débit de 100 000 req/s avec une latence p99 ≤ 200 ms.",
        "L'opération constitue une convention réglementée au sens de l'article L. 225-38 du Code de commerce et doit être soumise à l'approbation de l'assemblée générale.",
        "Mécanisme de confidentialité différentielle : injection de bruit laplacien lors de l'agrégation des données ; budget de confidentialité ε = 1,0.",
    ],
    "口语俚语": [
        "Wesh, c'est ouf ce truc ! J'en reviens pas !",
        "Mdr, j'suis mort de rire, c'est trop ça !",
        "T'as vu le match hier ? C'était un truc de dingue !",
        "Chelou ton histoire, j'y crois pas trop.",
        "La meuf elle est trop stylée, j'avoue.",
        "Ptdr, il a dit quoi là ? C'est n'importe quoi !",
        "Tkt frère, on gère ! Ça va le faire.",
        "Frère, j'suis au bout de ma vie, j'ai trop de boulot.",
        "Ça claque ! Ce resto est une dinguerie !",
        "Sah, on y va là ? J'ai la dalle.",
        "Askip y'a une soirée ce soir. Tu viens ?",
        "J'me suis fait arnaquer, le mec m'a vendu une daube.",
        "C'est relou, le métro est encore en panne.",
        "On se pose au parc ? Il fait trop beau.",
        "Pas ouf le film, je m'attendais à mieux.",
        "Genre tu savais pas ? Tout le monde est au courant !",
        "Ça me saoule grave, j'en ai marre.",
        "C'est chaud, il a réussi l'exam du premier coup.",
        "Bien ou bien ? Ça faisait longtemps !",
        "J'ai le seum, j'ai raté le dernier bus.",
        "Franchement, la bouffe à la cantoche c'est pas terrible.",
        "Il est chanmé ton pote, il m'a trop fait rire.",
        "Wesh tranquille, prends ton temps.",
        "C'est la hess, j'ai plus un rond jusqu'à la fin du mois.",
        "Grave ! C'est exactement ce que je pensais.",
        "Bg, t'as changé de coupe ? Ça te va trop bien.",
        "J'suis claqué, j'ai pas dormi de la nuit.",
        "Ah ouais ? Sérieux ? C'est un bail ça !",
        "Ça marche, je note ! On fait comme ça.",
        "Bref, on s'en fout, passons à autre chose.",
        "Au top ! Merci frérot, t'es un boss !",
    ],
}
