LANG_NAME = "印尼语"
LANG_CODE = "id-ID"

TEMPLATES = {
    "常规文案": [
        "Prakiraan cuaca hari ini menyebutkan Jakarta akan diguyur hujan lebat disertai petir pada sore hari.",
        "Pemberitahuan: Sistem akan ditutup sementara besok pukul 02:00–06:00 WIB untuk pemeliharaan rutin.",
        "KRL Commuter Line rute Bogor–Jakarta Kota mengalami keterlambatan akibat gangguan sinyal.",
        "Paket makan siang baru mencakup hidangan utama, salad, sup, dan minuman dengan harga spesial.",
        "Pengurus RT mengumumkan pemasangan sistem CCTV baru di lingkungan perumahan.",
        "Bapak/Ibu Wali Murid: Rapat wali murid akan diadakan hari Rabu depan pukul 14:30 WIB.",
        "BMKG mengeluarkan peringatan dini cuaca ekstrem untuk wilayah Jawa Barat dan Banten.",
        "Perpustakaan kembali buka hari ini setelah dua minggu direnovasi.",
        "Film dokumenter ini mengisahkan kehidupan orangutan di hutan Kalimantan.",
        "Kereta api Argo Bromo Anggrek akan segera tiba di Stasiun Gambir. Penumpang turun harap bersiap.",
        "Kurir berhasil mengantarkan pesanan tepat waktu meskipun hujan deras.",
        "Relawan mengadakan kerja bakti membersihkan sungai di wilayah Ciliwung pada akhir pekan.",
        "Museum Nasional menggelar pameran khusus artefak kerajaan Majapahit.",
        "Saat Lebaran, arus mudik memuncak di seluruh terminal dan stasiun kereta api.",
        "Acara makan malam akhir tahun perusahaan akan diadakan pada 23 Desember di sebuah restoran di Kemang.",
        "Kemendikbudristek menerbitkan panduan baru tentang kurikulum merdeka untuk sekolah dasar.",
        "Warung nasi Padang di gang kecil itu selalu ramai dan sering kehabisan rendang sebelum jam 11.",
        "Masyarakat kini dapat mengurus dokumen kependudukan secara daring melalui aplikasi Dukcapil.",
        "Jalur sepeda baru menghubungkan Taman Mini Indonesia Indah dengan stasiun LRT terdekat.",
        "Selama libur Natal dan Tahun Baru, objek wisata populer menerapkan sistem reservasi daring.",
        "Malam ini malam takbiran. Warga berkumpul di masjid untuk menyambut Hari Raya Idul Fitri.",
        "Paket Anda telah tiba di loker. Silakan ambil menggunakan kode verifikasi.",
        "Kantin sekolah kini menyediakan menu vegetarian dan bebas gluten.",
        "Di ruang tunggu mengalun musik gamelan yang lembut, menciptakan suasana tenang.",
        "Simulasi evakuasi kebakaran akan dilaksanakan Jumat ini pukul 10:00 WIB di lobi lantai dasar.",
        "Pohon kamboja di halaman tetangga sedang berbunga, semerbak harum memenuhi gang.",
        "Hari ini awal musim kemarau, tetapi Jakarta masih terasa panas dan lembap.",
        "Kedai kopi baru mengadakan promo pembukaan: beli satu gratis satu.",
        "Kakek bangun setiap pagi pukul lima untuk jalan-jalan di taman dekat rumah.",
        "Sekolah menginformasikan perubahan jam pulang siswa mulai minggu depan.",
        "Bu guru menggambar peta Indonesia di papan tulis dan meminta murid-murid menyebutkan ibu kota provinsi.",
    ],
    "长难句": [
        "Meskipun pemerintah telah berkali-kali mengeluarkan kebijakan untuk menstabilkan harga kebutuhan pokok, harga barang di pasar tetap terus merangkak naik, membuat beban hidup masyarakat kecil semakin berat.",
        "Seandainya krisis moneter 1998 tidak terjadi, reformasi struktur ekonomi Indonesia kemungkinan besar akan menempuh jalur yang sama sekali berbeda dari yang kita kenal sekarang.",
        "Putusan pengadilan ini melampaui sekadar penyelesaian kasus individual dan menetapkan preseden penting dalam menentukan batas-batas hak perlindungan data pribadi di era digital.",
        "Secanggih apa pun teknologi penerjemahan mesin, menerjemahkan nuansa budaya dan keindahan sastra sebuah karya secara utuh dan setia masih merupakan tantangan yang belum terpecahkan.",
        "Menurut laporan BPK, instansi yang diperiksa telah mengesampingkan prosedur pengendalian internal dalam pelaksanaan anggaran dan berulang kali melakukan pengadaan langsung tanpa mekanisme tender yang semestinya.",
        "Kekayaan linguistik bahasa Indonesia yang menyerap unsur dari berbagai bahasa daerah dan bahasa asing merupakan cerminan keberagaman budaya Nusantara yang patut dijaga dan dilestarikan.",
        "Upaya mengatasi urbanisasi berlebihan semata-mata melalui insentif finansial menunjukkan ketidakpahaman terhadap penyebab struktural yang mendorong kaum muda meninggalkan desa.",
        "Kuasa hukum terdakwa berargumen bahwa bukti digital yang diajukan oleh jaksa penuntut umum diperoleh tanpa mengikuti prosedur hukum acara yang berlaku, sehingga tidak dapat diterima sebagai alat bukti yang sah.",
        "Yang membuat novel-novel pengarang ini meresahkan adalah penolakannya untuk menjatuhkan penilaian moral atas tokoh-tokohnya, sehingga memaksa pembaca menarik kesimpulan etis sendiri.",
        "Di daerah-daerah yang terancam ditinggalkan penduduknya, pemerintah daerah menawarkan subsidi perumahan, pendidikan, dan kesehatan, tetapi tingkat keberhasilan program tersebut masih jauh dari harapan.",
        "Menganalisis sejarah Indonesia modern tanpa mempertimbangkan dampak penjajahan Belanda selama 350 tahun ibarat mempelajari pohon tanpa memperhatikan akarnya.",
        "Kenaikan permukaan laut akibat perubahan iklim mengancam jutaan penduduk pesisir, dan pertanyaan apakah negara-negara industri akan memenuhi komitmen pengurangan emisi telah menjadi isu keadilan global.",
        "Artefak yang ditemukan di situs arkeologi bukan sekadar benda seni, melainkan bukti sejarah yang mengungkap jaringan perdagangan maritim Nusantara pada era kerajaan Hindu-Buddha.",
        "Kalaupun negosiasi berhasil mencapai kesepakatan, kemungkinan timbulnya perselisihan di tahap implementasi akibat perbedaan penafsiran antara para pihak tetap tidak dapat dikesampingkan.",
        "Selama otonomi guru di ruang kelas belum terjamin, reformasi pendidikan apa pun, sebaik apa pun rancangannya, akan tetap menjadi macan kertas belaka.",
        "Yang memicu kontroversi di dunia akademik bukanlah kelemahan metodologi penelitian tersebut, melainkan kesimpulannya sendiri yang secara frontal menantang teori mapan selama puluhan tahun.",
        "Kuasa hukum penggugat berdalih bahwa bukti elektronik yang disampaikan tergugat memiliki cacat dalam rantai penyimpanan sehingga tidak memiliki kekuatan pembuktian.",
        "Peribahasa mengatakan, ajarilah seseorang memancing daripada memberinya ikan; tetapi apa gunanya mengajar memancing jika yang bersangkutan tidak mampu membeli kail?",
        "Di dunia yang rantai pasokan globalnya saling terhubung erat, gangguan pada satu simpul kritis dapat memicu reaksi berantai yang dampaknya jauh melampaui perkiraan awal.",
        "Apabila pembeli tidak menyelesaikan pemeriksaan dalam jangka waktu yang ditentukan kontrak, maka dianggap telah menerima secara diam-diam bahwa produk yang diserahkan memenuhi standar kualitas yang disepakati.",
        "Semakin banyak bukti ilmiah yang menunjukkan bahwa paparan jangka panjang terhadap polutan lingkungan dalam dosis rendah dapat merusak perkembangan saraf anak-anak, dengan dampak yang baru terlihat pada masa remaja.",
        "Kehebatan sejati sutradara ini terletak pada kemampuannya membangkitkan empati penonton terhadap setiap karakter tanpa perlu menunjuk secara langsung siapa yang harus dikasihani.",
        "Meskipun teknologi blockchain secara teori mampu menyelesaikan masalah kepercayaan dalam pembayaran lintas batas, perbedaan kerangka regulasi antarnegara tetap menjadi hambatan utama adopsi massal.",
        "Manuskrip lontar yang ditemukan dalam penggalian mengalami kerusakan parah, tetapi teknologi pencitraan inframerah berhasil mengungkap sejumlah teks kuno yang belum pernah diketahui sebelumnya.",
        "Desain jembatan ini harus mampu menahan beban lebih dari seratus ribu kendaraan per hari sekaligus menjamin keamanan struktural saat gempa berkekuatan 7 skala Richter atau lebih.",
        "Lebih tepat menafsirkan pengunduran dirinya sebagai protes diam-diam terhadap kompromi berulang yang dilakukan manajemen terhadap nilai-nilai inti organisasi, ketimbang sekadar keputusan pribadi.",
        "Tidak adanya mekanisme koordinasi antarinstansi yang efektif menyebabkan setiap lembaga bertindak sendiri-sendiri saat menghadapi krisis kesehatan darurat, sehingga waktu respons optimal terlewatkan.",
        "Ekonom paling optimistis sekalipun mengakui bahwa prospek pertumbuhan ekonomi yang bergantung pada ekspor telah merosot secara signifikan di tengah meningkatnya ketegangan perdagangan internasional.",
        "Apa yang tampak sebagai sengketa biasa antarpenghuni apartemen ternyata menyimpan rangkaian penyimpangan yang meliputi penjualan ilegal dan penyalahgunaan dana pemeliharaan gedung.",
        "Transformasi digital di bidang pendidikan menuntut penanganan simultan terhadap tiga aspek: infrastruktur teknologi, kompetensi digital guru, dan keamanan informasi.",
        "Semakin besar ketergantungan masyarakat pada kecerdasan buatan dalam pengambilan keputusan, semakin mendesak kebutuhan akan diskusi tentang transparansi algoritma dan akuntabilitas pengembangnya.",
    ],
    "短文本": [
        "Konfirmasi", "Batal", "Kirim", "Kembali", "Berikutnya",
        "Simpan draf", "Beli sekarang", "Tambah ke keranjang", "Lihat detail", "Habis terjual",
        "Memuat", "Segarkan", "Cari", "Pengaturan", "Akun saya",
        "Notifikasi", "Keluar", "Ubah kata sandi", "Verifikasi telepon", "Verifikasi identitas",
        "Sedang ditinjau", "Disetujui", "Ditolak", "Menunggu", "Selesai",
        "Tidak ada data", "Kesalahan jaringan", "Silakan coba lagi", "Berhasil", "Kesalahan input",
        "Pilih semua", "Hapus", "Edit", "Salin tautan", "Bagikan",
        "Favorit", "Suka", "Laporkan", "Blokir", "Ikuti",
        "Beranda", "Jelajahi", "Keranjang", "Profil", "Bantuan",
    ],
    "数字日期": [
        "Kamis, 14 Mei 2026",
        "Total pesanan: Rp 1.298.500",
        "Telepon: (021) 1234-5678",
        "HP: +62 812-3456-7890",
        "NIK: 3201012345678901",
        "No. resi: ID1234567890123",
        "Jam operasional: Senin–Jumat 09:00–17:30 WIB (Sabtu, Minggu & hari libur: tutup)",
        "Rapat: Senin, 1 Juni 2026, 14:00–16:30 WIB",
        "Suhu: 24°C – 38°C",
        "Modal dasar: Rp 5.000.000.000 (lima miliar rupiah)",
        "Plat nomor: B 1234 ABC",
        "Kode pos: 10110",
        "Nomor kontrak: HT-2026-05-0378",
        "Nomor rekening: 1234567890 — Bank BCA",
        "Jumlah tagihan: Rp 86.400.000 (termasuk PPN 12%)",
        "Koordinat: 6°12′00″ LS, 106°49′00″ BT",
        "Luas: 128,56 m² (luas bangunan)",
        "Penerbangan GA123, berangkat 08:45, tiba 11:20",
        "Kata sandi: 8–16 karakter, wajib huruf besar, huruf kecil, dan angka",
        "Versi: v3.2.1-beta (build 20260514)",
        "Skor: 3-2 (perpanjangan waktu)",
        "Suku bunga: 4,35% per tahun (0,3625% per bulan)",
        "Ketinggian: 4.718 meter di atas permukaan laut",
        "Tanggal kedaluwarsa: 15/03/2027",
        "Kode saham: BBCA (Bank Central Asia)",
        "Alamat IP: 192.168.1.100:8080",
        "NPWP: 12.345.678.9-012.345",
        "Pendapatan kuartal III: naik 12,7% dibanding periode yang sama tahun lalu",
        "Kemasan: 500 ml × 24 botol/karton",
        "Radius pengiriman: 5 km, estimasi waktu 30–45 menit",
    ],
    "特殊字符": [
        "【PENGUMUMAN PENTING】Jadwal libur nasional 2026",
        "«Bumi Manusia» — mahakarya Pramoedya Ananta Toer",
        "Peringatan: Dilarang membawa makanan dan minuman ke dalam perpustakaan!!!",
        "Harga: Rp 298.000 → Rp 198.000 (promo terbatas)",
        "Penilaian: ★★★★☆ (4,5/5,0)",
        "Rute: Jakarta → Bandung → Semarang → Surabaya → Bali",
        "OS yang didukung: Windows / macOS / Linux (64-bit)",
        "Rumus: E = mc², dengan c ≈ 3×10⁸ m/s",
        "Catatan: Harga belum termasuk PPN (±5% variasi)",
        "Kontak: ☎ (021) 1234-5678 / ✉ info@contoh.co.id / 📍 Sudirman, Jakarta",
        "Progres: ████████░░ 80%",
        "♻️ Pisahkan sampah daur ulang ke tempat yang sesuai ♻️",
        "⚠️ Bahaya: Tegangan tinggi 380V — Dilarang mendekat! ⚠️",
        "— Pramoedya A. T., Bumi Manusia: «Kau harus adil sejak dalam pikiran…»",
        "【SUDAH DIPERBAIKI ✓】Error server 500 sudah teratasi @semua",
        "Karakter terlarang dalam nama file: \\ / : * ? \" < > |",
        "Matematika: ∑(i=1→n) aᵢ × bᵢ = a·b",
        "Kimia: 2H₂ + O₂ → 2H₂O (reaksi eksoterm)",
        "© 2026 PT Contoh Indonesia. Hak cipta dilindungi undang-undang.",
        "Emisi CO₂: sekitar 2,3 kg/km²·tahun⁻¹",
        "Kekuatan kata sandi: lemah ☠️ / sedang ⚡ / kuat 💪",
        "【Teruskan】@Budi @Siti Lihat ini! 🔥🔥🔥",
        "Pilihan: (a) Benar (b) Salah (c) Tidak yakin (d) Tidak ada yang benar",
        "Juara 1 🥇: Rp 100 juta | Juara 2 🥈: Rp 50 juta | Juara 3 🥉: Rp 20 juta",
        "═══════════════════════════════════════════",
        "Aksara khusus Indonesia: tidak ada diakritik — tetapi ada kata serapan: café, naïf",
        "#jalan2 #kuliner #keseharian #vlog",
        "✓ Selesai  × Belum  ○ Sedang dikerjakan  △ Menunggu konfirmasi",
        "Emoji: 😀😂🤔😭🥰🤯👍🎉💯🔥❤️✅❌⚡🌈",
        "Multibahasa: Hari ini makan phở enak banget, おいしかった！",
    ],
    "边界场景": [
        "a" * 200,
        " " * 50 + "teks dikelilingi spasi" + " " * 50,
        "tes\ttab\tpemisah\tteks",
        "baris 1\nbaris 2\nbaris 3\nbaris 4\nbaris 5",
        "Ini adalah string uji yang sangat panjang. " + "Sistem harus mampu menangani string panjang dengan benar. " * 15,
        "",
        "   ",
        "aAbBcCdDeE campuran teks Indonesia-Inggris",
        "IndonesiaEnglish中文日本語한국어العربية campuran multibahasa",
        "ＡＢＣＤＥ１２３４５ karakter lebar penuh",
        "①②③④⑤⑥⑦⑧⑨⑩ angka dalam lingkaran",
        "㎡ ㎝ ㎞ ㎏ ℃ ℉ satuan khusus",
        "Tanda baca berulang!!!!!?????.....",
        "tanpaspasi" + "abcdefghijklmnopqrstuvwxyz" * 10,
        "Ejaan lama vs baru: dulu/dahulu, nampak/tampak, fikir/pikir",
        "Kata serapan: komputer, televisi, telepon, bis, taksi, manajemen",
        "Emoji berulang: " + "😀" * 100,
        "Spasi khusus: normal tidak-putus tipis lebar",
        "\u200ETanda LTR dan \u200Ftanda RTL tercampur",
        "Angka padat: 12345678901234567890.12345678901234567890",
        "Tanda baca campuran: Tes, this is a test.",
        "Jeda baris campuran\r\nWindows\nUnix\rMac lama",
        "HTML: <script>alert('XSS')</script><b>tebal</b>",
        "SQL injection: '; DROP TABLE users; --",
        "Path file: C:\\Users\\Tes\\Dokumen\\laporan.xlsx",
        "URL: https://contoh.co.id/cari?kata=tes&halaman=1#hasil",
        "Indentasi ekstrem:" + "\t" * 20 + "teks dengan indentasi dalam",
        "Baris kosong berurutan:\n\n\n\n\nTeks setelah 5 baris kosong",
        "Aksara Jawa: ꦗꦮ — aksara tradisional Nusantara",
        "Imbuhan: me-, ber-, pe-, ke-...-an, se-...-nya",
        "Bahasa gaul: gue, lu, emang, gak, udah, banget, dong",
    ],
    "专业术语": [
        "Berdasarkan Pasal 1243 KUH Perdata, debitur yang lalai memenuhi kewajibannya wajib membayar ganti rugi kepada kreditur.",
        "Pasien datang ke IGD dengan keluhan nyeri dada substernal yang menjalar ke lengan kiri; EKG menunjukkan elevasi segmen ST — kesan: STEMI akut.",
        "Sistem menggunakan arsitektur microservices dengan API Gateway untuk autentikasi dan pembatasan lalu lintas; komunikasi antarservis menggunakan gRPC.",
        "Goodwill dalam laporan posisi keuangan konsolidasian pada akhir periode pelaporan sebesar Rp 12,8 triliun, meningkat 23,5% dibanding periode sama tahun sebelumnya.",
        "Berdasarkan Hukum Acara Perdata, tergugat memiliki waktu 14 hari kerja untuk mengajukan jawaban setelah menerima surat gugatan.",
        "Hasil pemeriksaan histopatologi: karsinoma duktal invasif payudara kiri, grade II. Imunohistokimia: ER(+), PR(+), HER2 (2+), FISH negatif.",
        "Model mencapai akurasi Top-1 sebesar 87,3% pada set validasi ImageNet, dengan latensi inferensi 2,1 ms per gambar pada GPU A100.",
        "Saham emiten telah dicatatkan di Bursa Efek Indonesia pada tanggal 8 Mei 2026. Kode emiten: XXXX.",
        "Reksa dana dapat berinvestasi pada efek ekuitas yang tercatat, surat utang negara, obligasi korporasi, instrumen pasar uang, dan derivatif.",
        "MRI otak dengan kontras: lesi 3,2×2,8×2,5 cm di lobus temporalis kanan dengan enhancement heterogen.",
        "Apabila debitur tidak mematuhi perintah eksekusi, pengadilan dapat menerbitkan penetapan sita jaminan atas harta kekayaan debitur.",
        "Pendanaan Seri B dipimpin oleh firma modal ventura terkemuka dengan valuasi post-money sekitar Rp 52,5 triliun.",
        "Orkestrasi kontainer menggunakan kluster Kubernetes, dengan manajemen siklus hidup aplikasi melalui Helm Charts dan observabilitas melalui Prometheus + Grafana.",
        "Obat ini hanya dapat diperoleh dengan resep dokter dan dikontraindikasikan pada pasien dengan riwayat hipersensitivitas terhadap komponen obat. Penyesuaian dosis diperlukan pada pasien gangguan hati atau ginjal.",
        "Pihak pemberi lisensi memberikan hak distribusi eksklusif kepada penerima lisensi di seluruh wilayah Indonesia untuk jangka waktu tiga tahun sejak tanggal efektif kontrak.",
        "Iuran BPJS Ketenagakerjaan: JKK 0,24%-1,74% (pemberi kerja), JKM 0,3% (pemberi kerja), JHT 5,7% (3,7% pemberi kerja + 2% pekerja), JP 3% (2% pemberi kerja + 1% pekerja).",
        "HbA1c pasien 9,2%, glukosa darah puasa 14,6 mmol/L — direkomendasikan untuk memulai terapi insulin intensif.",
        "Pelatihan menggunakan optimizer AdamW dengan learning rate awal 3×10⁻⁴, jadwal cosine annealing, 100 epoch, dan batch size 256.",
        "Pendapatan konsolidasian tahun buku 2025 mencapai Rp 58,72 triliun (+18,6% YoY); laba bersih yang dapat diatribusikan kepada pemilik entitas induk Rp 6,43 triliun.",
        "RTO sistem ditetapkan 4 jam dan RPO 1 jam, memenuhi persyaratan Business Continuity Plan (BCP) level 3.",
        "Petitum: 1. Menyatakan tergugat telah melanggar merek terdaftar milik penggugat. 2. Menghukum tergugat membayar ganti rugi sebesar Rp 5 miliar.",
        "Resep: Amoxicillin kapsul 500 mg, 3× sehari sesudah makan selama 7 hari; Ibuprofen 300 mg lepas lambat, 2× sehari bila nyeri.",
        "SoC diproduksi dengan proses TSMC 5 nm, memuat 12 miliar transistor, clock maksimum 3,5 GHz, TDP 65 W.",
        "Perubahan kebijakan akuntansi: Perusahaan menerapkan PSAK 72 (IFRS 15) efektif 1 Januari 2026, menggunakan metode retrospektif penuh.",
        "Konfigurasi connection pool: koneksi maksimum 200, koneksi idle minimum 20, connection timeout 30 detik.",
        "Berdasarkan UU Ketenagakerjaan, pemutusan hubungan kerja karena efisiensi wajib disertai pembayaran pesangon sesuai masa kerja karyawan.",
        "Hari ke-3 pasca penggantian katup aorta: tanda vital stabil, output drain berkurang; rencana pelepasan drain dada besok.",
        "Sistem mempertahankan throughput 100k QPS pada latensi p99 ≤ 200 ms.",
        "Transaksi ini termasuk transaksi material yang memerlukan persetujuan RUPS dan persetujuan OJK.",
        "Mekanisme differential privacy: noise Laplacian diinjeksikan saat agregasi data, privacy budget ε = 1,0.",
    ],
    "口语俚语": [
        "Serius?! Gak percaya deh! Masa sih?!",
        "Wkwkwkwk ngakak parah! Kocak banget!",
        "Hah? Gue yang terakhir tau? Parah sih...",
        "Yuk buruan! Telat nanti gak dapet tempat!",
        "Enak banget sumpah! Harus balik lagi deh!",
        "Ih kok gitu sih. Keterlaluan banget.",
        "Iya bener. Setuju banget sama lo.",
        "Males banget hari ini... Gak mau ngapa-ngapain.",
        "Gila sih ini! Legend banget! Epic!",
        "Oke siap, gue yang urus!",
        "Iri banget... Pengen liburan juga...",
        "Gimana ya... agak bingung juga sih...",
        "Hadeh, hujan lagi... Bete banget.",
        "Makan yuk? Laper parah nih.",
        "Anjay keren! Ranking satu?! Jenius lo!",
        "Lo gila ya? Siapa yang kayak gitu?",
        "Gue lakuin aja gitu. Biasa aja kok.",
        "Sorry ganggu lagi, tapi butuh bantuan nih...",
        "Santai aja kali. Gak segitunya juga.",
        "Udah cukup. Gak perlu nambah lagi.",
        "Wih, keren banget! Mantap jiwa!",
        "Terserah deh. Suka-suka lu aja.",
        "Udah deh. Jangan lebay.",
        "Pengen ikut! Ajak gue dong!",
        "Jangan lupa ya! Janji lho! Penting!",
        "Siap! Langsung gue kerjain!",
        "Susah banget ini... Pusing kepala gue.",
        "AAAA!!! Band favorit gue mau ke Indonesia!!! Tiket sekarang!!!",
        "Hmm... iya... yaudah... gapapa deh...",
        "Bro, bantuin dong! Urgent nih!",
        "Buruan! Tinggal dikit! Stok terbatas!",
    ],
}
