LANG_NAME = "马来语"
LANG_CODE = "ms-MY"

TEMPLATES = {
    "常规文案": [
        "Ramalan cuaca hari ini menjangkakan hujan lebat di Lembah Klang pada sebelah petang.",
        "Makluman: Sistem akan ditutup sementara esok dari jam 2:00 hingga 6:00 pagi untuk penyelenggaraan.",
        "Perkhidmatan LRT Laluan Kelana Jaya mengalami kelewatan akibat gangguan isyarat.",
        "Set makan tengah hari baharu termasuk hidangan utama, salad, sup dan minuman pada harga istimewa.",
        "Pihak pengurusan kondominium memaklumkan pemasangan sistem keselamatan baharu.",
        "Ibu bapa yang dihormati, mesyuarat PIBG akan diadakan pada hari Rabu depan jam 2:30 petang.",
        "Jabatan Meteorologi Malaysia mengeluarkan amaran cuaca buruk untuk pantai timur Semenanjung.",
        "Perpustakaan dibuka semula hari ini selepas dua minggu ditutup untuk pengubahsuaian.",
        "Dokumentari ini merakamkan kehidupan hidupan liar di Taman Negara Pahang.",
        "Kereta api ETS akan tiba di stesen KL Sentral tidak lama lagi. Sila bersedia untuk turun.",
        "Penghantar makanan berjaya menghantar pesanan tepat pada waktunya walaupun hujan lebat.",
        "Sukarelawan menganjurkan gotong-royong membersihkan pantai pada hujung minggu.",
        "Muzium Negara mengadakan pameran khas mengenai warisan seni batik Malaysia.",
        "Semasa Hari Raya Aidilfitri, suasana meriah memenuhi setiap kampung di seluruh negara.",
        "Majlis makan malam akhir tahun syarikat akan diadakan pada 23 Disember di sebuah hotel di KLCC.",
        "Kementerian Pendidikan mengumumkan dasar baharu berkaitan kurikulum sekolah rendah.",
        "Kedai roti di kampung menjual roti canai segar yang habis dijual sebelum tengah hari.",
        "Rakyat kini boleh memohon dokumen rasmi secara dalam talian melalui portal MyGovernment.",
        "Laluan basikal baharu menghubungkan Taman Tasik Titiwangsa dengan stesen LRT.",
        "Semasa cuti perayaan Deepavali, tempat-tempat pelancongan utama memerlukan tempahan awal.",
        "Malam ini ialah malam Tahun Baharu Cina. Seluruh keluarga berkumpul untuk makan malam reunion.",
        "Bungkusan anda telah sampai di loker. Sila ambil menggunakan kod pengesahan.",
        "Kafeteria kini menawarkan pilihan makanan halal dan vegetarian dalam menu harian.",
        "Di ruang menunggu, muzik lembut dimainkan mewujudkan suasana yang menenangkan.",
        "Latihan kebakaran akan diadakan pada hari Jumaat ini jam 10:00 pagi di lobi utama.",
        "Pokok bunga raya jiran berbunga dan harumnya memenuhi seluruh lorong.",
        "Hari ini ialah permulaan musim tengkujuh, tetapi cuaca masih panas terik.",
        "Kedai kopi baharu mengadakan promosi pembukaan: minuman kedua separuh harga.",
        "Atuk bangun awal setiap pagi untuk bersenam di taman berhampiran.",
        "Sekolah memaklumkan perubahan waktu pulang murid bermula minggu hadapan.",
        "Cikgu melukis peta Malaysia di papan hitam dan meminta murid mengenal pasti ibu negeri setiap negeri.",
    ],
    "长难句": [
        "Walaupun kerajaan telah melaksanakan pelbagai langkah untuk menstabilkan pasaran hartanah, harga rumah di bandar-bandar besar masih terus meningkat, menyebabkan rasa kecewa yang semakin meningkat dalam kalangan pembeli rumah pertama.",
        "Sekiranya krisis kewangan tidak berlaku pada masa itu, reformasi sistem perbankan negara berkemungkinan besar akan mengambil haluan yang sama sekali berbeza.",
        "Keputusan mahkamah ini bukan sahaja menyelesaikan kes tertentu tetapi juga mewujudkan duluan yang penting dalam menentukan skop hak perlindungan data peribadi dalam era digital.",
        "Walau setinggi mana pun kemajuan teknologi terjemahan automatik, pemindahan nuansa budaya dan keindahan gaya bahasa sesebuah karya sastera dengan tepat dan setia masih kekal sebagai cabaran yang belum dapat diatasi.",
        "Laporan Ketua Audit Negara mendedahkan bahawa agensi berkenaan telah meminggirkan prosedur kawalan dalaman dalam perbelanjaan bajet dan kerap menggunakan perolehan terus secara berlebihan.",
        "Kekayaan linguistik bahasa Melayu yang digunakan di beberapa buah negara merupakan warisan budaya yang kepelbagaiannya harus dilihat sebagai kekuatan dan bukan perpecahan.",
        "Percubaan untuk mengatasi masalah penghijrahan penduduk luar bandar hanya dengan insentif kewangan mendedahkan kekurangan pemahaman terhadap punca-punca struktur yang mendorong golongan muda meninggalkan kampung.",
        "Peguam tertuduh berhujah bahawa bukti digital yang dikemukakan oleh pihak pendakwaan telah diperoleh tanpa mematuhi prosedur undang-undang yang sewajarnya dan oleh itu tidak boleh diterima sebagai keterangan.",
        "Apa yang menjadikan novel-novel pengarang ini menggelisahkan pembaca ialah keengganannya untuk mengeluarkan penghakiman moral terhadap watak-wataknya, sekali gus memaksa pembaca membuat kesimpulan etika sendiri.",
        "Di kawasan luar bandar yang terancam kehilangan populasi, kerajaan menawarkan subsidi perumahan, pendidikan, dan kesihatan untuk menarik penduduk baharu, namun kadar penetapan masih mengecewakan.",
        "Menganalisis sejarah moden Malaysia tanpa mengambil kira kesan penjajahan adalah umpama mengkaji sebatang pokok sambil mengabaikan akar-akarnya.",
        "Kenaikan paras laut yang disebabkan oleh perubahan iklim mengancam komuniti pesisir, dan persoalan sama ada negara-negara perindustrian akan memenuhi komitmen pengurangan pelepasan karbon telah menjadi isu keadilan global.",
        "Artifak yang ditemui di tapak arkeologi bukan sekadar barangan hiasan semata-mata, tetapi merupakan bukti sejarah yang memberikan pencerahan tentang rangkaian perdagangan purba di Nusantara.",
        "Meskipun rundingan berjaya mencapai persetujuan, kemungkinan pertikaian timbul semula dalam fasa pelaksanaan akibat perbezaan tafsiran antara pihak-pihak yang terlibat tidak boleh diketepikan.",
        "Selagi autonomi guru di dalam bilik darjah tidak dijamin, sebarang pembaharuan pendidikan, walau sebaik mana pun reka bentuknya, pasti tidak akan mencapai matlamat yang dihasratkan.",
        "Yang mencetuskan kontroversi dalam kalangan akademik bukanlah kelemahan metodologi kajian tersebut, tetapi dapatan kajian itu sendiri yang secara langsung bertentangan dengan teori yang diterima umum selama ini.",
        "Peguam pihak plaintif berhujah bahawa bukti elektronik yang dikemukakan oleh defendan mempunyai kecacatan dalam rantaian jagaan yang menjadikannya tidak sah di sisi undang-undang.",
        "Pepatah berkata, ajar seseorang memancing lebih baik daripada memberi ikan, tetapi apa gunanya mengajar memancing jika mereka tidak mampu membeli pancing?",
        "Dalam dunia di mana rantaian bekalan global saling berkait rapat, gangguan pada satu titik penting boleh mencetuskan reaksi berantai yang melangkaui sebarang jangkaan.",
        "Jika pihak pembeli tidak menyelesaikan pemeriksaan dalam tempoh yang ditetapkan dalam kontrak, ia dianggap telah menerima secara tersirat bahawa produk yang dihantar menepati standard kualiti yang dipersetujui.",
        "Semakin banyak bukti menunjukkan bahawa pendedahan berpanjangan kepada bahan pencemar alam sekitar pada dos rendah boleh merosakkan perkembangan neurologi kanak-kanak, dengan kesan yang hanya ketara semasa remaja.",
        "Kehebatan sebenar pengarah filem ini terletak pada kemampuannya membangkitkan empati penonton terhadap setiap watak tanpa perlu memberitahu secara terang-terangan siapa yang patut dikasihani.",
        "Walaupun teknologi blockchain secara teorinya mampu menyelesaikan masalah kepercayaan dalam pembayaran rentas sempadan, perbezaan kerangka kawal selia antara negara kekal sebagai halangan utama kepada penggunaan meluas.",
        "Manuskrip yang ditemui dalam penggalian telah rosak teruk, namun teknologi pengimejan inframerah berjaya mendedahkan beberapa teks purba yang tidak pernah diketahui sebelum ini.",
        "Reka bentuk jambatan ini perlu menampung lebih 100,000 kenderaan setiap hari dan pada masa yang sama menjamin keselamatan struktur semasa gempa bumi magnitud 7 atau lebih.",
        "Lebih tepat untuk melihat peletakan jawatannya sebagai bantahan senyap terhadap pengkompromian nilai teras organisasi yang berulang kali dilakukan oleh pihak pengurusan.",
        "Ketiadaan mekanisme penyelarasan antara agensi yang berkesan menyebabkan setiap agensi bertindak secara berasingan semasa krisis kesihatan, sekali gus terlepas masa terbaik untuk bertindak balas.",
        "Pakar ekonomi yang paling optimistik sekalipun mengakui bahawa prospek pertumbuhan ekonomi yang bergantung kepada eksport telah menjadi suram dalam suasana ketegangan perdagangan antarabangsa yang semakin meningkat.",
        "Apa yang kelihatan seperti pertikaian biasa antara penghuni kondominium sebenarnya menyembunyikan rangkaian penyelewengan yang melibatkan penjualan haram dan penyalahgunaan dana penyelenggaraan.",
        "Transformasi digital dalam pendidikan memerlukan penanganan serentak terhadap tiga aspek: infrastruktur teknologi, kecekapan digital guru, dan keselamatan maklumat.",
        "Semakin masyarakat bergantung kepada kecerdasan buatan untuk membuat keputusan, semakin mendesak perbincangan mengenai ketelusan algoritma dan akauntabiliti pembangun sistem tersebut.",
    ],
    "短文本": [
        "Sahkan", "Batal", "Hantar", "Kembali", "Seterusnya",
        "Simpan draf", "Beli sekarang", "Tambah ke troli", "Lihat butiran", "Habis dijual",
        "Memuatkan", "Muat semula", "Cari", "Tetapan", "Akaun saya",
        "Pemberitahuan", "Log keluar", "Tukar kata laluan", "Sahkan telefon", "Sahkan identiti",
        "Dalam semakan", "Diluluskan", "Ditolak", "Menunggu", "Selesai",
        "Tiada data", "Ralat rangkaian", "Sila cuba lagi", "Berjaya", "Ralat input",
        "Pilih semua", "Padam", "Sunting", "Salin pautan", "Kongsi",
        "Kegemaran", "Suka", "Laporkan", "Sekat", "Ikuti",
        "Laman utama", "Terokai", "Troli", "Profil", "Bantuan",
    ],
    "数字日期": [
        "Khamis, 14 Mei 2026",
        "Jumlah pesanan: RM 1,298.50",
        "Telefon: +603-1234 5678",
        "Telefon bimbit: +6012-345 6789",
        "No. MyKad: 860307-14-5678",
        "No. penjejakan: MY1234567890123",
        "Waktu operasi: Isnin–Jumaat, 09:00–17:30 (Sabtu, Ahad & cuti umum: tutup)",
        "Mesyuarat: Isnin, 1 Jun 2026, 14:00–16:30",
        "Suhu: 24°C – 38°C",
        "Modal berbayar: RM 5,000,000.00 (lima juta ringgit)",
        "No. pendaftaran kenderaan: WKL 1234",
        "Poskod: 50000",
        "No. kontrak: HT-2026-05-0378",
        "No. akaun bank: 1234567890 — Maybank",
        "Jumlah invois: RM 86,400.00 (termasuk SST)",
        "Koordinat: 3°08′51″ U, 101°41′36″ T",
        "Keluasan: 128.56 m² (keluasan lantai)",
        "Penerbangan MH123, berlepas 08:45, tiba 11:20",
        "Kata laluan: 8–16 aksara, termasuk huruf besar, huruf kecil dan nombor",
        "Versi: v3.2.1-beta (binaan 20260514)",
        "Skor: 3-2 (masa tambahan)",
        "Kadar faedah: 4.35% setahun (0.3625% sebulan)",
        "Ketinggian: 4,718 meter di atas paras laut",
        "Tarikh luput: 15/03/2027",
        "Kod saham: MAYBANK (Malayan Banking Berhad)",
        "Alamat IP: 192.168.1.100:8080",
        "No. pendaftaran syarikat: 202601012345 (1012345-X)",
        "Hasil suku ke-3: +12.7% berbanding tempoh sama tahun lepas",
        "Pembungkusan: 500 ml × 24 botol/kotak",
        "Radius penghantaran: 5 km, anggaran masa 30–45 minit",
    ],
    "特殊字符": [
        "【MAKLUMAN PENTING】Jadual cuti umum 2026",
        "«Hikayat Hang Tuah» — karya agung sastera Melayu",
        "Amaran: Dilarang membawa makanan dan minuman ke dalam perpustakaan!!!",
        "Harga: RM 29.80 → RM 19.80 (tawaran terhad)",
        "Penilaian: ★★★★☆ (4.5/5.0)",
        "Laluan: KL → Ipoh → Penang → Langkawi",
        "OS disokong: Windows / macOS / Linux (64-bit)",
        "Formula: E = mc², di mana c ≈ 3×10⁸ m/s",
        "Nota: Harga belum termasuk SST (±5% variasi)",
        "Hubungi: ☎ +603-1234 5678 / ✉ info@contoh.my / 📍 Bukit Bintang, KL",
        "Kemajuan: ████████░░ 80%",
        "♻️ Sila asingkan sisa kitar semula ♻️",
        "⚠️ Bahaya: Voltan tinggi 380V — Dilarang masuk! ⚠️",
        "— A. Samad Said, Salina: «Di antara dua daratan…»",
        "【SELESAI ✓】Ralat pelayan 500 telah diperbaiki @semua",
        "Aksara tidak dibenarkan dalam nama fail: \\ / : * ? \" < > |",
        "Matematik: ∑(i=1→n) aᵢ × bᵢ = a·b",
        "Kimia: 2H₂ + O₂ → 2H₂O (tindak balas eksotermik)",
        "© 2026 Syarikat Contoh Sdn. Bhd. Hak cipta terpelihara.",
        "Pelepasan CO₂: lebih kurang 2.3 kg/km²·tahun⁻¹",
        "Kekuatan kata laluan: lemah ☠️ / sederhana ⚡ / kuat 💪",
        "【Majukan】@Ali @Siti Tengok ni! 🔥🔥🔥",
        "Pilihan: (a) Betul (b) Salah (c) Tidak pasti (d) Tiada yang betul",
        "Tempat 1 🥇: RM 100,000 | Tempat 2 🥈: RM 50,000 | Tempat 3 🥉: RM 20,000",
        "═══════════════════════════════════════════",
        "Aksara khas Melayu: perkataan dengan imbuhan — me-, ber-, pe-, ke-...-an",
        "#pelancongan #makanan #kehidupan #vlog",
        "✓ Selesai  × Belum  ○ Sedang berjalan  △ Menunggu pengesahan",
        "Emoji: 😀😂🤔😭🥰🤯👍🎉💯🔥❤️✅❌⚡🌈",
        "Berbilang bahasa: Hari ini makan phở, おいしかった！",
    ],
    "边界场景": [
        "a" * 200,
        " " * 50 + "teks dikelilingi ruang kosong" + " " * 50,
        "ujian\ttab\tdipisahkan\tteks",
        "baris 1\nbaris 2\nbaris 3\nbaris 4\nbaris 5",
        "Ini ialah rentetan ujian yang sangat panjang. " + "Sistem perlu mengendalikan rentetan panjang dengan betul. " * 15,
        "",
        "   ",
        "aAbBcCdDeE campuran teks Melayu-Inggeris",
        "MelayuEnglish中文日本語한국어العربية campuran berbilang bahasa",
        "ＡＢＣＤＥ１２３４５ aksara lebar penuh",
        "①②③④⑤⑥⑦⑧⑨⑩ nombor bulat",
        "㎡ ㎝ ㎞ ㎏ ℃ ℉ unit khas",
        "Tanda baca berulang!!!!!?????.....",
        "tanparuang" + "abcdefghijklmnopqrstuvwxyz" * 10,
        "Huruf khas Jawi: ا ب ت ث ج — tulisan Jawi Melayu",
        "Kata pinjaman: komputer, televisyen, telefon, bas, teksi",
        "Emoji berulang: " + "😀" * 100,
        "Ruang khas: biasa tidak putus nipis lebar",
        "\u200ETanda LTR dan \u200Ftanda RTL bercampur",
        "Nombor padat: 12345678901234567890.12345678901234567890",
        "Tanda baca bercampur: Ujian, this is a test.",
        "Baris baharu bercampur\r\nWindows\nUnix\rMac lama",
        "HTML: <script>alert('XSS')</script><b>tebal</b>",
        "SQL injection: '; DROP TABLE users; --",
        "Laluan fail: C:\\Users\\Ujian\\Dokumen\\laporan.xlsx",
        "URL: https://contoh.com/cari?kata=ujian&halaman=1#keputusan",
        "Inden melampau:" + "\t" * 20 + "teks inden dalam",
        "Baris kosong berturut:\n\n\n\n\nTeks selepas 5 baris kosong",
        "Ejaan lama vs baharu: negri/negeri, sa-orang/seorang",
        "Imbuhan: memper-, diper-, berke-, se-...-nya",
        "Bahasa rojak: I nak pergi makan, you nak ikut tak?",
    ],
    "专业术语": [
        "Menurut Seksyen 74 Akta Kontrak 1950, pihak yang melanggar kontrak bertanggungjawab untuk membayar pampasan bagi sebarang kerugian yang dialami oleh pihak yang satu lagi.",
        "Pesakit datang ke jabatan kecemasan dengan aduan sakit dada menekan memancar ke lengan kiri; ECG menunjukkan ST elevation — diagnosis awal: STEMI akut.",
        "Sistem ini menggunakan seni bina perkhidmatan mikro dengan API Gateway untuk pengesahan dan kawalan kadar; komunikasi antara perkhidmatan menggunakan gRPC.",
        "Muhibah dalam penyata kedudukan kewangan disatukan pada akhir tempoh pelaporan ialah RM 12.8 bilion, meningkat 23.5% berbanding tempoh yang sama tahun sebelumnya.",
        "Menurut Kaedah-Kaedah Mahkamah 2012, defendan hendaklah memfailkan pembelaan dalam tempoh 14 hari selepas penyampaian writ dan pernyataan tuntutan.",
        "Laporan histopatologi: karsinoma duktal invasif payudara kiri, gred II. Imunohistokimia: ER(+), PR(+), HER2 (2+), FISH negatif.",
        "Model ini mencapai ketepatan Top-1 sebanyak 87.3% pada set pengesahan ImageNet, dengan kependaman inferens 2.1 ms setiap imej pada GPU A100.",
        "Saham biasa penerbit telah disenaraikan di Bursa Malaysia pada 8 Mei 2026. Kod saham: XXXX.",
        "Dana ini boleh melabur dalam ekuiti tersenarai, sekuriti kerajaan, bon korporat, instrumen pasaran wang, dan derivatif.",
        "MRI otak dengan kontras: lesi 3.2×2.8×2.5 cm di lobus temporal kanan dengan peningkatan heterogen.",
        "Sekiranya penghutang gagal mematuhi perintah pelaksanaan, mahkamah boleh mengeluarkan perintah garnisi atau perintah penyitaan harta.",
        "Pusingan pembiayaan Siri B diketuai oleh dana modal teroka terkemuka, dengan penilaian selepas pelaburan kira-kira RM 15 bilion.",
        "Orkestrasi kontena dijalankan melalui kluster Kubernetes, dengan pengurusan kitaran hayat aplikasi melalui Helm Charts dan pemerhatian melalui Prometheus + Grafana.",
        "Ubat ini adalah ubat preskripsi dan dikontraindikasikan pada pesakit yang mempunyai hipersensitiviti terhadap mana-mana komponennya. Pelarasan dos diperlukan bagi pesakit kegagalan hati atau buah pinggang.",
        "Pihak pemberi lesen memberikan hak pengedaran eksklusif di Malaysia kepada pihak pemegang lesen untuk tempoh tiga tahun dari tarikh kontrak berkuat kuasa.",
        "Caruman KWSP: majikan 12%, pekerja 11% daripada gaji bulanan. Had gaji caruman: RM 20,000.",
        "HbA1c pesakit ialah 9.2%, glukosa puasa 14.6 mmol/L — disyorkan untuk memulakan terapi insulin intensif.",
        "Latihan menggunakan pengoptimum AdamW dengan kadar pembelajaran awal 3×10⁻⁴, jadual cosine annealing, 100 epok dan saiz kelompok 256.",
        "Hasil disatukan bagi tahun kewangan 2025 ialah RM 58.72 bilion (+18.6% y/y); untung bersih ialah RM 6.43 bilion.",
        "RTO sistem ialah 4 jam dan RPO ialah 1 jam, memenuhi keperluan Pelan Kesinambungan Perniagaan (BCP) tahap 3.",
        "Relief yang dipohon: 1. Perintah defendan menghentikan pelanggaran tanda dagangan. 2. Perintah defendan membayar ganti rugi RM 5 juta.",
        "Preskripsi: Amoxicillin 500 mg kapsul, 3 kali sehari selepas makan selama 7 hari; Ibuprofen 300 mg pelepasan berpanjangan, 2 kali sehari jika sakit.",
        "SoC dikilangkan menggunakan proses TSMC 5 nm, mengandungi 12 bilion transistor, frekuensi jam maksimum 3.5 GHz dan TDP 65 W.",
        "Perubahan dasar perakaunan: Syarikat mengguna pakai MFRS 15 mulai 1 Januari 2026 secara retrospektif penuh.",
        "Konfigurasi kumpulan sambungan DB: sambungan maksimum 200, sambungan terbiar minimum 20, tamat masa sambungan 30 saat.",
        "Menurut Akta Kerja 1955, majikan hendaklah memberi notis penamatan sekurang-kurangnya empat minggu bagi pekerja yang telah berkhidmat kurang dari dua tahun.",
        "Hari ke-3 selepas pembedahan penggantian injap aorta: tanda vital stabil, output saliran berkurangan; perancangan untuk menanggalkan saliran dada esok.",
        "Sistem mengekalkan daya pemprosesan 100k QPS pada kependaman p99 ≤ 200 ms.",
        "Transaksi ini merupakan pemerolehan aset material yang memerlukan kelulusan mesyuarat agung pemegang saham dan Suruhanjaya Sekuriti.",
        "Mekanisme privasi pembezaan: hingar Laplace disuntik semasa pengagregatan data, belanjawan privasi ε = 1.0.",
    ],
    "口语俚语": [
        "Betul ke?! Tak percaya la! Serious ni?!",
        "Hahaha gelak sampai sakit perut! Lawak gila!",
        "Hah? Aku last orang tahu? Kesian betul...",
        "Jom cepat! Lambat nanti takde tempat!",
        "Sedap gila! Kena datang lagi next time!",
        "Eh tak betul la macam tu. Dah keterlaluan dah.",
        "Betul tu. Memang betul cakap kau.",
        "Malas nak buat apa-apa hari ni... Penat sangat.",
        "Gila best! Memang legend la!",
        "Ok ok, aku handle!",
        "Jeles la... Nak pergi travel jugak...",
        "Macam mana nak cakap eh... Complicated sikit...",
        "Haish, hujan lagi... Boring betul.",
        "Nak pergi makan tak? Lapar dah ni.",
        "Hebat la kau! Number one?! Genius!",
        "Gila ke apa? Siapa buat macam tu?",
        "Buat je la macam tu. Takde apa pun.",
        "Sorry ganggu lagi, tapi aku nak minta tolong sikit...",
        "Rileks la bro. Bukan apa sangat pun.",
        "Cukup la tu. Tak perlu tambah dah.",
        "Wah, best gila! Memang power!",
        "Suka hati la. Ikut kau je.",
        "Sudah la tu. Jangan banyak hal.",
        "Nak pergi jugak! Ajak aku sekali!",
        "Jangan lupa tau! Penting ni! Janji tau!",
        "Boleh! Settlekan sekarang!",
        "Susah gila... Pening kepala aku.",
        "AAAA!!! Band favourite aku datang Malaysia!!! Tiket cepat!!!",
        "Ermm... entah la... ok la tu...",
        "Bro, tolong aku boleh? Urgent ni!",
        "Cepat! Tinggal sikit je! Stok terhad!",
    ],
}
