LANG_NAME = "葡萄牙语"
LANG_CODE = "pt-BR"

TEMPLATES = {
    "常规文案": [
        "A previsão do tempo indica chuvas isoladas para a região metropolitana de São Paulo nesta tarde.",
        "Aviso: o sistema ficará indisponível amanhã das 2h às 6h para manutenção programada.",
        "A Linha 4-Amarela do Metrô está com atrasos devido a uma falha no sistema de sinalização.",
        "O novo combo executivo inclui prato principal, salada, sopa e bebida por R$ 39,90.",
        "O condomínio informa sobre a instalação de um novo sistema de portaria remota.",
        "Prezados pais e responsáveis: a reunião de pais e mestres será na próxima quarta-feira às 14h30.",
        "O INMET emitiu alerta de chuvas intensas para o litoral do Rio de Janeiro.",
        "A biblioteca municipal reabre hoje após duas semanas de reforma.",
        "Este documentário retrata a fauna e flora da Amazônia brasileira.",
        "O trem de alta velocidade está chegando à estação da Luz. Preparem-se para o desembarque.",
        "O entregador conseguiu entregar o pedido no horário, mesmo debaixo de chuva forte.",
        "Voluntários organizaram um mutirão de limpeza na praia de Copacabana no fim de semana.",
        "O MASP inaugura exposição especial com obras de Tarsila do Amaral.",
        "Durante o Carnaval, as ruas do Rio de Janeiro se enchem de foliões e blocos de rua.",
        "A confraternização de fim de ano da empresa será no dia 23 de dezembro num restaurante em Pinheiros.",
        "O MEC anunciou novas diretrizes para o ensino fundamental.",
        "A padaria do bairro vende pão de queijo artesanal que esgota todos os dias antes do meio-dia.",
        "Agora é possível emitir certidões pelo portal Gov.br sem sair de casa.",
        "A nova ciclovia conecta o Parque Ibirapuera à estação de metrô.",
        "Durante o feriado de Tiradentes, os principais pontos turísticos exigem agendamento prévio.",
        "Hoje é véspera de Natal. A família inteira se reúne para a ceia e a troca de presentes.",
        "Sua encomenda chegou ao locker. Retire-a usando o código de verificação.",
        "O refeitório passou a oferecer opções veganas e sem glúten no cardápio diário.",
        "Na sala de espera toca uma bossa nova suave que deixa o ambiente agradável.",
        "O simulado de evacuação acontecerá nesta sexta-feira às 10h no saguão principal.",
        "O jasmineiro do vizinho floresceu e o perfume se espalha por toda a rua.",
        "Hoje é o início oficial do inverno, mas em São Paulo o calor continua.",
        "A cafeteria nova está com promoção de inauguração: o segundo café sai pela metade do preço.",
        "O avô levanta todo dia às seis da manhã para caminhar no parque.",
        "A escola informa que o horário de saída será alterado a partir da próxima semana.",
        "A professora desenhou o mapa do Brasil no quadro e pediu aos alunos que apontassem as capitais dos estados.",
    ],
    "长难句": [
        "Embora o governo tenha implementado diversas medidas para estabilizar o mercado imobiliário, os preços dos imóveis nas grandes capitais continuam subindo sem trégua, gerando frustração crescente entre os que buscam a casa própria.",
        "Se a crise econômica não tivesse atingido o país com tanta intensidade naquela época, é provável que a reforma do sistema financeiro brasileiro tivesse tomado um rumo completamente diferente.",
        "Esta decisão judicial vai muito além da resolução de um caso específico, estabelecendo um precedente fundamental para a delimitação do alcance do direito à proteção de dados pessoais na era digital.",
        "Por mais que a tradução automática avance, reproduzir com fidelidade as nuances culturais e a sonoridade de uma obra literária continua sendo um desafio que a tecnologia ainda não conseguiu superar.",
        "Segundo o relatório do Tribunal de Contas, o órgão investigado desvirtuou os mecanismos de controle interno na execução orçamentária e recorreu sistematicamente a contratações sem licitação.",
        "A riqueza linguística do português, com suas variantes espalhadas por quatro continentes, constitui um patrimônio cultural cuja diversidade não deve ser vista como fragmentação, mas como fonte inesgotável de criatividade.",
        "Pretender resolver o problema do êxodo rural apenas com incentivos financeiros revela desconhecimento das causas estruturais que levam os jovens a abandonar o interior.",
        "A defesa do réu alegou que as provas digitais apresentadas pela acusação foram obtidas sem a devida autorização judicial, devendo ser consideradas nulas de pleno direito.",
        "O que torna os romances desse autor perturbadores é sua recusa em emitir julgamentos morais sobre os personagens, obrigando o leitor a tirar suas próprias conclusões éticas.",
        "Nos municípios do interior ameaçados pelo esvaziamento populacional, são oferecidos subsídios generosos para moradia, educação e saúde, mas a taxa de permanência continua decepcionante.",
        "Analisar a história contemporânea do Brasil sem considerar os impactos da ditadura militar seria como estudar uma árvore ignorando suas raízes.",
        "A elevação do nível do mar causada pelas mudanças climáticas ameaça populações costeiras, e a questão do cumprimento das metas de redução de emissões pelos países industrializados tornou-se uma questão de justiça global.",
        "As peças de cerâmica marajoara encontradas na escavação não são meros objetos decorativos, mas testemunhos históricos que lançam luz sobre as redes comerciais da Amazônia pré-colombiana.",
        "Mesmo que as negociações cheguem a bom termo, não se pode descartar que divergências de interpretação entre as partes reacendam o conflito na fase de implementação.",
        "Enquanto a autonomia do professor em sala de aula não for garantida, qualquer reforma educacional, por mais bem concebida que seja, estará fadada ao fracasso.",
        "O que provocou a controvérsia acadêmica não foi uma falha metodológica do estudo, mas a própria conclusão, que contradiz frontalmente a teoria dominante no campo.",
        "O advogado do autor argumentou que as evidências eletrônicas apresentadas pelo réu possuem vícios na cadeia de custódia que as tornam inadmissíveis como prova.",
        "O ditado diz para ensinar a pescar em vez de dar o peixe, mas que sentido faz ensinar a pescar a quem não tem como comprar uma vara?",
        "Num mundo em que as cadeias de suprimentos globais estão profundamente interligadas, a interrupção de um único elo pode desencadear efeitos em cascata de proporções imprevisíveis.",
        "Caso o comprador não conclua a inspeção dentro do prazo contratual, presume-se a aceitação tácita da conformidade do produto com os padrões de qualidade acordados.",
        "Cada vez mais evidências apontam que a exposição prolongada a poluentes ambientais em baixas doses pode causar danos neurológicos em crianças que só se manifestam na adolescência.",
        "O grande talento desse diretor está na capacidade de despertar empatia por cada personagem sem indicar ao espectador de quem deve sentir pena.",
        "Embora a tecnologia blockchain possa, em tese, resolver a questão da confiança em pagamentos internacionais, as diferenças entre os marcos regulatórios nacionais seguem sendo o principal entrave à adoção em larga escala.",
        "Os pergaminhos encontrados na escavação estavam muito deteriorados, mas a reflectografia infravermelha permitiu decifrar textos medievais inéditos de extraordinário valor filológico.",
        "O projeto desta ponte precisa suportar um tráfego diário de mais de cem mil veículos e, ao mesmo tempo, garantir a segurança estrutural diante de um terremoto de magnitude 7 ou superior.",
        "Seria um equívoco interpretar sua demissão como decisão pessoal; na verdade, trata-se de um protesto silencioso contra as concessões ideológicas sucessivas da diretoria.",
        "A falta de um mecanismo eficaz de coordenação interministerial faz com que, diante de crises sanitárias, cada órgão aja isoladamente, perdendo-se o momento ideal de intervenção.",
        "Até os economistas mais otimistas reconhecem que, num cenário de escalada das tensões comerciais internacionais, as perspectivas de crescimento das economias exportadoras pioraram significativamente.",
        "O que à primeira vista parece apenas uma briga de condomínio revela, após investigação, um emaranhado de irregularidades envolvendo venda irregular de unidades e desvio do fundo de reserva.",
        "A digitalização do ensino exige tratar simultaneamente três frentes: infraestrutura tecnológica, capacitação docente e segurança da informação.",
        "Quanto mais a sociedade depende da inteligência artificial para tomar decisões, mais premente se torna o debate sobre transparência algorítmica e responsabilização dos desenvolvedores.",
    ],
    "短文本": [
        "Confirmar", "Cancelar", "Enviar", "Voltar", "Avançar",
        "Salvar rascunho", "Comprar agora", "Adicionar ao carrinho", "Ver detalhes", "Esgotado",
        "Carregando", "Atualizar", "Pesquisar", "Configurações", "Minha conta",
        "Notificações", "Sair", "Alterar senha", "Verificar telefone", "Verificar identidade",
        "Em análise", "Aprovado", "Recusado", "Pendente", "Concluído",
        "Sem dados", "Erro de rede", "Tente novamente", "Sucesso", "Erro de entrada",
        "Selecionar tudo", "Excluir", "Editar", "Copiar link", "Compartilhar",
        "Favoritos", "Curtir", "Denunciar", "Bloquear", "Seguir",
        "Início", "Explorar", "Carrinho", "Perfil", "Ajuda",
    ],
    "数字日期": [
        "Quinta-feira, 14 de maio de 2026",
        "Valor do pedido: R$ 1.298,50",
        "Telefone: (11) 1234-5678",
        "Celular: (11) 91234-5678",
        "CPF: 123.456.789-00",
        "Código de rastreamento: BR1234567890123",
        "Horário de funcionamento: seg–sex 09h–17h30 (sáb, dom e feriados: fechado)",
        "Reunião: segunda-feira, 01/06/2026, das 14h às 16h30",
        "Temperatura: mínima 3 °C / máxima 28 °C",
        "Capital social: R$ 5.000.000,00 (cinco milhões de reais)",
        "Placa do veículo: ABC-1D23",
        "CEP: 01310-100",
        "Número do contrato: HT-2026-05-0378",
        "Conta bancária: Ag. 1234 / C/C 12345678-9 — Banco do Brasil",
        "Valor da fatura: R$ 86.400,00 (com impostos inclusos)",
        "Coordenadas: 23°33′01″ S, 46°38′02″ O",
        "Área: 128,56 m² (área útil: 96,32 m²)",
        "Voo LA3456, decolagem 08h45, pouso 11h20",
        "Senha: de 8 a 16 caracteres, incluindo maiúsculas, minúsculas e números",
        "Versão: v3.2.1-beta (build 20260514)",
        "Placar: 3 × 2 (prorrogação)",
        "Taxa de juros: 4,35% a.a. (0,3625% a.m.)",
        "Altitude: 4.718 metros acima do nível do mar",
        "Validade: 15/03/2027",
        "Código da ação: PETR4 (Petrobras PN)",
        "Endereço IP: 192.168.1.100:8080",
        "CNPJ: 12.345.678/0001-90",
        "Receita do 3º trimestre: +12,7% em relação ao mesmo período do ano anterior",
        "Embalagem: 500 ml × 24 unidades/caixa",
        "Raio de entrega: 5 km; tempo estimado: 30 a 45 minutos",
    ],
    "特殊字符": [
        "【AVISO IMPORTANTE】Calendário de feriados 2026",
        "«Grande Sertão: Veredas» — obra-prima de Guimarães Rosa",
        "Atenção: é proibido trazer alimentos e bebidas para o recinto!!!",
        "Preço: de R$ 29,80 → por R$ 19,80 (oferta por tempo limitado)",
        "Avaliação: ★★★★☆ (4,5/5,0)",
        "Rota: São Paulo → Curitiba → Florianópolis → Porto Alegre",
        "Sistemas operacionais: Windows / macOS / Linux (64 bits)",
        "Fórmula: E = mc², onde c ≈ 3×10⁸ m/s",
        "Obs.: preços sem impostos (±5% de variação)",
        "Contato: ☎ (11) 1234-5678 / ✉ contato@exemplo.com.br / 📍 Av. Paulista",
        "Progresso: ████████░░ 80%",
        "♻️ Separe os recicláveis na lixeira verde ♻️",
        "⚠️ Perigo: alta tensão 380 V — Proibida a entrada! ⚠️",
        "— Machado de Assis, Dom Casmurro: «Não consultes dicionários. Casmurro não está aqui no sentido que eles lhe dão…»",
        "【RESOLVIDO ✓】Erro 500 do servidor corrigido @todos",
        "Caracteres proibidos em nomes de arquivo: \\ / : * ? \" < > |",
        "Fórmula: ∑(i=1→n) aᵢ × bᵢ = a·b",
        "Química: 2H₂ + O₂ → 2H₂O (reação exotérmica)",
        "© 2026 Empresa Exemplo Ltda. Todos os direitos reservados.",
        "Emissão de CO₂: aprox. 2,3 kg/km²·ano⁻¹",
        "Força da senha: fraca ☠️ / média ⚡ / forte 💪",
        "【Encaminhado】@João @Maria Olhem isso! 🔥🔥🔥",
        "Alternativas: (a) Certo (b) Errado (c) Incerto (d) Nenhuma das anteriores",
        "1.º 🥇: R$ 100 mil | 2.º 🥈: R$ 50 mil | 3.º 🥉: R$ 20 mil",
        "═══════════════════════════════════════════",
        "Acentos: à á â ã ç é ê í ó ô õ ú — caracteres do português",
        "#viagem #gastronomia #diadiadivida #vlog",
        "✓ Feito  × Pendente  ○ Em andamento  △ Aguardando",
        "Emojis: 😀😂🤔😭🥰🤯👍🎉💯🔥❤️✅❌⚡🌈",
        "Multilíngue: Hoje almocei phở e estava おいしかった！",
    ],
    "边界场景": [
        "a" * 200,
        " " * 50 + "texto cercado por espaços" + " " * 50,
        "teste\ttabulação\tseparador\ttexto",
        "linha 1\nlinha 2\nlinha 3\nlinha 4\nlinha 5",
        "Esta é uma string de teste muito longa. " + "O sistema deve lidar corretamente com strings longas. " * 15,
        "",
        "   ",
        "aáeébícóôõuú mistura de vogais com e sem acento",
        "PortuguêsEnglish中文日本語한국어العربية mistura multilíngue",
        "ＡＢＣＤＥ１２３４５ caracteres de largura total",
        "①②③④⑤⑥⑦⑧⑨⑩ números circundados",
        "㎡ ㎝ ㎞ ㎏ ℃ ℉ unidades especiais",
        "Sinais repetidos!!!!!?????.....",
        "semespaço" + "abcdefghijklmnopqrstuvwxyz" * 10,
        "Acentuação: pêlo/pelo, pára/para, côa/coa — antes e depois do acordo ortográfico",
        "Ç ç — cedilha, caractere exclusivo do português",
        "Emoji repetido: " + "😀" * 100,
        "Espaços especiais: normal não-quebrável fino largo",
        "\u200EMarca LTR e \u200Fmarca RTL misturadas",
        "Números densos: 12345678901234567890.12345678901234567890",
        "Pontuação mista: Teste, this is a test.",
        "Quebras de linha mistas\r\nWindows\nUnix\rMac antigo",
        "HTML: <script>alert('XSS')</script><b>negrito</b>",
        "SQL injection: '; DROP TABLE users; --",
        "Caminho: C:\\Users\\Teste\\Documentos\\relatório.xlsx",
        "URL: https://exemplo.com.br/busca?termo=teste&página=1#resultados",
        "Recuo extremo:" + "\t" * 20 + "texto com recuo profundo",
        "Linhas em branco consecutivas:\n\n\n\n\nTexto após 5 linhas em branco",
        "Trema: linguiça, cinquenta, tranquilo — trema removido pelo acordo ortográfico",
        "Abreviações: Sr., Sra., Dr., Dra., V. Ex.ª, n.º, p., pág.",
        "Gíria vs. formal: 'tá' vs. 'está', 'pra' vs. 'para', 'né' vs. 'não é'",
    ],
    "专业术语": [
        "Nos termos do artigo 389 do Código Civil, o devedor responde por perdas e danos em caso de não cumprimento da obrigação, salvo se a prestação se tornar impossível sem culpa.",
        "Paciente deu entrada na emergência com dor torácica retroesternal em aperto irradiando para MSE; ECG com supradesnivelamento de ST em parede inferior — hipótese de IAM com supra de ST.",
        "O sistema utiliza arquitetura de microsserviços com API Gateway para autenticação e controle de tráfego; a comunicação entre serviços é feita via gRPC.",
        "O ágio (goodwill) no balanço patrimonial consolidado ao final do período é de R$ 12,8 bilhões, aumento de 23,5% em relação ao mesmo período do ano anterior.",
        "Conforme o CPC, o réu será citado para apresentar contestação no prazo de 15 dias úteis, contados da data da juntada do mandado aos autos.",
        "Laudo anatomopatológico: carcinoma ductal invasivo de mama esquerda, grau II. Imuno-histoquímica: RE(+), RP(+), HER2 (2+), FISH negativo.",
        "O modelo atingiu acurácia Top-1 de 87,3% no conjunto de validação do ImageNet, com latência de inferência de 2,1 ms por imagem em GPU A100.",
        "As ações ordinárias da emissora foram admitidas à negociação na B3 em 8 de maio de 2026. Código de negociação: XXXX3.",
        "O fundo pode investir em ações listadas, títulos públicos, debêntures, instrumentos do mercado monetário e derivativos.",
        "RM de crânio com contraste: lesão expansiva de 3,2 × 2,8 × 2,5 cm no lobo temporal direito com realce heterogêneo.",
        "Caso o executado não cumpra a obrigação no prazo fixado, o juiz determinará a penhora de bens suficientes para satisfação do crédito.",
        "A rodada de captação Série B foi liderada por um fundo de venture capital de primeira linha, com valuation post-money de aproximadamente R$ 17,5 bilhões.",
        "A orquestração de contêineres é feita por cluster Kubernetes, com gerenciamento do ciclo de vida via Helm Charts e observabilidade com Prometheus + Grafana.",
        "Este medicamento é de uso sob prescrição médica e está contraindicado para pacientes com hipersensibilidade a qualquer componente da fórmula. Em caso de insuficiência hepática ou renal, ajuste de dose é necessário.",
        "O licenciante concede ao licenciado o direito exclusivo de distribuição no território nacional por prazo de três anos a contar da vigência do contrato.",
        "Contribuição previdenciária (INSS): empregador 20% sobre a folha; empregado de 7,5% a 14% conforme faixa salarial.",
        "A hemoglobina glicada (HbA1c) do paciente é de 9,2% e a glicemia de jejum é de 14,6 mmol/L — recomenda-se início de insulinoterapia intensiva.",
        "O treinamento utilizou o otimizador AdamW com taxa de aprendizado inicial de 3×10⁻⁴, schedule cosine annealing, 100 épocas e batch size de 256.",
        "A receita líquida consolidada do exercício de 2025 foi de R$ 58,72 bilhões (+18,6% a/a); o lucro líquido atribuído aos acionistas controladores foi de R$ 6,43 bilhões.",
        "O RTO do sistema é de 4 horas e o RPO de 1 hora, atendendo aos requisitos do Plano de Continuidade de Negócios (PCN) nível 3.",
        "Pedidos: 1. Condenar o réu a cessar a violação da marca registrada do autor. 2. Condenar o réu ao pagamento de indenização de R$ 5 milhões.",
        "Prescrição: amoxicilina 500 mg cápsulas, 3×/dia após refeições, 7 dias; ibuprofeno 300 mg liberação prolongada, 2×/dia se dor.",
        "O SoC é fabricado no processo TSMC de 5 nm, integra 12 bilhões de transistores, clock máximo de 3,5 GHz e TDP de 65 W.",
        "Mudança de política contábil: a companhia adotou o CPC 47 / IFRS 15 a partir de 1º de janeiro de 2026, com aplicação retrospectiva integral.",
        "Configuração do pool de conexões: máximo de conexões 200, mínimo ocioso 20, timeout de conexão 30 segundos.",
        "Nos termos do art. 477 da CLT, na rescisão do contrato de trabalho, o empregador deve efetuar o pagamento das verbas rescisórias no prazo de 10 dias.",
        "3º dia pós-operatório de troca valvar aórtica: sinais vitais estáveis, débito do dreno torácico em queda; programada retirada do dreno amanhã.",
        "O sistema sustenta throughput de 100k QPS com latência p99 ≤ 200 ms.",
        "A operação configura aquisição relevante de ativos e depende de aprovação em assembleia geral de acionistas e anuência da CVM.",
        "Mecanismo de privacidade diferencial: ruído de Laplace é injetado na etapa de agregação de dados, com orçamento de privacidade ε = 1,0.",
    ],
    "口语俚语": [
        "Sério?! Não acredito! Jura que é verdade?!",
        "Kkkkkkk tô morrendo de rir, muito bom!",
        "Ué? Eu fui o último a saber? Valeu, hein...",
        "Bora! Vamos logo que se chegar tarde não pega lugar!",
        "Tava muito bom! A gente tem que voltar lá!",
        "Ah não, isso não tá certo. Pegaram pesado demais.",
        "Com certeza. Você tem toda razão.",
        "Preguiça... Hoje não quero fazer nada, nada mesmo.",
        "Mano, isso é insano! Que coisa incrível!",
        "Beleza, deixa comigo!",
        "Que inveja... Também quero viajar...",
        "Tipo assim... sei lá... é complicado, sabe?",
        "Ai que saco, chovendo de novo!",
        "Bora comer alguma coisa? Tô morrendo de fome.",
        "Caraca, tu é fera! Primeiro lugar? Que orgulho!",
        "Cê é doido? Quem faz isso?",
        "Fiz na moral, sem esquentar a cabeça.",
        "Desculpa incomodar de novo, mas preciso de mais uma ajuda...",
        "Relaxa, tá tudo bem. Não é o fim do mundo.",
        "Tá bom assim. Não precisa de mais nada.",
        "Uau, que top! Demais!",
        "Tá, tanto faz. Como você quiser.",
        "Para com isso, vai. Chega.",
        "Quero muito ir! Me leva junto!",
        "Não esquece, hein?! Prometeu! É importante!",
        "Fechou! Já vou resolver!",
        "Nossa, que difícil... Minha cabeça vai explodir.",
        "AAAA!!! Minha banda favorita vem pro Brasil!!! Ingressos já!!!",
        "Hm... é... tá... tudo bem...",
        "Irmão, me ajuda aí? É urgente, por favor!",
        "Corre que tá acabando! Últimas unidades!",
    ],
}
