LANG_NAME = "越南语"
LANG_CODE = "vi-VN"

TEMPLATES = {
    "常规文案": [
        "Dự báo thời tiết hôm nay cho biết Hà Nội sẽ có mưa rào và giông vào chiều tối.",
        "Thông báo: Hệ thống sẽ tạm ngừng hoạt động từ 2 giờ đến 6 giờ sáng ngày mai để bảo trì.",
        "Tuyến metro số 1 Bến Thành – Suối Tiên đã chính thức đi vào vận hành thương mại.",
        "Nhà hàng mới khai trương combo trưa gồm cơm, canh, món mặn và tráng miệng.",
        "Ban quản lý chung cư thông báo về việc lắp đặt hệ thống camera giám sát mới.",
        "Kính mời phụ huynh tham dự buổi họp phụ huynh vào thứ Tư tuần sau lúc 14 giờ 30.",
        "Trung tâm Khí tượng Thủy văn cảnh báo bão số 4 đang tiến vào biển Đông.",
        "Thư viện tầng 2 đã mở cửa trở lại phục vụ bạn đọc từ hôm nay.",
        "Bộ phim tài liệu ghi lại cuộc sống của người dân vùng cao Tây Bắc.",
        "Sân bay Tân Sơn Nhất dự kiến đón hơn 130.000 lượt khách trong dịp Tết.",
        "Shipper vẫn giao hàng đúng giờ dù trời mưa to gió lớn.",
        "Đoàn thanh niên tình nguyện tổ chức dọn vệ sinh bãi biển vào cuối tuần.",
        "Bảo tàng Lịch sử khai mạc triển lãm cổ vật thời Lý – Trần.",
        "Dịp Tết Nguyên Đán, ga Sài Gòn tấp nập người về quê đón Tết.",
        "Liên hoan cuối năm của công ty sẽ tổ chức tại khách sạn Rex vào ngày 28 tháng Chạp.",
        "Bộ Giáo dục và Đào tạo ban hành thông tư mới về đánh giá học sinh tiểu học.",
        "Tiệm bánh mì Bà Hoa nổi tiếng ở Sài Gòn lúc nào cũng đông khách xếp hàng.",
        "Người dân có thể đăng ký làm căn cước công dân trực tuyến qua ứng dụng VNeID.",
        "Con đường ven sông mới xây nối liền công viên với khu dân cư.",
        "Trong dịp lễ 30/4 – 1/5, các điểm du lịch yêu cầu đặt vé trước.",
        "Đêm Trung thu, trẻ con rước đèn ông sao đi khắp phố phường.",
        "Bưu phẩm đã được gửi đến tủ locker, vui lòng nhận hàng trong 48 giờ.",
        "Căng tin trường mới thêm quầy bán đồ chay phục vụ giáo viên và học sinh.",
        "Phòng chờ phát nhạc nhẹ nhàng, hành khách ngồi đọc sách chờ lên máy bay.",
        "Buổi diễn tập phòng cháy chữa cháy sẽ diễn ra vào thứ Sáu tuần này.",
        "Hàng xóm trồng hoa sứ trước nhà, hương thơm thoang thoảng cả con hẻm.",
        "Hôm nay là ngày Lập Thu nhưng Sài Gòn vẫn nóng như đổ lửa.",
        "Quán trà sữa mới khai trương giảm giá 50% cho ly thứ hai.",
        "Ông ngoại mỗi sáng đều dậy sớm đi tập dưỡng sinh ở công viên.",
        "Nhà trường thông báo thay đổi giờ đón trả học sinh từ tuần sau.",
        "Cô giáo vẽ bản đồ Việt Nam lên bảng, cho học sinh tìm tên các tỉnh thành.",
    ],
    "长难句": [
        "Mặc dù Chính phủ đã ban hành hàng loạt chính sách bình ổn giá, nhưng giá cả sinh hoạt tại các thành phố lớn vẫn không ngừng leo thang, khiến đời sống người lao động ngày càng khó khăn.",
        "Nếu như dự án đường sắt tốc độ cao Bắc – Nam được triển khai đúng tiến độ, thì việc đi lại giữa Hà Nội và TP.HCM sẽ chỉ mất khoảng 5 tiếng thay vì 30 tiếng như hiện nay.",
        "Bản hợp đồng này có điều khoản về quyền sở hữu trí tuệ được diễn đạt một cách mơ hồ đến mức cả hai bên đã phải thương lượng suốt hai tháng mà vẫn chưa đạt được thỏa thuận.",
        "Vấn đề già hóa dân số kết hợp với tỷ lệ sinh giảm mạnh đang đặt ra thách thức nghiêm trọng cho hệ thống an sinh xã hội, đặc biệt là quỹ bảo hiểm xã hội.",
        "Kết quả kiểm toán cho thấy dự án có nhiều sai phạm nghiêm trọng trong khâu đấu thầu, một số thành viên hội đồng chấm thầu có mối quan hệ lợi ích với nhà thầu.",
        "Phong cách viết của nhà văn thoạt nhìn có vẻ giản dị nhưng thực chất ẩn chứa nhiều tầng ý nghĩa sâu xa, thường khiến người đọc phải suy ngẫm rất lâu.",
        "Trong bối cảnh giá nguyên liệu đầu vào đã tăng hơn 40% trong ba quý liên tiếp, doanh nghiệp buộc phải tính toán lại chi phí sản xuất và điều chỉnh giá bán.",
        "Y học cổ truyền Việt Nam chú trọng biện chứng luận trị, cùng một triệu chứng nhưng ở những người có thể trạng khác nhau có thể cần phương pháp điều trị hoàn toàn khác biệt.",
        "Tranh dân gian Đông Hồ không chỉ là tác phẩm nghệ thuật mà còn là tấm gương phản chiếu đời sống văn hóa, phong tục tập quán của người Việt qua nhiều thế kỷ.",
        "Thay vì tiêu tốn năng lượng vào những suy đoán vô căn cứ, tốt hơn hết là chờ kết quả điều tra chính thức rồi hãy đưa ra phán xét.",
        "Dù công nghệ blockchain về mặt lý thuyết có thể giải quyết vấn đề tin cậy trong thanh toán xuyên biên giới, nhưng sự khác biệt lớn về khung pháp lý giữa các quốc gia vẫn là rào cản chính cho việc ứng dụng đại trà.",
        "Những thẻ tre khai quật được tuy bị hư hại nặng nề, nhưng nhờ công nghệ chụp ảnh hồng ngoại, các nhà nghiên cứu đã nhận diện được nhiều đoạn văn cổ chưa từng xuất hiện trong tài liệu truyền đời.",
        "Cây cầu này được thiết kế để vừa đáp ứng lưu lượng hơn 100.000 lượt xe mỗi ngày, vừa đảm bảo an toàn kết cấu trong điều kiện động đất cấp 8 trở lên.",
        "Cuộc cách mạng công nghiệp 4.0 đang đặt ra yêu cầu cấp bách về việc đổi mới giáo dục, từ nội dung chương trình đến phương pháp giảng dạy, nhằm trang bị cho thế hệ trẻ những kỹ năng phù hợp với thị trường lao động tương lai.",
        "Anh ấy mất ba năm trời mới nhận ra rằng điều thực sự cản trở sự tiến bộ trong học tập không phải là năng lực trí tuệ, mà là lối tư duy sợ sai, không dám đặt câu hỏi.",
        "Trong phiên tòa sơ thẩm, luật sư bên bị đơn lập luận rằng các bằng chứng điện tử do nguyên đơn cung cấp có sai sót về thủ tục thu thập, do đó không có giá trị pháp lý.",
        "Tục ngữ có câu 'cho cần câu thay vì cho con cá', nhưng trong bối cảnh thất nghiệp hệ thống hiện nay, khi người ta không đủ tiền mua cần câu thì nói gì đến việc học câu cá.",
        "Trong thế giới mà chuỗi cung ứng toàn cầu đan xen phức tạp, bất kỳ sự gián đoạn nào tại một mắt xích quan trọng đều có thể gây ra phản ứng dây chuyền vượt xa dự đoán.",
        "Ngày càng nhiều bằng chứng cho thấy việc tiếp xúc lâu dài với ô nhiễm môi trường ở liều lượng thấp có thể gây tổn thương thần kinh ở trẻ em, nhưng hậu quả chỉ biểu hiện rõ ràng khi đến tuổi dậy thì hoặc trưởng thành.",
        "Điều đáng nói nhất về đạo diễn này là ông không bao giờ trực tiếp bảo khán giả nên đồng cảm với ai, mà thông qua ngôn ngữ hình ảnh tinh tế, để mỗi số phận trong phim đều chạm đến trái tim người xem.",
        "Càng phụ thuộc vào trí tuệ nhân tạo trong việc ra quyết định, càng xuất hiện nhiều câu hỏi đạo đức cốt lõi về sự minh bạch và công bằng của các hệ thống thuật toán.",
        "Bên A không hoàn thành nghiệm thu trong thời hạn hợp đồng quy định thì được coi là mặc nhiên chấp nhận thành quả do Bên B bàn giao đạt tiêu chuẩn chất lượng.",
        "Di sản Hoàng thành Thăng Long không chỉ có giá trị khảo cổ học mà còn là minh chứng sống động cho hơn một nghìn năm lịch sử dựng nước và giữ nước của dân tộc Việt Nam.",
        "Cho dù nền kinh tế có dấu hiệu phục hồi, nhưng đối với doanh nghiệp vừa và nhỏ, việc tiếp cận nguồn vốn vay với lãi suất hợp lý vẫn là bài toán nan giải.",
        "Hệ thống giáo dục mà chỉ chạy theo thành tích và bằng cấp thay vì phát triển tư duy sáng tạo thì khó lòng đào tạo ra những con người đáp ứng được yêu cầu của thời đại.",
        "Nghịch lý là ở chỗ, chính những vùng cần đầu tư cơ sở hạ tầng nhất lại là những nơi nhận được ít ngân sách nhất, bởi nguồn thu thuế tại chỗ quá thấp.",
        "Phim của đạo diễn này dù bị giới phê bình chê là dài dòng và quá nặng tính biểu tượng, nhưng vẫn giành giải Cành cọ Vàng tại Liên hoan phim Cannes bằng quyết định nhất trí của ban giám khảo.",
        "Trong điều kiện mà cứ ba sinh viên sư phạm ra trường thì có một người bỏ nghề trong năm năm đầu, việc nói đến nâng cao chất lượng giáo dục mà không cải thiện đãi ngộ cho giáo viên là điều không thực tế.",
        "Dự thảo luật không chỉ mâu thuẫn với các cam kết quốc tế về bảo vệ dữ liệu cá nhân mà còn tạo tiền lệ cho việc mở rộng quyền hạn của cơ quan an ninh một cách thiếu kiểm soát.",
        "Ẩm thực Việt Nam phong phú đến mức mỗi vùng miền đều có những món ăn đặc trưng không nơi nào có, từ phở Hà Nội, bún bò Huế, đến cơm tấm Sài Gòn, tạo nên một bức tranh văn hóa ẩm thực đa dạng và độc đáo.",
    ],
    "短文本": [
        "Xác nhận", "Hủy", "Gửi", "Quay lại", "Tiếp theo",
        "Lưu nháp", "Mua ngay", "Thêm vào giỏ", "Xem chi tiết", "Hết hàng",
        "Đang tải", "Làm mới", "Tìm kiếm", "Cài đặt", "Tài khoản",
        "Thông báo", "Đăng xuất", "Đổi mật khẩu", "Xác minh SĐT", "Xác thực danh tính",
        "Đang xét duyệt", "Đã duyệt", "Bị từ chối", "Chờ xử lý", "Hoàn thành",
        "Không có dữ liệu", "Lỗi mạng", "Vui lòng thử lại", "Thành công", "Dữ liệu không hợp lệ",
        "Chọn tất cả", "Xóa", "Chỉnh sửa", "Sao chép liên kết", "Chia sẻ",
        "Lưu lại", "Thích", "Báo cáo", "Chặn", "Theo dõi",
        "Trang chủ", "Khám phá", "Giỏ hàng", "Cá nhân", "Hỗ trợ",
    ],
    "数字日期": [
        "Ngày 14 tháng 5 năm 2026",
        "Tổng tiền: 42.850.000₫",
        "Điện thoại: (028) 1234 5678",
        "Di động: 0912 345 678",
        "CCCD: 001234567890",
        "Mã vận đơn: VNPOST1234567890",
        "Giờ làm việc: Thứ 2 – Thứ 6, 08:00 – 17:00",
        "Họp: Thứ Hai ngày 01/06/2026, 14:00 – 16:30",
        "Nhiệt độ: 18°C – 38°C",
        "Vốn điều lệ: 5.000.000.000 đồng (năm tỷ đồng)",
        "Biển số xe: 51F-123.45",
        "Mã bưu chính: 700000",
        "Số hợp đồng: HT-2026-05-0378",
        "Số tài khoản: 1234567890 – Vietcombank CN HCM",
        "Số tiền hóa đơn: 86.400.000₫ (đã bao gồm VAT)",
        "Tọa độ: 10°46′10″B, 106°40′55″Đ",
        "Diện tích: 128,56 m² (diện tích sàn)",
        "Chuyến bay VN123, cất cánh 08:45, hạ cánh 11:20",
        "Mật khẩu: 8-16 ký tự, gồm chữ hoa, chữ thường và số",
        "Phiên bản: v3.2.1-beta (build 20260514)",
        "Tỷ số: 3-2 (hiệp phụ)",
        "Lãi suất: 4,35%/năm",
        "Độ cao: 4.718 mét so với mực nước biển",
        "Hạn sử dụng: 15/03/2027",
        "Mã chứng khoán: VNM (Vinamilk)",
        "Địa chỉ IP: 192.168.1.100:8080",
        "Mã số thuế: 0123456789",
        "Doanh thu quý 3 tăng 12,7% so với cùng kỳ",
        "Quy cách: 500ml × 24 chai/thùng",
        "Phạm vi giao hàng: bán kính 5km, dự kiến 30-45 phút",
    ],
    "特殊字符": [
        "【THÔNG BÁO QUAN TRỌNG】Về lịch nghỉ Tết Nguyên Đán 2026",
        "《Truyện Kiều》— kiệt tác văn học Việt Nam",
        "Lưu ý: Không mang đồ ăn thức uống vào thư viện!!!",
        "Giá: từ 299.000₫ → còn 199.000₫ (khuyến mãi có hạn)",
        "Đánh giá: ★★★★☆ (4.5/5.0)",
        "Lộ trình: Hà Nội → Huế → Đà Nẵng → Nha Trang → TP.HCM",
        "Hỗ trợ: Windows / macOS / Linux (64-bit)",
        "Công thức: E = mc², c ≈ 3×10⁸ m/s",
        "Ghi chú: Giá chưa bao gồm VAT (±5%)",
        "Liên hệ: ☎ (028) 1234 5678 / ✉ info@example.vn / 📍 Quận 1",
        "Tiến độ: ████████░░ 80%",
        "♻️ Hãy phân loại rác tái chế ♻️",
        "⚠️ Nguy hiểm: Điện áp 380V – Cấm sờ! ⚠️",
        "— Nguyễn Du, Truyện Kiều: «Trăm năm trong cõi người ta…»",
        "【ĐÃ SỬA ✓】Lỗi server 500 đã được khắc phục @all",
        "Tên file không được chứa: \\ / : * ? \" < > |",
        "Toán: ∑(i=1→n) aᵢ × bᵢ = a·b",
        "Hóa học: 2H₂ + O₂ → 2H₂O (phản ứng tỏa nhiệt)",
        "© 2026 Công ty TNHH Mẫu. Bản quyền thuộc về công ty.",
        "CO₂: khoảng 2,3 kg/km²·năm⁻¹",
        "Độ mạnh mật khẩu: yếu ☠️ / trung bình ⚡ / mạnh 💪",
        "【Chuyển tiếp】@Minh @Lan xem cái này! 🔥🔥🔥",
        "Đáp án: (A) Đúng  (B) Sai  (C) Chưa rõ  (D) Không có đáp án",
        "Giải nhất 🥇: 10 triệu | Giải nhì 🥈: 5 triệu | Giải ba 🥉: 2 triệu",
        "═══════════════════════════════════════════",
        "Dấu tiếng Việt: ă â đ ê ô ơ ư / à ả ã á ạ / ằ ẳ ẵ ắ ặ",
        "#dulich #amthuc #cuocsong #vlog",
        "✓ Xong  × Chưa xong  ○ Đang làm  △ Chờ xác nhận",
        "Emoji: 😀😂🤔😭🥰🤯👍🎉💯🔥❤️✅❌⚡🌈",
        "Đa ngôn ngữ: Hôm nay ăn おにぎり, 맛있었어요!",
    ],
    "边界场景": [
        "a" * 200,
        " " * 50 + "văn bản bao quanh bởi khoảng trắng" + " " * 50,
        "kiểm\ttra\ttab\tphân\tcách",
        "dòng 1\ndòng 2\ndòng 3\ndòng 4\ndòng 5",
        "Đây là đoạn văn bản rất dài " + "để kiểm tra khả năng xử lý chuỗi dài " * 15 + "kết thúc tại đây.",
        "",
        "   ",
        "aàbảcãdáeạ tiếng Việt xen lẫn ký tự",
        "ViệtEnglish中文한국어日本語ทดสอบ nhiều ngôn ngữ",
        "Dấu thanh chồng: ằ ẳ ẵ ắ ặ ồ ổ ỗ ố ộ ừ ử ữ ứ ự",
        "ＡＢＣＤＥ１２３４５ ký tự toàn chiều rộng",
        "Ký tự zero-width: kiểm​tra​ẩn​ký​tự",
        "()[]{}⟨⟩«»‹› các loại ngoặc",
        "①②③④⑤⑥⑦⑧⑨⑩ số trong vòng tròn",
        "㎡ ㎝ ㎞ ㎏ ℃ ℉ đơn vị đặc biệt",
        "Dấu câu liên tục!!!!!?????.....",
        "khôngcódấucách" + "abcdefghijklmnopqrstuvwxyz" * 10,
        "Chính tả: sữa/sửa, dành/giành, dể/dễ — lỗi thường gặp",
        "Từ láy: long lanh, lấp lánh, mênh mông, bát ngát, thênh thang",
        "Emoji lặp lại: " + "😀" * 100,
        "Khoảng trắng đặc biệt: thường không ngắt mỏng rộng",
        "\u200EDấu LTR và \u200Fdấu RTL trộn lẫn",
        "Số dày đặc: 12345678901234567890.12345678901234567890",
        "Trộn dấu câu: Kiểm tra, this is a test.",
        "Xuống dòng: \r\nWindows\nUnix\rMac cũ",
        "HTML: <script>alert('XSS')</script><b>in đậm</b>",
        "SQL injection: '; DROP TABLE users; --",
        "Đường dẫn: C:\\Users\\Kiểm tra\\Tài liệu\\báo cáo.xlsx",
        "URL: https://example.com/tìm-kiếm?từ-khóa=kiểm-tra&trang=1#kết-quả",
        "Thụt lề cực đoan:" + "\t" * 20 + "văn bản thụt lề sâu",
        "Nhiều dòng trống:\n\n\n\n\nVăn bản sau 5 dòng trống",
    ],
    "专业术语": [
        "Theo quy định tại Điều 351 Bộ luật Dân sự 2015, bên vi phạm nghĩa vụ phải chịu trách nhiệm bồi thường toàn bộ thiệt hại, trừ trường hợp có thỏa thuận khác hoặc luật có quy định khác.",
        "Bệnh nhân nhập viện với triệu chứng đau ngực sau xương ức lan ra vai trái, ECG cho thấy ST chênh lên, chẩn đoán sơ bộ: nhồi máu cơ tim cấp có ST chênh lên.",
        "Hệ thống sử dụng kiến trúc microservices, API Gateway đảm nhiệm xác thực và giới hạn lưu lượng, giao tiếp giữa các service qua gRPC.",
        "Tại thời điểm cuối kỳ báo cáo, lợi thế thương mại trên bảng cân đối kế toán hợp nhất là 12.800 tỷ đồng, tăng 23,5% so với cùng kỳ năm trước.",
        "Theo Bộ luật Tố tụng Dân sự, bị đơn có quyền nộp bản tự bảo vệ quyền lợi trong thời hạn 15 ngày kể từ ngày nhận được thông báo thụ lý vụ án.",
        "Kết quả giải phẫu bệnh: ung thư biểu mô ống xâm nhập vú trái, độ mô học II, ER(+), PR(+), HER2 (2+), FISH âm tính.",
        "Mô hình đạt Top-1 accuracy 87,3% trên tập ImageNet validation, inference latency 2,1ms/ảnh trên A100 GPU.",
        "Cổ phiếu của công ty đã niêm yết trên Sở Giao dịch Chứng khoán TP.HCM ngày 08/05/2026, mã chứng khoán: XYZ.",
        "Quỹ đầu tư vào trái phiếu chính phủ, trái phiếu doanh nghiệp, tiền gửi, công cụ phái sinh và cổ phiếu niêm yết.",
        "MRI sọ não có tiêm thuốc đối quang: khối u 3,2×2,8×2,5 cm vùng thái dương phải, ngấm thuốc không đồng nhất.",
        "Tòa án ra quyết định kê biên tài sản của người phải thi hành án do không tự nguyện thi hành bản án trong thời hạn ấn định.",
        "Vòng gọi vốn Series B do quỹ đầu tư hàng đầu dẫn dắt, định giá sau đầu tư khoảng 350 triệu USD.",
        "Container orchestration sử dụng Kubernetes cluster, quản lý application lifecycle qua Helm Charts, giám sát bằng Prometheus + Grafana.",
        "Thuốc này là thuốc kê đơn, chống chỉ định với bệnh nhân mẫn cảm với bất kỳ thành phần nào. Cần chỉnh liều ở bệnh nhân suy gan, suy thận.",
        "Bên A cấp quyền phân phối độc quyền cho Bên B trên lãnh thổ Việt Nam, thời hạn 3 năm kể từ ngày hợp đồng có hiệu lực.",
        "Tỷ lệ đóng BHXH: người lao động 8%, người sử dụng lao động 17,5% trên mức lương tháng đóng BHXH.",
        "Chỉ số HbA1c: 9,2%; đường huyết lúc đói: 14,6 mmol/L — khuyến nghị bắt đầu liệu pháp insulin tích cực.",
        "Huấn luyện dùng AdamW optimizer, learning rate khởi đầu 3e-4, cosine annealing, 100 epochs, batch size 256.",
        "Doanh thu năm 2025 đạt 58.720 tỷ đồng, tăng 18,6% so với năm trước; lợi nhuận sau thuế đạt 6.430 tỷ đồng.",
        "Hệ thống có RTO ≤ 4 giờ và RPO ≤ 1 giờ, đáp ứng yêu cầu an toàn thông tin cấp độ 3.",
        "Yêu cầu khởi kiện: 1) Buộc bị đơn chấm dứt hành vi xâm phạm nhãn hiệu; 2) Bồi thường thiệt hại 5 tỷ đồng.",
        "Đơn thuốc: Amoxicillin 500mg × 3 lần/ngày × 7 ngày; Ibuprofen 300mg × 2 lần/ngày khi đau.",
        "Chip sản xuất trên công nghệ TSMC 5nm, 12 tỷ transistor, xung nhịp tối đa 3,5 GHz, TDP 65W.",
        "Thay đổi chính sách kế toán: Áp dụng IFRS 15 từ ngày 01/01/2026, phương pháp hồi tố toàn phần.",
        "Connection pool: max connections 200, min idle 20, connection timeout 30 giây.",
        "Theo Bộ luật Lao động, khi chấm dứt HĐLĐ do thay đổi cơ cấu tổ chức, người sử dụng LĐ phải chi trả trợ cấp mất việc theo quy định.",
        "Sau phẫu thuật thay van động mạch chủ ngày thứ 3, sinh hiệu ổn định, lượng dịch dẫn lưu giảm dần, dự kiến rút dẫn lưu ngày mai.",
        "Hệ thống duy trì throughput 100k QPS tại p99 latency ≤ 200ms.",
        "Giao dịch này thuộc diện phải công bố thông tin bất thường và cần được ĐHCĐ thông qua.",
        "Cơ chế differential privacy: thêm nhiễu Laplacian vào quá trình tổng hợp dữ liệu, privacy budget ε = 1,0.",
    ],
    "口语俚语": [
        "Trời ơi, buồn cười quá đi! Không nhịn được luôn á.",
        "Ê, cái này cute ghê nè! Mua đi mua đi!",
        "Gì kỳ vậy trời? Ai mà làm kiểu đó?",
        "Chill đi, từ từ rồi tính, đừng có gấp.",
        "Ngon bá cháy luôn nha! Phải quay lại ăn lần nữa!",
        "Thiệt hả? Đừng có nói xạo nghe!",
        "Ngơ ngác luôn, không hiểu ổng đang nghĩ gì.",
        "Mệt muốn xỉu luôn, về nhà ngủ thôi.",
        "Đỉnh của chóp luôn! Làm kiểu gì hay vậy?",
        "Oke chiến luôn! Đặt đi đừng có lưỡng lự!",
        "Ghen tị ghê, lại được đi du lịch nữa rồi!",
        "Kiểu như là... cũng không biết nói sao nữa.",
        "Trời ơi, chán quá! Mưa hoài mưa mãi.",
        "Đi ăn không? Đói bụng quá rồi nè.",
        "Xỉu ngang xỉu dọc luôn! Em giỏi quá vậy!",
        "Điên rồi à, ai mà làm vậy chứ!",
        "Thong thả thôi, đi đến đâu hay đến đó.",
        "Ngại quá, lại phải phiền anh chị nữa rồi.",
        "Bình tĩnh đi, đừng có căng thẳng quá.",
        "Vậy đủ rồi, không cần thêm gì nữa đâu.",
        "Wao, xịn ghê! Quá đỉnh luôn!",
        "Cũng được, tùy bạn thôi.",
        "Thôi đi nha, đừng có nhiều chuyện.",
        "Muốn xem lắm luôn! Đi coi chung nha!",
        "Nhớ nha, nhớ nha! Quên là chết đó!",
        "Ok luôn! Để mình lo!",
        "Khó quá trời quá đất! Game này hack não thật sự!",
        "Aaaaa! Idol mình sang Việt Nam biểu diễn nè!",
        "Ơ... hả... ờ... thôi cũng không sao đâu.",
        "Anh ơi, giúp em với được không ạ? Gấp lắm ạ!",
        "Nhanh lên! Chậm là hết nha! Số lượng có hạn!",
    ],
}
